// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: secretflow/protos/approval/vote_result.proto

package org.secretflow.proto.approval;

public final class VoteResult {
  private VoteResult() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:secretflow.approval.Result)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.secretflow.approval.Request vote_request = 1;</code>
     * @return Whether the voteRequest field is set.
     */
    boolean hasVoteRequest();
    /**
     * <code>.secretflow.approval.Request vote_request = 1;</code>
     * @return The voteRequest.
     */
    org.secretflow.proto.approval.VoteRequest.Request getVoteRequest();
    /**
     * <code>.secretflow.approval.Request vote_request = 1;</code>
     */
    org.secretflow.proto.approval.VoteRequest.RequestOrBuilder getVoteRequestOrBuilder();

    /**
     * <code>repeated .secretflow.approval.Invite vote_invite = 2;</code>
     */
    java.util.List<org.secretflow.proto.approval.VoteInvite.Invite> 
        getVoteInviteList();
    /**
     * <code>repeated .secretflow.approval.Invite vote_invite = 2;</code>
     */
    org.secretflow.proto.approval.VoteInvite.Invite getVoteInvite(int index);
    /**
     * <code>repeated .secretflow.approval.Invite vote_invite = 2;</code>
     */
    int getVoteInviteCount();
    /**
     * <code>repeated .secretflow.approval.Invite vote_invite = 2;</code>
     */
    java.util.List<? extends org.secretflow.proto.approval.VoteInvite.InviteOrBuilder> 
        getVoteInviteOrBuilderList();
    /**
     * <code>repeated .secretflow.approval.Invite vote_invite = 2;</code>
     */
    org.secretflow.proto.approval.VoteInvite.InviteOrBuilder getVoteInviteOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code secretflow.approval.Result}
   */
  public static final class Result extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:secretflow.approval.Result)
      ResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Result.newBuilder() to construct.
    private Result(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Result() {
      voteInvite_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Result();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.secretflow.proto.approval.VoteResult.internal_static_secretflow_approval_Result_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.secretflow.proto.approval.VoteResult.internal_static_secretflow_approval_Result_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.secretflow.proto.approval.VoteResult.Result.class, org.secretflow.proto.approval.VoteResult.Result.Builder.class);
    }

    public static final int VOTE_REQUEST_FIELD_NUMBER = 1;
    private org.secretflow.proto.approval.VoteRequest.Request voteRequest_;
    /**
     * <code>.secretflow.approval.Request vote_request = 1;</code>
     * @return Whether the voteRequest field is set.
     */
    @java.lang.Override
    public boolean hasVoteRequest() {
      return voteRequest_ != null;
    }
    /**
     * <code>.secretflow.approval.Request vote_request = 1;</code>
     * @return The voteRequest.
     */
    @java.lang.Override
    public org.secretflow.proto.approval.VoteRequest.Request getVoteRequest() {
      return voteRequest_ == null ? org.secretflow.proto.approval.VoteRequest.Request.getDefaultInstance() : voteRequest_;
    }
    /**
     * <code>.secretflow.approval.Request vote_request = 1;</code>
     */
    @java.lang.Override
    public org.secretflow.proto.approval.VoteRequest.RequestOrBuilder getVoteRequestOrBuilder() {
      return voteRequest_ == null ? org.secretflow.proto.approval.VoteRequest.Request.getDefaultInstance() : voteRequest_;
    }

    public static final int VOTE_INVITE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<org.secretflow.proto.approval.VoteInvite.Invite> voteInvite_;
    /**
     * <code>repeated .secretflow.approval.Invite vote_invite = 2;</code>
     */
    @java.lang.Override
    public java.util.List<org.secretflow.proto.approval.VoteInvite.Invite> getVoteInviteList() {
      return voteInvite_;
    }
    /**
     * <code>repeated .secretflow.approval.Invite vote_invite = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.secretflow.proto.approval.VoteInvite.InviteOrBuilder> 
        getVoteInviteOrBuilderList() {
      return voteInvite_;
    }
    /**
     * <code>repeated .secretflow.approval.Invite vote_invite = 2;</code>
     */
    @java.lang.Override
    public int getVoteInviteCount() {
      return voteInvite_.size();
    }
    /**
     * <code>repeated .secretflow.approval.Invite vote_invite = 2;</code>
     */
    @java.lang.Override
    public org.secretflow.proto.approval.VoteInvite.Invite getVoteInvite(int index) {
      return voteInvite_.get(index);
    }
    /**
     * <code>repeated .secretflow.approval.Invite vote_invite = 2;</code>
     */
    @java.lang.Override
    public org.secretflow.proto.approval.VoteInvite.InviteOrBuilder getVoteInviteOrBuilder(
        int index) {
      return voteInvite_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (voteRequest_ != null) {
        output.writeMessage(1, getVoteRequest());
      }
      for (int i = 0; i < voteInvite_.size(); i++) {
        output.writeMessage(2, voteInvite_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (voteRequest_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getVoteRequest());
      }
      for (int i = 0; i < voteInvite_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, voteInvite_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.secretflow.proto.approval.VoteResult.Result)) {
        return super.equals(obj);
      }
      org.secretflow.proto.approval.VoteResult.Result other = (org.secretflow.proto.approval.VoteResult.Result) obj;

      if (hasVoteRequest() != other.hasVoteRequest()) return false;
      if (hasVoteRequest()) {
        if (!getVoteRequest()
            .equals(other.getVoteRequest())) return false;
      }
      if (!getVoteInviteList()
          .equals(other.getVoteInviteList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasVoteRequest()) {
        hash = (37 * hash) + VOTE_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getVoteRequest().hashCode();
      }
      if (getVoteInviteCount() > 0) {
        hash = (37 * hash) + VOTE_INVITE_FIELD_NUMBER;
        hash = (53 * hash) + getVoteInviteList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.secretflow.proto.approval.VoteResult.Result parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.secretflow.proto.approval.VoteResult.Result parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.secretflow.proto.approval.VoteResult.Result parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.secretflow.proto.approval.VoteResult.Result parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.secretflow.proto.approval.VoteResult.Result parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.secretflow.proto.approval.VoteResult.Result parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.secretflow.proto.approval.VoteResult.Result parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.secretflow.proto.approval.VoteResult.Result parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.secretflow.proto.approval.VoteResult.Result parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.secretflow.proto.approval.VoteResult.Result parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.secretflow.proto.approval.VoteResult.Result parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.secretflow.proto.approval.VoteResult.Result parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.secretflow.proto.approval.VoteResult.Result prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code secretflow.approval.Result}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:secretflow.approval.Result)
        org.secretflow.proto.approval.VoteResult.ResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.secretflow.proto.approval.VoteResult.internal_static_secretflow_approval_Result_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.secretflow.proto.approval.VoteResult.internal_static_secretflow_approval_Result_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.secretflow.proto.approval.VoteResult.Result.class, org.secretflow.proto.approval.VoteResult.Result.Builder.class);
      }

      // Construct using org.secretflow.proto.approval.VoteResult.Result.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        voteRequest_ = null;
        if (voteRequestBuilder_ != null) {
          voteRequestBuilder_.dispose();
          voteRequestBuilder_ = null;
        }
        if (voteInviteBuilder_ == null) {
          voteInvite_ = java.util.Collections.emptyList();
        } else {
          voteInvite_ = null;
          voteInviteBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.secretflow.proto.approval.VoteResult.internal_static_secretflow_approval_Result_descriptor;
      }

      @java.lang.Override
      public org.secretflow.proto.approval.VoteResult.Result getDefaultInstanceForType() {
        return org.secretflow.proto.approval.VoteResult.Result.getDefaultInstance();
      }

      @java.lang.Override
      public org.secretflow.proto.approval.VoteResult.Result build() {
        org.secretflow.proto.approval.VoteResult.Result result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.secretflow.proto.approval.VoteResult.Result buildPartial() {
        org.secretflow.proto.approval.VoteResult.Result result = new org.secretflow.proto.approval.VoteResult.Result(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(org.secretflow.proto.approval.VoteResult.Result result) {
        if (voteInviteBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            voteInvite_ = java.util.Collections.unmodifiableList(voteInvite_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.voteInvite_ = voteInvite_;
        } else {
          result.voteInvite_ = voteInviteBuilder_.build();
        }
      }

      private void buildPartial0(org.secretflow.proto.approval.VoteResult.Result result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.voteRequest_ = voteRequestBuilder_ == null
              ? voteRequest_
              : voteRequestBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.secretflow.proto.approval.VoteResult.Result) {
          return mergeFrom((org.secretflow.proto.approval.VoteResult.Result)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.secretflow.proto.approval.VoteResult.Result other) {
        if (other == org.secretflow.proto.approval.VoteResult.Result.getDefaultInstance()) return this;
        if (other.hasVoteRequest()) {
          mergeVoteRequest(other.getVoteRequest());
        }
        if (voteInviteBuilder_ == null) {
          if (!other.voteInvite_.isEmpty()) {
            if (voteInvite_.isEmpty()) {
              voteInvite_ = other.voteInvite_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureVoteInviteIsMutable();
              voteInvite_.addAll(other.voteInvite_);
            }
            onChanged();
          }
        } else {
          if (!other.voteInvite_.isEmpty()) {
            if (voteInviteBuilder_.isEmpty()) {
              voteInviteBuilder_.dispose();
              voteInviteBuilder_ = null;
              voteInvite_ = other.voteInvite_;
              bitField0_ = (bitField0_ & ~0x00000002);
              voteInviteBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getVoteInviteFieldBuilder() : null;
            } else {
              voteInviteBuilder_.addAllMessages(other.voteInvite_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getVoteRequestFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                org.secretflow.proto.approval.VoteInvite.Invite m =
                    input.readMessage(
                        org.secretflow.proto.approval.VoteInvite.Invite.parser(),
                        extensionRegistry);
                if (voteInviteBuilder_ == null) {
                  ensureVoteInviteIsMutable();
                  voteInvite_.add(m);
                } else {
                  voteInviteBuilder_.addMessage(m);
                }
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private org.secretflow.proto.approval.VoteRequest.Request voteRequest_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.secretflow.proto.approval.VoteRequest.Request, org.secretflow.proto.approval.VoteRequest.Request.Builder, org.secretflow.proto.approval.VoteRequest.RequestOrBuilder> voteRequestBuilder_;
      /**
       * <code>.secretflow.approval.Request vote_request = 1;</code>
       * @return Whether the voteRequest field is set.
       */
      public boolean hasVoteRequest() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.secretflow.approval.Request vote_request = 1;</code>
       * @return The voteRequest.
       */
      public org.secretflow.proto.approval.VoteRequest.Request getVoteRequest() {
        if (voteRequestBuilder_ == null) {
          return voteRequest_ == null ? org.secretflow.proto.approval.VoteRequest.Request.getDefaultInstance() : voteRequest_;
        } else {
          return voteRequestBuilder_.getMessage();
        }
      }
      /**
       * <code>.secretflow.approval.Request vote_request = 1;</code>
       */
      public Builder setVoteRequest(org.secretflow.proto.approval.VoteRequest.Request value) {
        if (voteRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          voteRequest_ = value;
        } else {
          voteRequestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.approval.Request vote_request = 1;</code>
       */
      public Builder setVoteRequest(
          org.secretflow.proto.approval.VoteRequest.Request.Builder builderForValue) {
        if (voteRequestBuilder_ == null) {
          voteRequest_ = builderForValue.build();
        } else {
          voteRequestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.approval.Request vote_request = 1;</code>
       */
      public Builder mergeVoteRequest(org.secretflow.proto.approval.VoteRequest.Request value) {
        if (voteRequestBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            voteRequest_ != null &&
            voteRequest_ != org.secretflow.proto.approval.VoteRequest.Request.getDefaultInstance()) {
            getVoteRequestBuilder().mergeFrom(value);
          } else {
            voteRequest_ = value;
          }
        } else {
          voteRequestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.approval.Request vote_request = 1;</code>
       */
      public Builder clearVoteRequest() {
        bitField0_ = (bitField0_ & ~0x00000001);
        voteRequest_ = null;
        if (voteRequestBuilder_ != null) {
          voteRequestBuilder_.dispose();
          voteRequestBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.approval.Request vote_request = 1;</code>
       */
      public org.secretflow.proto.approval.VoteRequest.Request.Builder getVoteRequestBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getVoteRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>.secretflow.approval.Request vote_request = 1;</code>
       */
      public org.secretflow.proto.approval.VoteRequest.RequestOrBuilder getVoteRequestOrBuilder() {
        if (voteRequestBuilder_ != null) {
          return voteRequestBuilder_.getMessageOrBuilder();
        } else {
          return voteRequest_ == null ?
              org.secretflow.proto.approval.VoteRequest.Request.getDefaultInstance() : voteRequest_;
        }
      }
      /**
       * <code>.secretflow.approval.Request vote_request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.secretflow.proto.approval.VoteRequest.Request, org.secretflow.proto.approval.VoteRequest.Request.Builder, org.secretflow.proto.approval.VoteRequest.RequestOrBuilder> 
          getVoteRequestFieldBuilder() {
        if (voteRequestBuilder_ == null) {
          voteRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.secretflow.proto.approval.VoteRequest.Request, org.secretflow.proto.approval.VoteRequest.Request.Builder, org.secretflow.proto.approval.VoteRequest.RequestOrBuilder>(
                  getVoteRequest(),
                  getParentForChildren(),
                  isClean());
          voteRequest_ = null;
        }
        return voteRequestBuilder_;
      }

      private java.util.List<org.secretflow.proto.approval.VoteInvite.Invite> voteInvite_ =
        java.util.Collections.emptyList();
      private void ensureVoteInviteIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          voteInvite_ = new java.util.ArrayList<org.secretflow.proto.approval.VoteInvite.Invite>(voteInvite_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.secretflow.proto.approval.VoteInvite.Invite, org.secretflow.proto.approval.VoteInvite.Invite.Builder, org.secretflow.proto.approval.VoteInvite.InviteOrBuilder> voteInviteBuilder_;

      /**
       * <code>repeated .secretflow.approval.Invite vote_invite = 2;</code>
       */
      public java.util.List<org.secretflow.proto.approval.VoteInvite.Invite> getVoteInviteList() {
        if (voteInviteBuilder_ == null) {
          return java.util.Collections.unmodifiableList(voteInvite_);
        } else {
          return voteInviteBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .secretflow.approval.Invite vote_invite = 2;</code>
       */
      public int getVoteInviteCount() {
        if (voteInviteBuilder_ == null) {
          return voteInvite_.size();
        } else {
          return voteInviteBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .secretflow.approval.Invite vote_invite = 2;</code>
       */
      public org.secretflow.proto.approval.VoteInvite.Invite getVoteInvite(int index) {
        if (voteInviteBuilder_ == null) {
          return voteInvite_.get(index);
        } else {
          return voteInviteBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .secretflow.approval.Invite vote_invite = 2;</code>
       */
      public Builder setVoteInvite(
          int index, org.secretflow.proto.approval.VoteInvite.Invite value) {
        if (voteInviteBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVoteInviteIsMutable();
          voteInvite_.set(index, value);
          onChanged();
        } else {
          voteInviteBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .secretflow.approval.Invite vote_invite = 2;</code>
       */
      public Builder setVoteInvite(
          int index, org.secretflow.proto.approval.VoteInvite.Invite.Builder builderForValue) {
        if (voteInviteBuilder_ == null) {
          ensureVoteInviteIsMutable();
          voteInvite_.set(index, builderForValue.build());
          onChanged();
        } else {
          voteInviteBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .secretflow.approval.Invite vote_invite = 2;</code>
       */
      public Builder addVoteInvite(org.secretflow.proto.approval.VoteInvite.Invite value) {
        if (voteInviteBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVoteInviteIsMutable();
          voteInvite_.add(value);
          onChanged();
        } else {
          voteInviteBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .secretflow.approval.Invite vote_invite = 2;</code>
       */
      public Builder addVoteInvite(
          int index, org.secretflow.proto.approval.VoteInvite.Invite value) {
        if (voteInviteBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVoteInviteIsMutable();
          voteInvite_.add(index, value);
          onChanged();
        } else {
          voteInviteBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .secretflow.approval.Invite vote_invite = 2;</code>
       */
      public Builder addVoteInvite(
          org.secretflow.proto.approval.VoteInvite.Invite.Builder builderForValue) {
        if (voteInviteBuilder_ == null) {
          ensureVoteInviteIsMutable();
          voteInvite_.add(builderForValue.build());
          onChanged();
        } else {
          voteInviteBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .secretflow.approval.Invite vote_invite = 2;</code>
       */
      public Builder addVoteInvite(
          int index, org.secretflow.proto.approval.VoteInvite.Invite.Builder builderForValue) {
        if (voteInviteBuilder_ == null) {
          ensureVoteInviteIsMutable();
          voteInvite_.add(index, builderForValue.build());
          onChanged();
        } else {
          voteInviteBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .secretflow.approval.Invite vote_invite = 2;</code>
       */
      public Builder addAllVoteInvite(
          java.lang.Iterable<? extends org.secretflow.proto.approval.VoteInvite.Invite> values) {
        if (voteInviteBuilder_ == null) {
          ensureVoteInviteIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, voteInvite_);
          onChanged();
        } else {
          voteInviteBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .secretflow.approval.Invite vote_invite = 2;</code>
       */
      public Builder clearVoteInvite() {
        if (voteInviteBuilder_ == null) {
          voteInvite_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          voteInviteBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .secretflow.approval.Invite vote_invite = 2;</code>
       */
      public Builder removeVoteInvite(int index) {
        if (voteInviteBuilder_ == null) {
          ensureVoteInviteIsMutable();
          voteInvite_.remove(index);
          onChanged();
        } else {
          voteInviteBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .secretflow.approval.Invite vote_invite = 2;</code>
       */
      public org.secretflow.proto.approval.VoteInvite.Invite.Builder getVoteInviteBuilder(
          int index) {
        return getVoteInviteFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .secretflow.approval.Invite vote_invite = 2;</code>
       */
      public org.secretflow.proto.approval.VoteInvite.InviteOrBuilder getVoteInviteOrBuilder(
          int index) {
        if (voteInviteBuilder_ == null) {
          return voteInvite_.get(index);  } else {
          return voteInviteBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .secretflow.approval.Invite vote_invite = 2;</code>
       */
      public java.util.List<? extends org.secretflow.proto.approval.VoteInvite.InviteOrBuilder> 
           getVoteInviteOrBuilderList() {
        if (voteInviteBuilder_ != null) {
          return voteInviteBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(voteInvite_);
        }
      }
      /**
       * <code>repeated .secretflow.approval.Invite vote_invite = 2;</code>
       */
      public org.secretflow.proto.approval.VoteInvite.Invite.Builder addVoteInviteBuilder() {
        return getVoteInviteFieldBuilder().addBuilder(
            org.secretflow.proto.approval.VoteInvite.Invite.getDefaultInstance());
      }
      /**
       * <code>repeated .secretflow.approval.Invite vote_invite = 2;</code>
       */
      public org.secretflow.proto.approval.VoteInvite.Invite.Builder addVoteInviteBuilder(
          int index) {
        return getVoteInviteFieldBuilder().addBuilder(
            index, org.secretflow.proto.approval.VoteInvite.Invite.getDefaultInstance());
      }
      /**
       * <code>repeated .secretflow.approval.Invite vote_invite = 2;</code>
       */
      public java.util.List<org.secretflow.proto.approval.VoteInvite.Invite.Builder> 
           getVoteInviteBuilderList() {
        return getVoteInviteFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.secretflow.proto.approval.VoteInvite.Invite, org.secretflow.proto.approval.VoteInvite.Invite.Builder, org.secretflow.proto.approval.VoteInvite.InviteOrBuilder> 
          getVoteInviteFieldBuilder() {
        if (voteInviteBuilder_ == null) {
          voteInviteBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.secretflow.proto.approval.VoteInvite.Invite, org.secretflow.proto.approval.VoteInvite.Invite.Builder, org.secretflow.proto.approval.VoteInvite.InviteOrBuilder>(
                  voteInvite_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          voteInvite_ = null;
        }
        return voteInviteBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:secretflow.approval.Result)
    }

    // @@protoc_insertion_point(class_scope:secretflow.approval.Result)
    private static final org.secretflow.proto.approval.VoteResult.Result DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.secretflow.proto.approval.VoteResult.Result();
    }

    public static org.secretflow.proto.approval.VoteResult.Result getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Result>
        PARSER = new com.google.protobuf.AbstractParser<Result>() {
      @java.lang.Override
      public Result parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Result> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Result> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.secretflow.proto.approval.VoteResult.Result getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_secretflow_approval_Result_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_secretflow_approval_Result_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,secretflow/protos/approval/vote_result" +
      ".proto\022\023secretflow.approval\032-secretflow/" +
      "protos/approval/vote_request.proto\032,secr" +
      "etflow/protos/approval/vote_invite.proto" +
      "\"n\n\006Result\0222\n\014vote_request\030\001 \001(\0132\034.secre" +
      "tflow.approval.Request\0220\n\013vote_invite\030\002 " +
      "\003(\0132\033.secretflow.approval.InviteB\037\n\035org." +
      "secretflow.proto.approvalb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.secretflow.proto.approval.VoteRequest.getDescriptor(),
          org.secretflow.proto.approval.VoteInvite.getDescriptor(),
        });
    internal_static_secretflow_approval_Result_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_secretflow_approval_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_secretflow_approval_Result_descriptor,
        new java.lang.String[] { "VoteRequest", "VoteInvite", });
    org.secretflow.proto.approval.VoteRequest.getDescriptor();
    org.secretflow.proto.approval.VoteInvite.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
