// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: secretflow/protos/approval/vote_invite.proto

package org.secretflow.proto.approval;

public final class VoteInvite {
  private VoteInvite() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code secretflow.approval.Action}
   */
  public enum Action
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>APPROVE = 0;</code>
     */
    APPROVE(0),
    /**
     * <code>REJECT = 1;</code>
     */
    REJECT(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>APPROVE = 0;</code>
     */
    public static final int APPROVE_VALUE = 0;
    /**
     * <code>REJECT = 1;</code>
     */
    public static final int REJECT_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Action valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Action forNumber(int value) {
      switch (value) {
        case 0: return APPROVE;
        case 1: return REJECT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Action>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Action> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Action>() {
            public Action findValueByNumber(int number) {
              return Action.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.secretflow.proto.approval.VoteInvite.getDescriptor().getEnumTypes().get(0);
    }

    private static final Action[] VALUES = values();

    public static Action valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Action(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:secretflow.approval.Action)
  }

  public interface InviteOrBuilder extends
      // @@protoc_insertion_point(interface_extends:secretflow.approval.Invite)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *unique vote id
     * </pre>
     *
     * <code>string vote_request_id = 1;</code>
     * @return The voteRequestId.
     */
    java.lang.String getVoteRequestId();
    /**
     * <pre>
     *unique vote id
     * </pre>
     *
     * <code>string vote_request_id = 1;</code>
     * @return The bytes for voteRequestId.
     */
    com.google.protobuf.ByteString
        getVoteRequestIdBytes();

    /**
     * <pre>
     *participant
     * </pre>
     *
     * <code>string voter = 2;</code>
     * @return The voter.
     */
    java.lang.String getVoter();
    /**
     * <pre>
     *participant
     * </pre>
     *
     * <code>string voter = 2;</code>
     * @return The bytes for voter.
     */
    com.google.protobuf.ByteString
        getVoterBytes();

    /**
     * <code>.secretflow.approval.Action action = 3;</code>
     * @return The enum numeric value on the wire for action.
     */
    int getActionValue();
    /**
     * <code>.secretflow.approval.Action action = 3;</code>
     * @return The action.
     */
    org.secretflow.proto.approval.VoteInvite.Action getAction();

    /**
     * <pre>
     * "cert_chain" :["cacertxxx","tempcertxxx"]
     * </pre>
     *
     * <code>repeated string cert_chain = 4;</code>
     * @return A list containing the certChain.
     */
    java.util.List<java.lang.String>
        getCertChainList();
    /**
     * <pre>
     * "cert_chain" :["cacertxxx","tempcertxxx"]
     * </pre>
     *
     * <code>repeated string cert_chain = 4;</code>
     * @return The count of certChain.
     */
    int getCertChainCount();
    /**
     * <pre>
     * "cert_chain" :["cacertxxx","tempcertxxx"]
     * </pre>
     *
     * <code>repeated string cert_chain = 4;</code>
     * @param index The index of the element to return.
     * @return The certChain at the given index.
     */
    java.lang.String getCertChain(int index);
    /**
     * <pre>
     * "cert_chain" :["cacertxxx","tempcertxxx"]
     * </pre>
     *
     * <code>repeated string cert_chain = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the certChain at the given index.
     */
    com.google.protobuf.ByteString
        getCertChainBytes(int index);

    /**
     * <pre>
     **
     *{
     *"vote_request_id": "xxx",
     *"voter": "xxx",
     *"action": "xxx",
     *"resource_uri":"xxxx"
     *}
     * </pre>
     *
     * <code>string body = 5;</code>
     * @return The body.
     */
    java.lang.String getBody();
    /**
     * <pre>
     **
     *{
     *"vote_request_id": "xxx",
     *"voter": "xxx",
     *"action": "xxx",
     *"resource_uri":"xxxx"
     *}
     * </pre>
     *
     * <code>string body = 5;</code>
     * @return The bytes for body.
     */
    com.google.protobuf.ByteString
        getBodyBytes();

    /**
     * <pre>
     **
     *eg:
     *body = "this is base64 body"
     *vote_request_signature = "this is vote_request_signature in vote_request.proto"
     *voter_signature = sign(body + vote_request_signature);
     * </pre>
     *
     * <code>string voter_signature = 6;</code>
     * @return The voterSignature.
     */
    java.lang.String getVoterSignature();
    /**
     * <pre>
     **
     *eg:
     *body = "this is base64 body"
     *vote_request_signature = "this is vote_request_signature in vote_request.proto"
     *voter_signature = sign(body + vote_request_signature);
     * </pre>
     *
     * <code>string voter_signature = 6;</code>
     * @return The bytes for voterSignature.
     */
    com.google.protobuf.ByteString
        getVoterSignatureBytes();
  }
  /**
   * Protobuf type {@code secretflow.approval.Invite}
   */
  public static final class Invite extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:secretflow.approval.Invite)
      InviteOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Invite.newBuilder() to construct.
    private Invite(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Invite() {
      voteRequestId_ = "";
      voter_ = "";
      action_ = 0;
      certChain_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      body_ = "";
      voterSignature_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Invite();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.secretflow.proto.approval.VoteInvite.internal_static_secretflow_approval_Invite_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.secretflow.proto.approval.VoteInvite.internal_static_secretflow_approval_Invite_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.secretflow.proto.approval.VoteInvite.Invite.class, org.secretflow.proto.approval.VoteInvite.Invite.Builder.class);
    }

    public static final int VOTE_REQUEST_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object voteRequestId_ = "";
    /**
     * <pre>
     *unique vote id
     * </pre>
     *
     * <code>string vote_request_id = 1;</code>
     * @return The voteRequestId.
     */
    @java.lang.Override
    public java.lang.String getVoteRequestId() {
      java.lang.Object ref = voteRequestId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        voteRequestId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *unique vote id
     * </pre>
     *
     * <code>string vote_request_id = 1;</code>
     * @return The bytes for voteRequestId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVoteRequestIdBytes() {
      java.lang.Object ref = voteRequestId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        voteRequestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VOTER_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object voter_ = "";
    /**
     * <pre>
     *participant
     * </pre>
     *
     * <code>string voter = 2;</code>
     * @return The voter.
     */
    @java.lang.Override
    public java.lang.String getVoter() {
      java.lang.Object ref = voter_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        voter_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *participant
     * </pre>
     *
     * <code>string voter = 2;</code>
     * @return The bytes for voter.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVoterBytes() {
      java.lang.Object ref = voter_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        voter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACTION_FIELD_NUMBER = 3;
    private int action_ = 0;
    /**
     * <code>.secretflow.approval.Action action = 3;</code>
     * @return The enum numeric value on the wire for action.
     */
    @java.lang.Override public int getActionValue() {
      return action_;
    }
    /**
     * <code>.secretflow.approval.Action action = 3;</code>
     * @return The action.
     */
    @java.lang.Override public org.secretflow.proto.approval.VoteInvite.Action getAction() {
      org.secretflow.proto.approval.VoteInvite.Action result = org.secretflow.proto.approval.VoteInvite.Action.forNumber(action_);
      return result == null ? org.secretflow.proto.approval.VoteInvite.Action.UNRECOGNIZED : result;
    }

    public static final int CERT_CHAIN_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList certChain_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <pre>
     * "cert_chain" :["cacertxxx","tempcertxxx"]
     * </pre>
     *
     * <code>repeated string cert_chain = 4;</code>
     * @return A list containing the certChain.
     */
    public com.google.protobuf.ProtocolStringList
        getCertChainList() {
      return certChain_;
    }
    /**
     * <pre>
     * "cert_chain" :["cacertxxx","tempcertxxx"]
     * </pre>
     *
     * <code>repeated string cert_chain = 4;</code>
     * @return The count of certChain.
     */
    public int getCertChainCount() {
      return certChain_.size();
    }
    /**
     * <pre>
     * "cert_chain" :["cacertxxx","tempcertxxx"]
     * </pre>
     *
     * <code>repeated string cert_chain = 4;</code>
     * @param index The index of the element to return.
     * @return The certChain at the given index.
     */
    public java.lang.String getCertChain(int index) {
      return certChain_.get(index);
    }
    /**
     * <pre>
     * "cert_chain" :["cacertxxx","tempcertxxx"]
     * </pre>
     *
     * <code>repeated string cert_chain = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the certChain at the given index.
     */
    public com.google.protobuf.ByteString
        getCertChainBytes(int index) {
      return certChain_.getByteString(index);
    }

    public static final int BODY_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object body_ = "";
    /**
     * <pre>
     **
     *{
     *"vote_request_id": "xxx",
     *"voter": "xxx",
     *"action": "xxx",
     *"resource_uri":"xxxx"
     *}
     * </pre>
     *
     * <code>string body = 5;</code>
     * @return The body.
     */
    @java.lang.Override
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        body_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     *{
     *"vote_request_id": "xxx",
     *"voter": "xxx",
     *"action": "xxx",
     *"resource_uri":"xxxx"
     *}
     * </pre>
     *
     * <code>string body = 5;</code>
     * @return The bytes for body.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VOTER_SIGNATURE_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object voterSignature_ = "";
    /**
     * <pre>
     **
     *eg:
     *body = "this is base64 body"
     *vote_request_signature = "this is vote_request_signature in vote_request.proto"
     *voter_signature = sign(body + vote_request_signature);
     * </pre>
     *
     * <code>string voter_signature = 6;</code>
     * @return The voterSignature.
     */
    @java.lang.Override
    public java.lang.String getVoterSignature() {
      java.lang.Object ref = voterSignature_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        voterSignature_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     *eg:
     *body = "this is base64 body"
     *vote_request_signature = "this is vote_request_signature in vote_request.proto"
     *voter_signature = sign(body + vote_request_signature);
     * </pre>
     *
     * <code>string voter_signature = 6;</code>
     * @return The bytes for voterSignature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVoterSignatureBytes() {
      java.lang.Object ref = voterSignature_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        voterSignature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(voteRequestId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, voteRequestId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(voter_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, voter_);
      }
      if (action_ != org.secretflow.proto.approval.VoteInvite.Action.APPROVE.getNumber()) {
        output.writeEnum(3, action_);
      }
      for (int i = 0; i < certChain_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, certChain_.getRaw(i));
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(body_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, body_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(voterSignature_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, voterSignature_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(voteRequestId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, voteRequestId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(voter_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, voter_);
      }
      if (action_ != org.secretflow.proto.approval.VoteInvite.Action.APPROVE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, action_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < certChain_.size(); i++) {
          dataSize += computeStringSizeNoTag(certChain_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getCertChainList().size();
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(body_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, body_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(voterSignature_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, voterSignature_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.secretflow.proto.approval.VoteInvite.Invite)) {
        return super.equals(obj);
      }
      org.secretflow.proto.approval.VoteInvite.Invite other = (org.secretflow.proto.approval.VoteInvite.Invite) obj;

      if (!getVoteRequestId()
          .equals(other.getVoteRequestId())) return false;
      if (!getVoter()
          .equals(other.getVoter())) return false;
      if (action_ != other.action_) return false;
      if (!getCertChainList()
          .equals(other.getCertChainList())) return false;
      if (!getBody()
          .equals(other.getBody())) return false;
      if (!getVoterSignature()
          .equals(other.getVoterSignature())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VOTE_REQUEST_ID_FIELD_NUMBER;
      hash = (53 * hash) + getVoteRequestId().hashCode();
      hash = (37 * hash) + VOTER_FIELD_NUMBER;
      hash = (53 * hash) + getVoter().hashCode();
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + action_;
      if (getCertChainCount() > 0) {
        hash = (37 * hash) + CERT_CHAIN_FIELD_NUMBER;
        hash = (53 * hash) + getCertChainList().hashCode();
      }
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (37 * hash) + VOTER_SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getVoterSignature().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.secretflow.proto.approval.VoteInvite.Invite parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.secretflow.proto.approval.VoteInvite.Invite parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.secretflow.proto.approval.VoteInvite.Invite parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.secretflow.proto.approval.VoteInvite.Invite parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.secretflow.proto.approval.VoteInvite.Invite parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.secretflow.proto.approval.VoteInvite.Invite parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.secretflow.proto.approval.VoteInvite.Invite parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.secretflow.proto.approval.VoteInvite.Invite parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.secretflow.proto.approval.VoteInvite.Invite parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.secretflow.proto.approval.VoteInvite.Invite parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.secretflow.proto.approval.VoteInvite.Invite parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.secretflow.proto.approval.VoteInvite.Invite parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.secretflow.proto.approval.VoteInvite.Invite prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code secretflow.approval.Invite}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:secretflow.approval.Invite)
        org.secretflow.proto.approval.VoteInvite.InviteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.secretflow.proto.approval.VoteInvite.internal_static_secretflow_approval_Invite_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.secretflow.proto.approval.VoteInvite.internal_static_secretflow_approval_Invite_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.secretflow.proto.approval.VoteInvite.Invite.class, org.secretflow.proto.approval.VoteInvite.Invite.Builder.class);
      }

      // Construct using org.secretflow.proto.approval.VoteInvite.Invite.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        voteRequestId_ = "";
        voter_ = "";
        action_ = 0;
        certChain_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        body_ = "";
        voterSignature_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.secretflow.proto.approval.VoteInvite.internal_static_secretflow_approval_Invite_descriptor;
      }

      @java.lang.Override
      public org.secretflow.proto.approval.VoteInvite.Invite getDefaultInstanceForType() {
        return org.secretflow.proto.approval.VoteInvite.Invite.getDefaultInstance();
      }

      @java.lang.Override
      public org.secretflow.proto.approval.VoteInvite.Invite build() {
        org.secretflow.proto.approval.VoteInvite.Invite result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.secretflow.proto.approval.VoteInvite.Invite buildPartial() {
        org.secretflow.proto.approval.VoteInvite.Invite result = new org.secretflow.proto.approval.VoteInvite.Invite(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.secretflow.proto.approval.VoteInvite.Invite result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.voteRequestId_ = voteRequestId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.voter_ = voter_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.action_ = action_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          certChain_.makeImmutable();
          result.certChain_ = certChain_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.body_ = body_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.voterSignature_ = voterSignature_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.secretflow.proto.approval.VoteInvite.Invite) {
          return mergeFrom((org.secretflow.proto.approval.VoteInvite.Invite)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.secretflow.proto.approval.VoteInvite.Invite other) {
        if (other == org.secretflow.proto.approval.VoteInvite.Invite.getDefaultInstance()) return this;
        if (!other.getVoteRequestId().isEmpty()) {
          voteRequestId_ = other.voteRequestId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getVoter().isEmpty()) {
          voter_ = other.voter_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.action_ != 0) {
          setActionValue(other.getActionValue());
        }
        if (!other.certChain_.isEmpty()) {
          if (certChain_.isEmpty()) {
            certChain_ = other.certChain_;
            bitField0_ |= 0x00000008;
          } else {
            ensureCertChainIsMutable();
            certChain_.addAll(other.certChain_);
          }
          onChanged();
        }
        if (!other.getBody().isEmpty()) {
          body_ = other.body_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getVoterSignature().isEmpty()) {
          voterSignature_ = other.voterSignature_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                voteRequestId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                voter_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                action_ = input.readEnum();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureCertChainIsMutable();
                certChain_.add(s);
                break;
              } // case 34
              case 42: {
                body_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                voterSignature_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object voteRequestId_ = "";
      /**
       * <pre>
       *unique vote id
       * </pre>
       *
       * <code>string vote_request_id = 1;</code>
       * @return The voteRequestId.
       */
      public java.lang.String getVoteRequestId() {
        java.lang.Object ref = voteRequestId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          voteRequestId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *unique vote id
       * </pre>
       *
       * <code>string vote_request_id = 1;</code>
       * @return The bytes for voteRequestId.
       */
      public com.google.protobuf.ByteString
          getVoteRequestIdBytes() {
        java.lang.Object ref = voteRequestId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          voteRequestId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *unique vote id
       * </pre>
       *
       * <code>string vote_request_id = 1;</code>
       * @param value The voteRequestId to set.
       * @return This builder for chaining.
       */
      public Builder setVoteRequestId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        voteRequestId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *unique vote id
       * </pre>
       *
       * <code>string vote_request_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVoteRequestId() {
        voteRequestId_ = getDefaultInstance().getVoteRequestId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *unique vote id
       * </pre>
       *
       * <code>string vote_request_id = 1;</code>
       * @param value The bytes for voteRequestId to set.
       * @return This builder for chaining.
       */
      public Builder setVoteRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        voteRequestId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object voter_ = "";
      /**
       * <pre>
       *participant
       * </pre>
       *
       * <code>string voter = 2;</code>
       * @return The voter.
       */
      public java.lang.String getVoter() {
        java.lang.Object ref = voter_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          voter_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *participant
       * </pre>
       *
       * <code>string voter = 2;</code>
       * @return The bytes for voter.
       */
      public com.google.protobuf.ByteString
          getVoterBytes() {
        java.lang.Object ref = voter_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          voter_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *participant
       * </pre>
       *
       * <code>string voter = 2;</code>
       * @param value The voter to set.
       * @return This builder for chaining.
       */
      public Builder setVoter(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        voter_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *participant
       * </pre>
       *
       * <code>string voter = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVoter() {
        voter_ = getDefaultInstance().getVoter();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *participant
       * </pre>
       *
       * <code>string voter = 2;</code>
       * @param value The bytes for voter to set.
       * @return This builder for chaining.
       */
      public Builder setVoterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        voter_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int action_ = 0;
      /**
       * <code>.secretflow.approval.Action action = 3;</code>
       * @return The enum numeric value on the wire for action.
       */
      @java.lang.Override public int getActionValue() {
        return action_;
      }
      /**
       * <code>.secretflow.approval.Action action = 3;</code>
       * @param value The enum numeric value on the wire for action to set.
       * @return This builder for chaining.
       */
      public Builder setActionValue(int value) {
        action_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.approval.Action action = 3;</code>
       * @return The action.
       */
      @java.lang.Override
      public org.secretflow.proto.approval.VoteInvite.Action getAction() {
        org.secretflow.proto.approval.VoteInvite.Action result = org.secretflow.proto.approval.VoteInvite.Action.forNumber(action_);
        return result == null ? org.secretflow.proto.approval.VoteInvite.Action.UNRECOGNIZED : result;
      }
      /**
       * <code>.secretflow.approval.Action action = 3;</code>
       * @param value The action to set.
       * @return This builder for chaining.
       */
      public Builder setAction(org.secretflow.proto.approval.VoteInvite.Action value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        action_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.approval.Action action = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000004);
        action_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList certChain_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureCertChainIsMutable() {
        if (!certChain_.isModifiable()) {
          certChain_ = new com.google.protobuf.LazyStringArrayList(certChain_);
        }
        bitField0_ |= 0x00000008;
      }
      /**
       * <pre>
       * "cert_chain" :["cacertxxx","tempcertxxx"]
       * </pre>
       *
       * <code>repeated string cert_chain = 4;</code>
       * @return A list containing the certChain.
       */
      public com.google.protobuf.ProtocolStringList
          getCertChainList() {
        certChain_.makeImmutable();
        return certChain_;
      }
      /**
       * <pre>
       * "cert_chain" :["cacertxxx","tempcertxxx"]
       * </pre>
       *
       * <code>repeated string cert_chain = 4;</code>
       * @return The count of certChain.
       */
      public int getCertChainCount() {
        return certChain_.size();
      }
      /**
       * <pre>
       * "cert_chain" :["cacertxxx","tempcertxxx"]
       * </pre>
       *
       * <code>repeated string cert_chain = 4;</code>
       * @param index The index of the element to return.
       * @return The certChain at the given index.
       */
      public java.lang.String getCertChain(int index) {
        return certChain_.get(index);
      }
      /**
       * <pre>
       * "cert_chain" :["cacertxxx","tempcertxxx"]
       * </pre>
       *
       * <code>repeated string cert_chain = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the certChain at the given index.
       */
      public com.google.protobuf.ByteString
          getCertChainBytes(int index) {
        return certChain_.getByteString(index);
      }
      /**
       * <pre>
       * "cert_chain" :["cacertxxx","tempcertxxx"]
       * </pre>
       *
       * <code>repeated string cert_chain = 4;</code>
       * @param index The index to set the value at.
       * @param value The certChain to set.
       * @return This builder for chaining.
       */
      public Builder setCertChain(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureCertChainIsMutable();
        certChain_.set(index, value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * "cert_chain" :["cacertxxx","tempcertxxx"]
       * </pre>
       *
       * <code>repeated string cert_chain = 4;</code>
       * @param value The certChain to add.
       * @return This builder for chaining.
       */
      public Builder addCertChain(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureCertChainIsMutable();
        certChain_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * "cert_chain" :["cacertxxx","tempcertxxx"]
       * </pre>
       *
       * <code>repeated string cert_chain = 4;</code>
       * @param values The certChain to add.
       * @return This builder for chaining.
       */
      public Builder addAllCertChain(
          java.lang.Iterable<java.lang.String> values) {
        ensureCertChainIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, certChain_);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * "cert_chain" :["cacertxxx","tempcertxxx"]
       * </pre>
       *
       * <code>repeated string cert_chain = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCertChain() {
        certChain_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * "cert_chain" :["cacertxxx","tempcertxxx"]
       * </pre>
       *
       * <code>repeated string cert_chain = 4;</code>
       * @param value The bytes of the certChain to add.
       * @return This builder for chaining.
       */
      public Builder addCertChainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureCertChainIsMutable();
        certChain_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object body_ = "";
      /**
       * <pre>
       **
       *{
       *"vote_request_id": "xxx",
       *"voter": "xxx",
       *"action": "xxx",
       *"resource_uri":"xxxx"
       *}
       * </pre>
       *
       * <code>string body = 5;</code>
       * @return The body.
       */
      public java.lang.String getBody() {
        java.lang.Object ref = body_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          body_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       *{
       *"vote_request_id": "xxx",
       *"voter": "xxx",
       *"action": "xxx",
       *"resource_uri":"xxxx"
       *}
       * </pre>
       *
       * <code>string body = 5;</code>
       * @return The bytes for body.
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        java.lang.Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       *{
       *"vote_request_id": "xxx",
       *"voter": "xxx",
       *"action": "xxx",
       *"resource_uri":"xxxx"
       *}
       * </pre>
       *
       * <code>string body = 5;</code>
       * @param value The body to set.
       * @return This builder for chaining.
       */
      public Builder setBody(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        body_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       *{
       *"vote_request_id": "xxx",
       *"voter": "xxx",
       *"action": "xxx",
       *"resource_uri":"xxxx"
       *}
       * </pre>
       *
       * <code>string body = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearBody() {
        body_ = getDefaultInstance().getBody();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       *{
       *"vote_request_id": "xxx",
       *"voter": "xxx",
       *"action": "xxx",
       *"resource_uri":"xxxx"
       *}
       * </pre>
       *
       * <code>string body = 5;</code>
       * @param value The bytes for body to set.
       * @return This builder for chaining.
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        body_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object voterSignature_ = "";
      /**
       * <pre>
       **
       *eg:
       *body = "this is base64 body"
       *vote_request_signature = "this is vote_request_signature in vote_request.proto"
       *voter_signature = sign(body + vote_request_signature);
       * </pre>
       *
       * <code>string voter_signature = 6;</code>
       * @return The voterSignature.
       */
      public java.lang.String getVoterSignature() {
        java.lang.Object ref = voterSignature_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          voterSignature_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       *eg:
       *body = "this is base64 body"
       *vote_request_signature = "this is vote_request_signature in vote_request.proto"
       *voter_signature = sign(body + vote_request_signature);
       * </pre>
       *
       * <code>string voter_signature = 6;</code>
       * @return The bytes for voterSignature.
       */
      public com.google.protobuf.ByteString
          getVoterSignatureBytes() {
        java.lang.Object ref = voterSignature_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          voterSignature_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       *eg:
       *body = "this is base64 body"
       *vote_request_signature = "this is vote_request_signature in vote_request.proto"
       *voter_signature = sign(body + vote_request_signature);
       * </pre>
       *
       * <code>string voter_signature = 6;</code>
       * @param value The voterSignature to set.
       * @return This builder for chaining.
       */
      public Builder setVoterSignature(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        voterSignature_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       *eg:
       *body = "this is base64 body"
       *vote_request_signature = "this is vote_request_signature in vote_request.proto"
       *voter_signature = sign(body + vote_request_signature);
       * </pre>
       *
       * <code>string voter_signature = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearVoterSignature() {
        voterSignature_ = getDefaultInstance().getVoterSignature();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       *eg:
       *body = "this is base64 body"
       *vote_request_signature = "this is vote_request_signature in vote_request.proto"
       *voter_signature = sign(body + vote_request_signature);
       * </pre>
       *
       * <code>string voter_signature = 6;</code>
       * @param value The bytes for voterSignature to set.
       * @return This builder for chaining.
       */
      public Builder setVoterSignatureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        voterSignature_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:secretflow.approval.Invite)
    }

    // @@protoc_insertion_point(class_scope:secretflow.approval.Invite)
    private static final org.secretflow.proto.approval.VoteInvite.Invite DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.secretflow.proto.approval.VoteInvite.Invite();
    }

    public static org.secretflow.proto.approval.VoteInvite.Invite getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Invite>
        PARSER = new com.google.protobuf.AbstractParser<Invite>() {
      @java.lang.Override
      public Invite parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Invite> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Invite> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.secretflow.proto.approval.VoteInvite.Invite getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_secretflow_approval_Invite_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_secretflow_approval_Invite_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,secretflow/protos/approval/vote_invite" +
      ".proto\022\023secretflow.approval\"\230\001\n\006Invite\022\027" +
      "\n\017vote_request_id\030\001 \001(\t\022\r\n\005voter\030\002 \001(\t\022+" +
      "\n\006action\030\003 \001(\0162\033.secretflow.approval.Act" +
      "ion\022\022\n\ncert_chain\030\004 \003(\t\022\014\n\004body\030\005 \001(\t\022\027\n" +
      "\017voter_signature\030\006 \001(\t*!\n\006Action\022\013\n\007APPR" +
      "OVE\020\000\022\n\n\006REJECT\020\001B\037\n\035org.secretflow.prot" +
      "o.approvalb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_secretflow_approval_Invite_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_secretflow_approval_Invite_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_secretflow_approval_Invite_descriptor,
        new java.lang.String[] { "VoteRequestId", "Voter", "Action", "CertChain", "Body", "VoterSignature", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
