// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: secretflow/serving/kuscia/serving_config.proto

package secretflow.serving.kuscia;

public final class ServingConfig {
  private ServingConfig() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface KusciaServingConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:secretflow.serving.kuscia.KusciaServingConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Key: Party id
     * Value: Party config
     * </pre>
     *
     * <code>map&lt;string, .secretflow.serving.kuscia.KusciaServingConfig.PartyConfig&gt; party_configs = 1;</code>
     */
    int getPartyConfigsCount();
    /**
     * <pre>
     * Key: Party id
     * Value: Party config
     * </pre>
     *
     * <code>map&lt;string, .secretflow.serving.kuscia.KusciaServingConfig.PartyConfig&gt; party_configs = 1;</code>
     */
    boolean containsPartyConfigs(
        java.lang.String key);
    /**
     * Use {@link #getPartyConfigsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig>
    getPartyConfigs();
    /**
     * <pre>
     * Key: Party id
     * Value: Party config
     * </pre>
     *
     * <code>map&lt;string, .secretflow.serving.kuscia.KusciaServingConfig.PartyConfig&gt; party_configs = 1;</code>
     */
    java.util.Map<java.lang.String, secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig>
    getPartyConfigsMap();
    /**
     * <pre>
     * Key: Party id
     * Value: Party config
     * </pre>
     *
     * <code>map&lt;string, .secretflow.serving.kuscia.KusciaServingConfig.PartyConfig&gt; party_configs = 1;</code>
     */
    /* nullable */
secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig getPartyConfigsOrDefault(
        java.lang.String key,
        /* nullable */
secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig defaultValue);
    /**
     * <pre>
     * Key: Party id
     * Value: Party config
     * </pre>
     *
     * <code>map&lt;string, .secretflow.serving.kuscia.KusciaServingConfig.PartyConfig&gt; party_configs = 1;</code>
     */
    secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig getPartyConfigsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code secretflow.serving.kuscia.KusciaServingConfig}
   */
  public static final class KusciaServingConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:secretflow.serving.kuscia.KusciaServingConfig)
      KusciaServingConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use KusciaServingConfig.newBuilder() to construct.
    private KusciaServingConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KusciaServingConfig() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new KusciaServingConfig();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return secretflow.serving.kuscia.ServingConfig.internal_static_secretflow_serving_kuscia_KusciaServingConfig_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetPartyConfigs();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return secretflow.serving.kuscia.ServingConfig.internal_static_secretflow_serving_kuscia_KusciaServingConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.class, secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.Builder.class);
    }

    public interface PartyConfigOrBuilder extends
        // @@protoc_insertion_point(interface_extends:secretflow.serving.kuscia.KusciaServingConfig.PartyConfig)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>.secretflow.serving.ServerConfig server_config = 1;</code>
       * @return Whether the serverConfig field is set.
       */
      boolean hasServerConfig();
      /**
       * <code>.secretflow.serving.ServerConfig server_config = 1;</code>
       * @return The serverConfig.
       */
      secretflow.serving.ServerConfigOuterClass.ServerConfig getServerConfig();
      /**
       * <code>.secretflow.serving.ServerConfig server_config = 1;</code>
       */
      secretflow.serving.ServerConfigOuterClass.ServerConfigOrBuilder getServerConfigOrBuilder();

      /**
       * <code>.secretflow.serving.ModelConfig model_config = 2;</code>
       * @return Whether the modelConfig field is set.
       */
      boolean hasModelConfig();
      /**
       * <code>.secretflow.serving.ModelConfig model_config = 2;</code>
       * @return The modelConfig.
       */
      secretflow.serving.ModelConfigOuterClass.ModelConfig getModelConfig();
      /**
       * <code>.secretflow.serving.ModelConfig model_config = 2;</code>
       */
      secretflow.serving.ModelConfigOuterClass.ModelConfigOrBuilder getModelConfigOrBuilder();

      /**
       * <code>.secretflow.serving.FeatureSourceConfig feature_source_config = 3;</code>
       * @return Whether the featureSourceConfig field is set.
       */
      boolean hasFeatureSourceConfig();
      /**
       * <code>.secretflow.serving.FeatureSourceConfig feature_source_config = 3;</code>
       * @return The featureSourceConfig.
       */
      secretflow.serving.FeatureConfig.FeatureSourceConfig getFeatureSourceConfig();
      /**
       * <code>.secretflow.serving.FeatureSourceConfig feature_source_config = 3;</code>
       */
      secretflow.serving.FeatureConfig.FeatureSourceConfigOrBuilder getFeatureSourceConfigOrBuilder();

      /**
       * <code>.secretflow.serving.ChannelDesc channel_desc = 4;</code>
       * @return Whether the channelDesc field is set.
       */
      boolean hasChannelDesc();
      /**
       * <code>.secretflow.serving.ChannelDesc channel_desc = 4;</code>
       * @return The channelDesc.
       */
      secretflow.serving.ClusterConfigOuterClass.ChannelDesc getChannelDesc();
      /**
       * <code>.secretflow.serving.ChannelDesc channel_desc = 4;</code>
       */
      secretflow.serving.ClusterConfigOuterClass.ChannelDescOrBuilder getChannelDescOrBuilder();
    }
    /**
     * Protobuf type {@code secretflow.serving.kuscia.KusciaServingConfig.PartyConfig}
     */
    public static final class PartyConfig extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:secretflow.serving.kuscia.KusciaServingConfig.PartyConfig)
        PartyConfigOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use PartyConfig.newBuilder() to construct.
      private PartyConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private PartyConfig() {
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new PartyConfig();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return secretflow.serving.kuscia.ServingConfig.internal_static_secretflow_serving_kuscia_KusciaServingConfig_PartyConfig_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return secretflow.serving.kuscia.ServingConfig.internal_static_secretflow_serving_kuscia_KusciaServingConfig_PartyConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig.class, secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig.Builder.class);
      }

      public static final int SERVER_CONFIG_FIELD_NUMBER = 1;
      private secretflow.serving.ServerConfigOuterClass.ServerConfig serverConfig_;
      /**
       * <code>.secretflow.serving.ServerConfig server_config = 1;</code>
       * @return Whether the serverConfig field is set.
       */
      @java.lang.Override
      public boolean hasServerConfig() {
        return serverConfig_ != null;
      }
      /**
       * <code>.secretflow.serving.ServerConfig server_config = 1;</code>
       * @return The serverConfig.
       */
      @java.lang.Override
      public secretflow.serving.ServerConfigOuterClass.ServerConfig getServerConfig() {
        return serverConfig_ == null ? secretflow.serving.ServerConfigOuterClass.ServerConfig.getDefaultInstance() : serverConfig_;
      }
      /**
       * <code>.secretflow.serving.ServerConfig server_config = 1;</code>
       */
      @java.lang.Override
      public secretflow.serving.ServerConfigOuterClass.ServerConfigOrBuilder getServerConfigOrBuilder() {
        return serverConfig_ == null ? secretflow.serving.ServerConfigOuterClass.ServerConfig.getDefaultInstance() : serverConfig_;
      }

      public static final int MODEL_CONFIG_FIELD_NUMBER = 2;
      private secretflow.serving.ModelConfigOuterClass.ModelConfig modelConfig_;
      /**
       * <code>.secretflow.serving.ModelConfig model_config = 2;</code>
       * @return Whether the modelConfig field is set.
       */
      @java.lang.Override
      public boolean hasModelConfig() {
        return modelConfig_ != null;
      }
      /**
       * <code>.secretflow.serving.ModelConfig model_config = 2;</code>
       * @return The modelConfig.
       */
      @java.lang.Override
      public secretflow.serving.ModelConfigOuterClass.ModelConfig getModelConfig() {
        return modelConfig_ == null ? secretflow.serving.ModelConfigOuterClass.ModelConfig.getDefaultInstance() : modelConfig_;
      }
      /**
       * <code>.secretflow.serving.ModelConfig model_config = 2;</code>
       */
      @java.lang.Override
      public secretflow.serving.ModelConfigOuterClass.ModelConfigOrBuilder getModelConfigOrBuilder() {
        return modelConfig_ == null ? secretflow.serving.ModelConfigOuterClass.ModelConfig.getDefaultInstance() : modelConfig_;
      }

      public static final int FEATURE_SOURCE_CONFIG_FIELD_NUMBER = 3;
      private secretflow.serving.FeatureConfig.FeatureSourceConfig featureSourceConfig_;
      /**
       * <code>.secretflow.serving.FeatureSourceConfig feature_source_config = 3;</code>
       * @return Whether the featureSourceConfig field is set.
       */
      @java.lang.Override
      public boolean hasFeatureSourceConfig() {
        return featureSourceConfig_ != null;
      }
      /**
       * <code>.secretflow.serving.FeatureSourceConfig feature_source_config = 3;</code>
       * @return The featureSourceConfig.
       */
      @java.lang.Override
      public secretflow.serving.FeatureConfig.FeatureSourceConfig getFeatureSourceConfig() {
        return featureSourceConfig_ == null ? secretflow.serving.FeatureConfig.FeatureSourceConfig.getDefaultInstance() : featureSourceConfig_;
      }
      /**
       * <code>.secretflow.serving.FeatureSourceConfig feature_source_config = 3;</code>
       */
      @java.lang.Override
      public secretflow.serving.FeatureConfig.FeatureSourceConfigOrBuilder getFeatureSourceConfigOrBuilder() {
        return featureSourceConfig_ == null ? secretflow.serving.FeatureConfig.FeatureSourceConfig.getDefaultInstance() : featureSourceConfig_;
      }

      public static final int CHANNEL_DESC_FIELD_NUMBER = 4;
      private secretflow.serving.ClusterConfigOuterClass.ChannelDesc channelDesc_;
      /**
       * <code>.secretflow.serving.ChannelDesc channel_desc = 4;</code>
       * @return Whether the channelDesc field is set.
       */
      @java.lang.Override
      public boolean hasChannelDesc() {
        return channelDesc_ != null;
      }
      /**
       * <code>.secretflow.serving.ChannelDesc channel_desc = 4;</code>
       * @return The channelDesc.
       */
      @java.lang.Override
      public secretflow.serving.ClusterConfigOuterClass.ChannelDesc getChannelDesc() {
        return channelDesc_ == null ? secretflow.serving.ClusterConfigOuterClass.ChannelDesc.getDefaultInstance() : channelDesc_;
      }
      /**
       * <code>.secretflow.serving.ChannelDesc channel_desc = 4;</code>
       */
      @java.lang.Override
      public secretflow.serving.ClusterConfigOuterClass.ChannelDescOrBuilder getChannelDescOrBuilder() {
        return channelDesc_ == null ? secretflow.serving.ClusterConfigOuterClass.ChannelDesc.getDefaultInstance() : channelDesc_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (serverConfig_ != null) {
          output.writeMessage(1, getServerConfig());
        }
        if (modelConfig_ != null) {
          output.writeMessage(2, getModelConfig());
        }
        if (featureSourceConfig_ != null) {
          output.writeMessage(3, getFeatureSourceConfig());
        }
        if (channelDesc_ != null) {
          output.writeMessage(4, getChannelDesc());
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (serverConfig_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, getServerConfig());
        }
        if (modelConfig_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, getModelConfig());
        }
        if (featureSourceConfig_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, getFeatureSourceConfig());
        }
        if (channelDesc_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, getChannelDesc());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig)) {
          return super.equals(obj);
        }
        secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig other = (secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig) obj;

        if (hasServerConfig() != other.hasServerConfig()) return false;
        if (hasServerConfig()) {
          if (!getServerConfig()
              .equals(other.getServerConfig())) return false;
        }
        if (hasModelConfig() != other.hasModelConfig()) return false;
        if (hasModelConfig()) {
          if (!getModelConfig()
              .equals(other.getModelConfig())) return false;
        }
        if (hasFeatureSourceConfig() != other.hasFeatureSourceConfig()) return false;
        if (hasFeatureSourceConfig()) {
          if (!getFeatureSourceConfig()
              .equals(other.getFeatureSourceConfig())) return false;
        }
        if (hasChannelDesc() != other.hasChannelDesc()) return false;
        if (hasChannelDesc()) {
          if (!getChannelDesc()
              .equals(other.getChannelDesc())) return false;
        }
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasServerConfig()) {
          hash = (37 * hash) + SERVER_CONFIG_FIELD_NUMBER;
          hash = (53 * hash) + getServerConfig().hashCode();
        }
        if (hasModelConfig()) {
          hash = (37 * hash) + MODEL_CONFIG_FIELD_NUMBER;
          hash = (53 * hash) + getModelConfig().hashCode();
        }
        if (hasFeatureSourceConfig()) {
          hash = (37 * hash) + FEATURE_SOURCE_CONFIG_FIELD_NUMBER;
          hash = (53 * hash) + getFeatureSourceConfig().hashCode();
        }
        if (hasChannelDesc()) {
          hash = (37 * hash) + CHANNEL_DESC_FIELD_NUMBER;
          hash = (53 * hash) + getChannelDesc().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code secretflow.serving.kuscia.KusciaServingConfig.PartyConfig}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:secretflow.serving.kuscia.KusciaServingConfig.PartyConfig)
          secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfigOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return secretflow.serving.kuscia.ServingConfig.internal_static_secretflow_serving_kuscia_KusciaServingConfig_PartyConfig_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return secretflow.serving.kuscia.ServingConfig.internal_static_secretflow_serving_kuscia_KusciaServingConfig_PartyConfig_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig.class, secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig.Builder.class);
        }

        // Construct using secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          serverConfig_ = null;
          if (serverConfigBuilder_ != null) {
            serverConfigBuilder_.dispose();
            serverConfigBuilder_ = null;
          }
          modelConfig_ = null;
          if (modelConfigBuilder_ != null) {
            modelConfigBuilder_.dispose();
            modelConfigBuilder_ = null;
          }
          featureSourceConfig_ = null;
          if (featureSourceConfigBuilder_ != null) {
            featureSourceConfigBuilder_.dispose();
            featureSourceConfigBuilder_ = null;
          }
          channelDesc_ = null;
          if (channelDescBuilder_ != null) {
            channelDescBuilder_.dispose();
            channelDescBuilder_ = null;
          }
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return secretflow.serving.kuscia.ServingConfig.internal_static_secretflow_serving_kuscia_KusciaServingConfig_PartyConfig_descriptor;
        }

        @java.lang.Override
        public secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig getDefaultInstanceForType() {
          return secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig.getDefaultInstance();
        }

        @java.lang.Override
        public secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig build() {
          secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig buildPartial() {
          secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig result = new secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.serverConfig_ = serverConfigBuilder_ == null
                ? serverConfig_
                : serverConfigBuilder_.build();
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.modelConfig_ = modelConfigBuilder_ == null
                ? modelConfig_
                : modelConfigBuilder_.build();
          }
          if (((from_bitField0_ & 0x00000004) != 0)) {
            result.featureSourceConfig_ = featureSourceConfigBuilder_ == null
                ? featureSourceConfig_
                : featureSourceConfigBuilder_.build();
          }
          if (((from_bitField0_ & 0x00000008) != 0)) {
            result.channelDesc_ = channelDescBuilder_ == null
                ? channelDesc_
                : channelDescBuilder_.build();
          }
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig) {
            return mergeFrom((secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig other) {
          if (other == secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig.getDefaultInstance()) return this;
          if (other.hasServerConfig()) {
            mergeServerConfig(other.getServerConfig());
          }
          if (other.hasModelConfig()) {
            mergeModelConfig(other.getModelConfig());
          }
          if (other.hasFeatureSourceConfig()) {
            mergeFeatureSourceConfig(other.getFeatureSourceConfig());
          }
          if (other.hasChannelDesc()) {
            mergeChannelDesc(other.getChannelDesc());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  input.readMessage(
                      getServerConfigFieldBuilder().getBuilder(),
                      extensionRegistry);
                  bitField0_ |= 0x00000001;
                  break;
                } // case 10
                case 18: {
                  input.readMessage(
                      getModelConfigFieldBuilder().getBuilder(),
                      extensionRegistry);
                  bitField0_ |= 0x00000002;
                  break;
                } // case 18
                case 26: {
                  input.readMessage(
                      getFeatureSourceConfigFieldBuilder().getBuilder(),
                      extensionRegistry);
                  bitField0_ |= 0x00000004;
                  break;
                } // case 26
                case 34: {
                  input.readMessage(
                      getChannelDescFieldBuilder().getBuilder(),
                      extensionRegistry);
                  bitField0_ |= 0x00000008;
                  break;
                } // case 34
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private secretflow.serving.ServerConfigOuterClass.ServerConfig serverConfig_;
        private com.google.protobuf.SingleFieldBuilderV3<
            secretflow.serving.ServerConfigOuterClass.ServerConfig, secretflow.serving.ServerConfigOuterClass.ServerConfig.Builder, secretflow.serving.ServerConfigOuterClass.ServerConfigOrBuilder> serverConfigBuilder_;
        /**
         * <code>.secretflow.serving.ServerConfig server_config = 1;</code>
         * @return Whether the serverConfig field is set.
         */
        public boolean hasServerConfig() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>.secretflow.serving.ServerConfig server_config = 1;</code>
         * @return The serverConfig.
         */
        public secretflow.serving.ServerConfigOuterClass.ServerConfig getServerConfig() {
          if (serverConfigBuilder_ == null) {
            return serverConfig_ == null ? secretflow.serving.ServerConfigOuterClass.ServerConfig.getDefaultInstance() : serverConfig_;
          } else {
            return serverConfigBuilder_.getMessage();
          }
        }
        /**
         * <code>.secretflow.serving.ServerConfig server_config = 1;</code>
         */
        public Builder setServerConfig(secretflow.serving.ServerConfigOuterClass.ServerConfig value) {
          if (serverConfigBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            serverConfig_ = value;
          } else {
            serverConfigBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>.secretflow.serving.ServerConfig server_config = 1;</code>
         */
        public Builder setServerConfig(
            secretflow.serving.ServerConfigOuterClass.ServerConfig.Builder builderForValue) {
          if (serverConfigBuilder_ == null) {
            serverConfig_ = builderForValue.build();
          } else {
            serverConfigBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>.secretflow.serving.ServerConfig server_config = 1;</code>
         */
        public Builder mergeServerConfig(secretflow.serving.ServerConfigOuterClass.ServerConfig value) {
          if (serverConfigBuilder_ == null) {
            if (((bitField0_ & 0x00000001) != 0) &&
              serverConfig_ != null &&
              serverConfig_ != secretflow.serving.ServerConfigOuterClass.ServerConfig.getDefaultInstance()) {
              getServerConfigBuilder().mergeFrom(value);
            } else {
              serverConfig_ = value;
            }
          } else {
            serverConfigBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>.secretflow.serving.ServerConfig server_config = 1;</code>
         */
        public Builder clearServerConfig() {
          bitField0_ = (bitField0_ & ~0x00000001);
          serverConfig_ = null;
          if (serverConfigBuilder_ != null) {
            serverConfigBuilder_.dispose();
            serverConfigBuilder_ = null;
          }
          onChanged();
          return this;
        }
        /**
         * <code>.secretflow.serving.ServerConfig server_config = 1;</code>
         */
        public secretflow.serving.ServerConfigOuterClass.ServerConfig.Builder getServerConfigBuilder() {
          bitField0_ |= 0x00000001;
          onChanged();
          return getServerConfigFieldBuilder().getBuilder();
        }
        /**
         * <code>.secretflow.serving.ServerConfig server_config = 1;</code>
         */
        public secretflow.serving.ServerConfigOuterClass.ServerConfigOrBuilder getServerConfigOrBuilder() {
          if (serverConfigBuilder_ != null) {
            return serverConfigBuilder_.getMessageOrBuilder();
          } else {
            return serverConfig_ == null ?
                secretflow.serving.ServerConfigOuterClass.ServerConfig.getDefaultInstance() : serverConfig_;
          }
        }
        /**
         * <code>.secretflow.serving.ServerConfig server_config = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            secretflow.serving.ServerConfigOuterClass.ServerConfig, secretflow.serving.ServerConfigOuterClass.ServerConfig.Builder, secretflow.serving.ServerConfigOuterClass.ServerConfigOrBuilder> 
            getServerConfigFieldBuilder() {
          if (serverConfigBuilder_ == null) {
            serverConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                secretflow.serving.ServerConfigOuterClass.ServerConfig, secretflow.serving.ServerConfigOuterClass.ServerConfig.Builder, secretflow.serving.ServerConfigOuterClass.ServerConfigOrBuilder>(
                    getServerConfig(),
                    getParentForChildren(),
                    isClean());
            serverConfig_ = null;
          }
          return serverConfigBuilder_;
        }

        private secretflow.serving.ModelConfigOuterClass.ModelConfig modelConfig_;
        private com.google.protobuf.SingleFieldBuilderV3<
            secretflow.serving.ModelConfigOuterClass.ModelConfig, secretflow.serving.ModelConfigOuterClass.ModelConfig.Builder, secretflow.serving.ModelConfigOuterClass.ModelConfigOrBuilder> modelConfigBuilder_;
        /**
         * <code>.secretflow.serving.ModelConfig model_config = 2;</code>
         * @return Whether the modelConfig field is set.
         */
        public boolean hasModelConfig() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>.secretflow.serving.ModelConfig model_config = 2;</code>
         * @return The modelConfig.
         */
        public secretflow.serving.ModelConfigOuterClass.ModelConfig getModelConfig() {
          if (modelConfigBuilder_ == null) {
            return modelConfig_ == null ? secretflow.serving.ModelConfigOuterClass.ModelConfig.getDefaultInstance() : modelConfig_;
          } else {
            return modelConfigBuilder_.getMessage();
          }
        }
        /**
         * <code>.secretflow.serving.ModelConfig model_config = 2;</code>
         */
        public Builder setModelConfig(secretflow.serving.ModelConfigOuterClass.ModelConfig value) {
          if (modelConfigBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            modelConfig_ = value;
          } else {
            modelConfigBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <code>.secretflow.serving.ModelConfig model_config = 2;</code>
         */
        public Builder setModelConfig(
            secretflow.serving.ModelConfigOuterClass.ModelConfig.Builder builderForValue) {
          if (modelConfigBuilder_ == null) {
            modelConfig_ = builderForValue.build();
          } else {
            modelConfigBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <code>.secretflow.serving.ModelConfig model_config = 2;</code>
         */
        public Builder mergeModelConfig(secretflow.serving.ModelConfigOuterClass.ModelConfig value) {
          if (modelConfigBuilder_ == null) {
            if (((bitField0_ & 0x00000002) != 0) &&
              modelConfig_ != null &&
              modelConfig_ != secretflow.serving.ModelConfigOuterClass.ModelConfig.getDefaultInstance()) {
              getModelConfigBuilder().mergeFrom(value);
            } else {
              modelConfig_ = value;
            }
          } else {
            modelConfigBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <code>.secretflow.serving.ModelConfig model_config = 2;</code>
         */
        public Builder clearModelConfig() {
          bitField0_ = (bitField0_ & ~0x00000002);
          modelConfig_ = null;
          if (modelConfigBuilder_ != null) {
            modelConfigBuilder_.dispose();
            modelConfigBuilder_ = null;
          }
          onChanged();
          return this;
        }
        /**
         * <code>.secretflow.serving.ModelConfig model_config = 2;</code>
         */
        public secretflow.serving.ModelConfigOuterClass.ModelConfig.Builder getModelConfigBuilder() {
          bitField0_ |= 0x00000002;
          onChanged();
          return getModelConfigFieldBuilder().getBuilder();
        }
        /**
         * <code>.secretflow.serving.ModelConfig model_config = 2;</code>
         */
        public secretflow.serving.ModelConfigOuterClass.ModelConfigOrBuilder getModelConfigOrBuilder() {
          if (modelConfigBuilder_ != null) {
            return modelConfigBuilder_.getMessageOrBuilder();
          } else {
            return modelConfig_ == null ?
                secretflow.serving.ModelConfigOuterClass.ModelConfig.getDefaultInstance() : modelConfig_;
          }
        }
        /**
         * <code>.secretflow.serving.ModelConfig model_config = 2;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            secretflow.serving.ModelConfigOuterClass.ModelConfig, secretflow.serving.ModelConfigOuterClass.ModelConfig.Builder, secretflow.serving.ModelConfigOuterClass.ModelConfigOrBuilder> 
            getModelConfigFieldBuilder() {
          if (modelConfigBuilder_ == null) {
            modelConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                secretflow.serving.ModelConfigOuterClass.ModelConfig, secretflow.serving.ModelConfigOuterClass.ModelConfig.Builder, secretflow.serving.ModelConfigOuterClass.ModelConfigOrBuilder>(
                    getModelConfig(),
                    getParentForChildren(),
                    isClean());
            modelConfig_ = null;
          }
          return modelConfigBuilder_;
        }

        private secretflow.serving.FeatureConfig.FeatureSourceConfig featureSourceConfig_;
        private com.google.protobuf.SingleFieldBuilderV3<
            secretflow.serving.FeatureConfig.FeatureSourceConfig, secretflow.serving.FeatureConfig.FeatureSourceConfig.Builder, secretflow.serving.FeatureConfig.FeatureSourceConfigOrBuilder> featureSourceConfigBuilder_;
        /**
         * <code>.secretflow.serving.FeatureSourceConfig feature_source_config = 3;</code>
         * @return Whether the featureSourceConfig field is set.
         */
        public boolean hasFeatureSourceConfig() {
          return ((bitField0_ & 0x00000004) != 0);
        }
        /**
         * <code>.secretflow.serving.FeatureSourceConfig feature_source_config = 3;</code>
         * @return The featureSourceConfig.
         */
        public secretflow.serving.FeatureConfig.FeatureSourceConfig getFeatureSourceConfig() {
          if (featureSourceConfigBuilder_ == null) {
            return featureSourceConfig_ == null ? secretflow.serving.FeatureConfig.FeatureSourceConfig.getDefaultInstance() : featureSourceConfig_;
          } else {
            return featureSourceConfigBuilder_.getMessage();
          }
        }
        /**
         * <code>.secretflow.serving.FeatureSourceConfig feature_source_config = 3;</code>
         */
        public Builder setFeatureSourceConfig(secretflow.serving.FeatureConfig.FeatureSourceConfig value) {
          if (featureSourceConfigBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            featureSourceConfig_ = value;
          } else {
            featureSourceConfigBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000004;
          onChanged();
          return this;
        }
        /**
         * <code>.secretflow.serving.FeatureSourceConfig feature_source_config = 3;</code>
         */
        public Builder setFeatureSourceConfig(
            secretflow.serving.FeatureConfig.FeatureSourceConfig.Builder builderForValue) {
          if (featureSourceConfigBuilder_ == null) {
            featureSourceConfig_ = builderForValue.build();
          } else {
            featureSourceConfigBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000004;
          onChanged();
          return this;
        }
        /**
         * <code>.secretflow.serving.FeatureSourceConfig feature_source_config = 3;</code>
         */
        public Builder mergeFeatureSourceConfig(secretflow.serving.FeatureConfig.FeatureSourceConfig value) {
          if (featureSourceConfigBuilder_ == null) {
            if (((bitField0_ & 0x00000004) != 0) &&
              featureSourceConfig_ != null &&
              featureSourceConfig_ != secretflow.serving.FeatureConfig.FeatureSourceConfig.getDefaultInstance()) {
              getFeatureSourceConfigBuilder().mergeFrom(value);
            } else {
              featureSourceConfig_ = value;
            }
          } else {
            featureSourceConfigBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000004;
          onChanged();
          return this;
        }
        /**
         * <code>.secretflow.serving.FeatureSourceConfig feature_source_config = 3;</code>
         */
        public Builder clearFeatureSourceConfig() {
          bitField0_ = (bitField0_ & ~0x00000004);
          featureSourceConfig_ = null;
          if (featureSourceConfigBuilder_ != null) {
            featureSourceConfigBuilder_.dispose();
            featureSourceConfigBuilder_ = null;
          }
          onChanged();
          return this;
        }
        /**
         * <code>.secretflow.serving.FeatureSourceConfig feature_source_config = 3;</code>
         */
        public secretflow.serving.FeatureConfig.FeatureSourceConfig.Builder getFeatureSourceConfigBuilder() {
          bitField0_ |= 0x00000004;
          onChanged();
          return getFeatureSourceConfigFieldBuilder().getBuilder();
        }
        /**
         * <code>.secretflow.serving.FeatureSourceConfig feature_source_config = 3;</code>
         */
        public secretflow.serving.FeatureConfig.FeatureSourceConfigOrBuilder getFeatureSourceConfigOrBuilder() {
          if (featureSourceConfigBuilder_ != null) {
            return featureSourceConfigBuilder_.getMessageOrBuilder();
          } else {
            return featureSourceConfig_ == null ?
                secretflow.serving.FeatureConfig.FeatureSourceConfig.getDefaultInstance() : featureSourceConfig_;
          }
        }
        /**
         * <code>.secretflow.serving.FeatureSourceConfig feature_source_config = 3;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            secretflow.serving.FeatureConfig.FeatureSourceConfig, secretflow.serving.FeatureConfig.FeatureSourceConfig.Builder, secretflow.serving.FeatureConfig.FeatureSourceConfigOrBuilder> 
            getFeatureSourceConfigFieldBuilder() {
          if (featureSourceConfigBuilder_ == null) {
            featureSourceConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                secretflow.serving.FeatureConfig.FeatureSourceConfig, secretflow.serving.FeatureConfig.FeatureSourceConfig.Builder, secretflow.serving.FeatureConfig.FeatureSourceConfigOrBuilder>(
                    getFeatureSourceConfig(),
                    getParentForChildren(),
                    isClean());
            featureSourceConfig_ = null;
          }
          return featureSourceConfigBuilder_;
        }

        private secretflow.serving.ClusterConfigOuterClass.ChannelDesc channelDesc_;
        private com.google.protobuf.SingleFieldBuilderV3<
            secretflow.serving.ClusterConfigOuterClass.ChannelDesc, secretflow.serving.ClusterConfigOuterClass.ChannelDesc.Builder, secretflow.serving.ClusterConfigOuterClass.ChannelDescOrBuilder> channelDescBuilder_;
        /**
         * <code>.secretflow.serving.ChannelDesc channel_desc = 4;</code>
         * @return Whether the channelDesc field is set.
         */
        public boolean hasChannelDesc() {
          return ((bitField0_ & 0x00000008) != 0);
        }
        /**
         * <code>.secretflow.serving.ChannelDesc channel_desc = 4;</code>
         * @return The channelDesc.
         */
        public secretflow.serving.ClusterConfigOuterClass.ChannelDesc getChannelDesc() {
          if (channelDescBuilder_ == null) {
            return channelDesc_ == null ? secretflow.serving.ClusterConfigOuterClass.ChannelDesc.getDefaultInstance() : channelDesc_;
          } else {
            return channelDescBuilder_.getMessage();
          }
        }
        /**
         * <code>.secretflow.serving.ChannelDesc channel_desc = 4;</code>
         */
        public Builder setChannelDesc(secretflow.serving.ClusterConfigOuterClass.ChannelDesc value) {
          if (channelDescBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            channelDesc_ = value;
          } else {
            channelDescBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000008;
          onChanged();
          return this;
        }
        /**
         * <code>.secretflow.serving.ChannelDesc channel_desc = 4;</code>
         */
        public Builder setChannelDesc(
            secretflow.serving.ClusterConfigOuterClass.ChannelDesc.Builder builderForValue) {
          if (channelDescBuilder_ == null) {
            channelDesc_ = builderForValue.build();
          } else {
            channelDescBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000008;
          onChanged();
          return this;
        }
        /**
         * <code>.secretflow.serving.ChannelDesc channel_desc = 4;</code>
         */
        public Builder mergeChannelDesc(secretflow.serving.ClusterConfigOuterClass.ChannelDesc value) {
          if (channelDescBuilder_ == null) {
            if (((bitField0_ & 0x00000008) != 0) &&
              channelDesc_ != null &&
              channelDesc_ != secretflow.serving.ClusterConfigOuterClass.ChannelDesc.getDefaultInstance()) {
              getChannelDescBuilder().mergeFrom(value);
            } else {
              channelDesc_ = value;
            }
          } else {
            channelDescBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000008;
          onChanged();
          return this;
        }
        /**
         * <code>.secretflow.serving.ChannelDesc channel_desc = 4;</code>
         */
        public Builder clearChannelDesc() {
          bitField0_ = (bitField0_ & ~0x00000008);
          channelDesc_ = null;
          if (channelDescBuilder_ != null) {
            channelDescBuilder_.dispose();
            channelDescBuilder_ = null;
          }
          onChanged();
          return this;
        }
        /**
         * <code>.secretflow.serving.ChannelDesc channel_desc = 4;</code>
         */
        public secretflow.serving.ClusterConfigOuterClass.ChannelDesc.Builder getChannelDescBuilder() {
          bitField0_ |= 0x00000008;
          onChanged();
          return getChannelDescFieldBuilder().getBuilder();
        }
        /**
         * <code>.secretflow.serving.ChannelDesc channel_desc = 4;</code>
         */
        public secretflow.serving.ClusterConfigOuterClass.ChannelDescOrBuilder getChannelDescOrBuilder() {
          if (channelDescBuilder_ != null) {
            return channelDescBuilder_.getMessageOrBuilder();
          } else {
            return channelDesc_ == null ?
                secretflow.serving.ClusterConfigOuterClass.ChannelDesc.getDefaultInstance() : channelDesc_;
          }
        }
        /**
         * <code>.secretflow.serving.ChannelDesc channel_desc = 4;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            secretflow.serving.ClusterConfigOuterClass.ChannelDesc, secretflow.serving.ClusterConfigOuterClass.ChannelDesc.Builder, secretflow.serving.ClusterConfigOuterClass.ChannelDescOrBuilder> 
            getChannelDescFieldBuilder() {
          if (channelDescBuilder_ == null) {
            channelDescBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                secretflow.serving.ClusterConfigOuterClass.ChannelDesc, secretflow.serving.ClusterConfigOuterClass.ChannelDesc.Builder, secretflow.serving.ClusterConfigOuterClass.ChannelDescOrBuilder>(
                    getChannelDesc(),
                    getParentForChildren(),
                    isClean());
            channelDesc_ = null;
          }
          return channelDescBuilder_;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:secretflow.serving.kuscia.KusciaServingConfig.PartyConfig)
      }

      // @@protoc_insertion_point(class_scope:secretflow.serving.kuscia.KusciaServingConfig.PartyConfig)
      private static final secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig();
      }

      public static secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<PartyConfig>
          PARSER = new com.google.protobuf.AbstractParser<PartyConfig>() {
        @java.lang.Override
        public PartyConfig parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<PartyConfig> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<PartyConfig> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int PARTY_CONFIGS_FIELD_NUMBER = 1;
    private static final class PartyConfigsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig>newDefaultInstance(
                  secretflow.serving.kuscia.ServingConfig.internal_static_secretflow_serving_kuscia_KusciaServingConfig_PartyConfigsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig.getDefaultInstance());
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig> partyConfigs_;
    private com.google.protobuf.MapField<java.lang.String, secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig>
    internalGetPartyConfigs() {
      if (partyConfigs_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PartyConfigsDefaultEntryHolder.defaultEntry);
      }
      return partyConfigs_;
    }
    public int getPartyConfigsCount() {
      return internalGetPartyConfigs().getMap().size();
    }
    /**
     * <pre>
     * Key: Party id
     * Value: Party config
     * </pre>
     *
     * <code>map&lt;string, .secretflow.serving.kuscia.KusciaServingConfig.PartyConfig&gt; party_configs = 1;</code>
     */
    @java.lang.Override
    public boolean containsPartyConfigs(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetPartyConfigs().getMap().containsKey(key);
    }
    /**
     * Use {@link #getPartyConfigsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig> getPartyConfigs() {
      return getPartyConfigsMap();
    }
    /**
     * <pre>
     * Key: Party id
     * Value: Party config
     * </pre>
     *
     * <code>map&lt;string, .secretflow.serving.kuscia.KusciaServingConfig.PartyConfig&gt; party_configs = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig> getPartyConfigsMap() {
      return internalGetPartyConfigs().getMap();
    }
    /**
     * <pre>
     * Key: Party id
     * Value: Party config
     * </pre>
     *
     * <code>map&lt;string, .secretflow.serving.kuscia.KusciaServingConfig.PartyConfig&gt; party_configs = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig getPartyConfigsOrDefault(
        java.lang.String key,
        /* nullable */
secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig> map =
          internalGetPartyConfigs().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Key: Party id
     * Value: Party config
     * </pre>
     *
     * <code>map&lt;string, .secretflow.serving.kuscia.KusciaServingConfig.PartyConfig&gt; party_configs = 1;</code>
     */
    @java.lang.Override
    public secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig getPartyConfigsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig> map =
          internalGetPartyConfigs().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetPartyConfigs(),
          PartyConfigsDefaultEntryHolder.defaultEntry,
          1);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig> entry
           : internalGetPartyConfigs().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig>
        partyConfigs__ = PartyConfigsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, partyConfigs__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof secretflow.serving.kuscia.ServingConfig.KusciaServingConfig)) {
        return super.equals(obj);
      }
      secretflow.serving.kuscia.ServingConfig.KusciaServingConfig other = (secretflow.serving.kuscia.ServingConfig.KusciaServingConfig) obj;

      if (!internalGetPartyConfigs().equals(
          other.internalGetPartyConfigs())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetPartyConfigs().getMap().isEmpty()) {
        hash = (37 * hash) + PARTY_CONFIGS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetPartyConfigs().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static secretflow.serving.kuscia.ServingConfig.KusciaServingConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static secretflow.serving.kuscia.ServingConfig.KusciaServingConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static secretflow.serving.kuscia.ServingConfig.KusciaServingConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static secretflow.serving.kuscia.ServingConfig.KusciaServingConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static secretflow.serving.kuscia.ServingConfig.KusciaServingConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static secretflow.serving.kuscia.ServingConfig.KusciaServingConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static secretflow.serving.kuscia.ServingConfig.KusciaServingConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static secretflow.serving.kuscia.ServingConfig.KusciaServingConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static secretflow.serving.kuscia.ServingConfig.KusciaServingConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static secretflow.serving.kuscia.ServingConfig.KusciaServingConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static secretflow.serving.kuscia.ServingConfig.KusciaServingConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static secretflow.serving.kuscia.ServingConfig.KusciaServingConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(secretflow.serving.kuscia.ServingConfig.KusciaServingConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code secretflow.serving.kuscia.KusciaServingConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:secretflow.serving.kuscia.KusciaServingConfig)
        secretflow.serving.kuscia.ServingConfig.KusciaServingConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return secretflow.serving.kuscia.ServingConfig.internal_static_secretflow_serving_kuscia_KusciaServingConfig_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetPartyConfigs();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutablePartyConfigs();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return secretflow.serving.kuscia.ServingConfig.internal_static_secretflow_serving_kuscia_KusciaServingConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.class, secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.Builder.class);
      }

      // Construct using secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        internalGetMutablePartyConfigs().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return secretflow.serving.kuscia.ServingConfig.internal_static_secretflow_serving_kuscia_KusciaServingConfig_descriptor;
      }

      @java.lang.Override
      public secretflow.serving.kuscia.ServingConfig.KusciaServingConfig getDefaultInstanceForType() {
        return secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.getDefaultInstance();
      }

      @java.lang.Override
      public secretflow.serving.kuscia.ServingConfig.KusciaServingConfig build() {
        secretflow.serving.kuscia.ServingConfig.KusciaServingConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public secretflow.serving.kuscia.ServingConfig.KusciaServingConfig buildPartial() {
        secretflow.serving.kuscia.ServingConfig.KusciaServingConfig result = new secretflow.serving.kuscia.ServingConfig.KusciaServingConfig(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(secretflow.serving.kuscia.ServingConfig.KusciaServingConfig result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.partyConfigs_ = internalGetPartyConfigs();
          result.partyConfigs_.makeImmutable();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof secretflow.serving.kuscia.ServingConfig.KusciaServingConfig) {
          return mergeFrom((secretflow.serving.kuscia.ServingConfig.KusciaServingConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(secretflow.serving.kuscia.ServingConfig.KusciaServingConfig other) {
        if (other == secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.getDefaultInstance()) return this;
        internalGetMutablePartyConfigs().mergeFrom(
            other.internalGetPartyConfigs());
        bitField0_ |= 0x00000001;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.MapEntry<java.lang.String, secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig>
                partyConfigs__ = input.readMessage(
                    PartyConfigsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutablePartyConfigs().getMutableMap().put(
                    partyConfigs__.getKey(), partyConfigs__.getValue());
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig> partyConfigs_;
      private com.google.protobuf.MapField<java.lang.String, secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig>
          internalGetPartyConfigs() {
        if (partyConfigs_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              PartyConfigsDefaultEntryHolder.defaultEntry);
        }
        return partyConfigs_;
      }
      private com.google.protobuf.MapField<java.lang.String, secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig>
          internalGetMutablePartyConfigs() {
        if (partyConfigs_ == null) {
          partyConfigs_ = com.google.protobuf.MapField.newMapField(
              PartyConfigsDefaultEntryHolder.defaultEntry);
        }
        if (!partyConfigs_.isMutable()) {
          partyConfigs_ = partyConfigs_.copy();
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return partyConfigs_;
      }
      public int getPartyConfigsCount() {
        return internalGetPartyConfigs().getMap().size();
      }
      /**
       * <pre>
       * Key: Party id
       * Value: Party config
       * </pre>
       *
       * <code>map&lt;string, .secretflow.serving.kuscia.KusciaServingConfig.PartyConfig&gt; party_configs = 1;</code>
       */
      @java.lang.Override
      public boolean containsPartyConfigs(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetPartyConfigs().getMap().containsKey(key);
      }
      /**
       * Use {@link #getPartyConfigsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig> getPartyConfigs() {
        return getPartyConfigsMap();
      }
      /**
       * <pre>
       * Key: Party id
       * Value: Party config
       * </pre>
       *
       * <code>map&lt;string, .secretflow.serving.kuscia.KusciaServingConfig.PartyConfig&gt; party_configs = 1;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig> getPartyConfigsMap() {
        return internalGetPartyConfigs().getMap();
      }
      /**
       * <pre>
       * Key: Party id
       * Value: Party config
       * </pre>
       *
       * <code>map&lt;string, .secretflow.serving.kuscia.KusciaServingConfig.PartyConfig&gt; party_configs = 1;</code>
       */
      @java.lang.Override
      public /* nullable */
secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig getPartyConfigsOrDefault(
          java.lang.String key,
          /* nullable */
secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig> map =
            internalGetPartyConfigs().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * Key: Party id
       * Value: Party config
       * </pre>
       *
       * <code>map&lt;string, .secretflow.serving.kuscia.KusciaServingConfig.PartyConfig&gt; party_configs = 1;</code>
       */
      @java.lang.Override
      public secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig getPartyConfigsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig> map =
            internalGetPartyConfigs().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearPartyConfigs() {
        bitField0_ = (bitField0_ & ~0x00000001);
        internalGetMutablePartyConfigs().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * Key: Party id
       * Value: Party config
       * </pre>
       *
       * <code>map&lt;string, .secretflow.serving.kuscia.KusciaServingConfig.PartyConfig&gt; party_configs = 1;</code>
       */
      public Builder removePartyConfigs(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutablePartyConfigs().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig>
          getMutablePartyConfigs() {
        bitField0_ |= 0x00000001;
        return internalGetMutablePartyConfigs().getMutableMap();
      }
      /**
       * <pre>
       * Key: Party id
       * Value: Party config
       * </pre>
       *
       * <code>map&lt;string, .secretflow.serving.kuscia.KusciaServingConfig.PartyConfig&gt; party_configs = 1;</code>
       */
      public Builder putPartyConfigs(
          java.lang.String key,
          secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutablePartyConfigs().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * Key: Party id
       * Value: Party config
       * </pre>
       *
       * <code>map&lt;string, .secretflow.serving.kuscia.KusciaServingConfig.PartyConfig&gt; party_configs = 1;</code>
       */
      public Builder putAllPartyConfigs(
          java.util.Map<java.lang.String, secretflow.serving.kuscia.ServingConfig.KusciaServingConfig.PartyConfig> values) {
        internalGetMutablePartyConfigs().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000001;
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:secretflow.serving.kuscia.KusciaServingConfig)
    }

    // @@protoc_insertion_point(class_scope:secretflow.serving.kuscia.KusciaServingConfig)
    private static final secretflow.serving.kuscia.ServingConfig.KusciaServingConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new secretflow.serving.kuscia.ServingConfig.KusciaServingConfig();
    }

    public static secretflow.serving.kuscia.ServingConfig.KusciaServingConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<KusciaServingConfig>
        PARSER = new com.google.protobuf.AbstractParser<KusciaServingConfig>() {
      @java.lang.Override
      public KusciaServingConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<KusciaServingConfig> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<KusciaServingConfig> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public secretflow.serving.kuscia.ServingConfig.KusciaServingConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_secretflow_serving_kuscia_KusciaServingConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_secretflow_serving_kuscia_KusciaServingConfig_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_secretflow_serving_kuscia_KusciaServingConfig_PartyConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_secretflow_serving_kuscia_KusciaServingConfig_PartyConfig_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_secretflow_serving_kuscia_KusciaServingConfig_PartyConfigsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_secretflow_serving_kuscia_KusciaServingConfig_PartyConfigsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.secretflow/serving/kuscia/serving_conf" +
      "ig.proto\022\031secretflow.serving.kuscia\032-sec" +
      "retflow_serving/config/server_config.pro" +
      "to\032.secretflow_serving/config/feature_co" +
      "nfig.proto\032,secretflow_serving/config/mo" +
      "del_config.proto\032.secretflow_serving/con" +
      "fig/cluster_config.proto\"\336\003\n\023KusciaServi" +
      "ngConfig\022W\n\rparty_configs\030\001 \003(\0132@.secret" +
      "flow.serving.kuscia.KusciaServingConfig." +
      "PartyConfigsEntry\032\374\001\n\013PartyConfig\0227\n\rser" +
      "ver_config\030\001 \001(\0132 .secretflow.serving.Se" +
      "rverConfig\0225\n\014model_config\030\002 \001(\0132\037.secre" +
      "tflow.serving.ModelConfig\022F\n\025feature_sou" +
      "rce_config\030\003 \001(\0132\'.secretflow.serving.Fe" +
      "atureSourceConfig\0225\n\014channel_desc\030\004 \001(\0132" +
      "\037.secretflow.serving.ChannelDesc\032o\n\021Part" +
      "yConfigsEntry\022\013\n\003key\030\001 \001(\t\022I\n\005value\030\002 \001(" +
      "\0132:.secretflow.serving.kuscia.KusciaServ" +
      "ingConfig.PartyConfig:\0028\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          secretflow.serving.ServerConfigOuterClass.getDescriptor(),
          secretflow.serving.FeatureConfig.getDescriptor(),
          secretflow.serving.ModelConfigOuterClass.getDescriptor(),
          secretflow.serving.ClusterConfigOuterClass.getDescriptor(),
        });
    internal_static_secretflow_serving_kuscia_KusciaServingConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_secretflow_serving_kuscia_KusciaServingConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_secretflow_serving_kuscia_KusciaServingConfig_descriptor,
        new java.lang.String[] { "PartyConfigs", });
    internal_static_secretflow_serving_kuscia_KusciaServingConfig_PartyConfig_descriptor =
      internal_static_secretflow_serving_kuscia_KusciaServingConfig_descriptor.getNestedTypes().get(0);
    internal_static_secretflow_serving_kuscia_KusciaServingConfig_PartyConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_secretflow_serving_kuscia_KusciaServingConfig_PartyConfig_descriptor,
        new java.lang.String[] { "ServerConfig", "ModelConfig", "FeatureSourceConfig", "ChannelDesc", });
    internal_static_secretflow_serving_kuscia_KusciaServingConfig_PartyConfigsEntry_descriptor =
      internal_static_secretflow_serving_kuscia_KusciaServingConfig_descriptor.getNestedTypes().get(1);
    internal_static_secretflow_serving_kuscia_KusciaServingConfig_PartyConfigsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_secretflow_serving_kuscia_KusciaServingConfig_PartyConfigsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    secretflow.serving.ServerConfigOuterClass.getDescriptor();
    secretflow.serving.FeatureConfig.getDescriptor();
    secretflow.serving.ModelConfigOuterClass.getDescriptor();
    secretflow.serving.ClusterConfigOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
