// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: secretflow/protos/pipeline/task_config.proto

package org.secretflow.proto.pipeline;

public final class TaskConfigOuterClass {
  private TaskConfigOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TaskConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:secretflow.pipeline.TaskConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * task_initiator_id
     * </pre>
     *
     * <code>string task_initiator_id = 1;</code>
     * @return The taskInitiatorId.
     */
    java.lang.String getTaskInitiatorId();
    /**
     * <pre>
     * task_initiator_id
     * </pre>
     *
     * <code>string task_initiator_id = 1;</code>
     * @return The bytes for taskInitiatorId.
     */
    com.google.protobuf.ByteString
        getTaskInitiatorIdBytes();

    /**
     * <pre>
     * kuscia： {project_id}
     * local： "default"
     * </pre>
     *
     * <code>string scope = 2;</code>
     * @return The scope.
     */
    java.lang.String getScope();
    /**
     * <pre>
     * kuscia： {project_id}
     * local： "default"
     * </pre>
     *
     * <code>string scope = 2;</code>
     * @return The bytes for scope.
     */
    com.google.protobuf.ByteString
        getScopeBytes();

    /**
     * <pre>
     * base64
     * </pre>
     *
     * <code>string task_body = 3;</code>
     * @return The taskBody.
     */
    java.lang.String getTaskBody();
    /**
     * <pre>
     * base64
     * </pre>
     *
     * <code>string task_body = 3;</code>
     * @return The bytes for taskBody.
     */
    com.google.protobuf.ByteString
        getTaskBodyBytes();

    /**
     * <pre>
     *  task_initiator_id || . || scope || . || task_body 的sign
     * </pre>
     *
     * <code>string signature = 20;</code>
     * @return The signature.
     */
    java.lang.String getSignature();
    /**
     * <pre>
     *  task_initiator_id || . || scope || . || task_body 的sign
     * </pre>
     *
     * <code>string signature = 20;</code>
     * @return The bytes for signature.
     */
    com.google.protobuf.ByteString
        getSignatureBytes();

    /**
     * <pre>
     *   * RS256: RSASSA-PKCS1-v1_5 using SHA-256
     *   * ES256: ECDSA using P-256 and SHA-256
     * </pre>
     *
     * <code>string sign_algorithm = 21;</code>
     * @return The signAlgorithm.
     */
    java.lang.String getSignAlgorithm();
    /**
     * <pre>
     *   * RS256: RSASSA-PKCS1-v1_5 using SHA-256
     *   * ES256: ECDSA using P-256 and SHA-256
     * </pre>
     *
     * <code>string sign_algorithm = 21;</code>
     * @return The bytes for signAlgorithm.
     */
    com.google.protobuf.ByteString
        getSignAlgorithmBytes();

    /**
     * <pre>
     * cert chain
     * </pre>
     *
     * <code>repeated string task_initiator_certs = 22;</code>
     * @return A list containing the taskInitiatorCerts.
     */
    java.util.List<java.lang.String>
        getTaskInitiatorCertsList();
    /**
     * <pre>
     * cert chain
     * </pre>
     *
     * <code>repeated string task_initiator_certs = 22;</code>
     * @return The count of taskInitiatorCerts.
     */
    int getTaskInitiatorCertsCount();
    /**
     * <pre>
     * cert chain
     * </pre>
     *
     * <code>repeated string task_initiator_certs = 22;</code>
     * @param index The index of the element to return.
     * @return The taskInitiatorCerts at the given index.
     */
    java.lang.String getTaskInitiatorCerts(int index);
    /**
     * <pre>
     * cert chain
     * </pre>
     *
     * <code>repeated string task_initiator_certs = 22;</code>
     * @param index The index of the value to return.
     * @return The bytes of the taskInitiatorCerts at the given index.
     */
    com.google.protobuf.ByteString
        getTaskInitiatorCertsBytes(int index);

    /**
     * <pre>
     * capsule manager service
     * </pre>
     *
     * <code>string capsule_manager_endpoint = 23;</code>
     * @return The capsuleManagerEndpoint.
     */
    java.lang.String getCapsuleManagerEndpoint();
    /**
     * <pre>
     * capsule manager service
     * </pre>
     *
     * <code>string capsule_manager_endpoint = 23;</code>
     * @return The bytes for capsuleManagerEndpoint.
     */
    com.google.protobuf.ByteString
        getCapsuleManagerEndpointBytes();
  }
  /**
   * Protobuf type {@code secretflow.pipeline.TaskConfig}
   */
  public static final class TaskConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:secretflow.pipeline.TaskConfig)
      TaskConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TaskConfig.newBuilder() to construct.
    private TaskConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TaskConfig() {
      taskInitiatorId_ = "";
      scope_ = "";
      taskBody_ = "";
      signature_ = "";
      signAlgorithm_ = "";
      taskInitiatorCerts_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      capsuleManagerEndpoint_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TaskConfig();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.secretflow.proto.pipeline.TaskConfigOuterClass.internal_static_secretflow_pipeline_TaskConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.secretflow.proto.pipeline.TaskConfigOuterClass.internal_static_secretflow_pipeline_TaskConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig.class, org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig.Builder.class);
    }

    public static final int TASK_INITIATOR_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object taskInitiatorId_ = "";
    /**
     * <pre>
     * task_initiator_id
     * </pre>
     *
     * <code>string task_initiator_id = 1;</code>
     * @return The taskInitiatorId.
     */
    @java.lang.Override
    public java.lang.String getTaskInitiatorId() {
      java.lang.Object ref = taskInitiatorId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskInitiatorId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * task_initiator_id
     * </pre>
     *
     * <code>string task_initiator_id = 1;</code>
     * @return The bytes for taskInitiatorId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTaskInitiatorIdBytes() {
      java.lang.Object ref = taskInitiatorId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskInitiatorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCOPE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object scope_ = "";
    /**
     * <pre>
     * kuscia： {project_id}
     * local： "default"
     * </pre>
     *
     * <code>string scope = 2;</code>
     * @return The scope.
     */
    @java.lang.Override
    public java.lang.String getScope() {
      java.lang.Object ref = scope_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        scope_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * kuscia： {project_id}
     * local： "default"
     * </pre>
     *
     * <code>string scope = 2;</code>
     * @return The bytes for scope.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getScopeBytes() {
      java.lang.Object ref = scope_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        scope_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TASK_BODY_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object taskBody_ = "";
    /**
     * <pre>
     * base64
     * </pre>
     *
     * <code>string task_body = 3;</code>
     * @return The taskBody.
     */
    @java.lang.Override
    public java.lang.String getTaskBody() {
      java.lang.Object ref = taskBody_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskBody_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * base64
     * </pre>
     *
     * <code>string task_body = 3;</code>
     * @return The bytes for taskBody.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTaskBodyBytes() {
      java.lang.Object ref = taskBody_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskBody_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIGNATURE_FIELD_NUMBER = 20;
    @SuppressWarnings("serial")
    private volatile java.lang.Object signature_ = "";
    /**
     * <pre>
     *  task_initiator_id || . || scope || . || task_body 的sign
     * </pre>
     *
     * <code>string signature = 20;</code>
     * @return The signature.
     */
    @java.lang.Override
    public java.lang.String getSignature() {
      java.lang.Object ref = signature_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        signature_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *  task_initiator_id || . || scope || . || task_body 的sign
     * </pre>
     *
     * <code>string signature = 20;</code>
     * @return The bytes for signature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSignatureBytes() {
      java.lang.Object ref = signature_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIGN_ALGORITHM_FIELD_NUMBER = 21;
    @SuppressWarnings("serial")
    private volatile java.lang.Object signAlgorithm_ = "";
    /**
     * <pre>
     *   * RS256: RSASSA-PKCS1-v1_5 using SHA-256
     *   * ES256: ECDSA using P-256 and SHA-256
     * </pre>
     *
     * <code>string sign_algorithm = 21;</code>
     * @return The signAlgorithm.
     */
    @java.lang.Override
    public java.lang.String getSignAlgorithm() {
      java.lang.Object ref = signAlgorithm_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        signAlgorithm_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *   * RS256: RSASSA-PKCS1-v1_5 using SHA-256
     *   * ES256: ECDSA using P-256 and SHA-256
     * </pre>
     *
     * <code>string sign_algorithm = 21;</code>
     * @return The bytes for signAlgorithm.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSignAlgorithmBytes() {
      java.lang.Object ref = signAlgorithm_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signAlgorithm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TASK_INITIATOR_CERTS_FIELD_NUMBER = 22;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList taskInitiatorCerts_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <pre>
     * cert chain
     * </pre>
     *
     * <code>repeated string task_initiator_certs = 22;</code>
     * @return A list containing the taskInitiatorCerts.
     */
    public com.google.protobuf.ProtocolStringList
        getTaskInitiatorCertsList() {
      return taskInitiatorCerts_;
    }
    /**
     * <pre>
     * cert chain
     * </pre>
     *
     * <code>repeated string task_initiator_certs = 22;</code>
     * @return The count of taskInitiatorCerts.
     */
    public int getTaskInitiatorCertsCount() {
      return taskInitiatorCerts_.size();
    }
    /**
     * <pre>
     * cert chain
     * </pre>
     *
     * <code>repeated string task_initiator_certs = 22;</code>
     * @param index The index of the element to return.
     * @return The taskInitiatorCerts at the given index.
     */
    public java.lang.String getTaskInitiatorCerts(int index) {
      return taskInitiatorCerts_.get(index);
    }
    /**
     * <pre>
     * cert chain
     * </pre>
     *
     * <code>repeated string task_initiator_certs = 22;</code>
     * @param index The index of the value to return.
     * @return The bytes of the taskInitiatorCerts at the given index.
     */
    public com.google.protobuf.ByteString
        getTaskInitiatorCertsBytes(int index) {
      return taskInitiatorCerts_.getByteString(index);
    }

    public static final int CAPSULE_MANAGER_ENDPOINT_FIELD_NUMBER = 23;
    @SuppressWarnings("serial")
    private volatile java.lang.Object capsuleManagerEndpoint_ = "";
    /**
     * <pre>
     * capsule manager service
     * </pre>
     *
     * <code>string capsule_manager_endpoint = 23;</code>
     * @return The capsuleManagerEndpoint.
     */
    @java.lang.Override
    public java.lang.String getCapsuleManagerEndpoint() {
      java.lang.Object ref = capsuleManagerEndpoint_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        capsuleManagerEndpoint_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * capsule manager service
     * </pre>
     *
     * <code>string capsule_manager_endpoint = 23;</code>
     * @return The bytes for capsuleManagerEndpoint.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCapsuleManagerEndpointBytes() {
      java.lang.Object ref = capsuleManagerEndpoint_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        capsuleManagerEndpoint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(taskInitiatorId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, taskInitiatorId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(scope_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, scope_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(taskBody_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, taskBody_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(signature_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 20, signature_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(signAlgorithm_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 21, signAlgorithm_);
      }
      for (int i = 0; i < taskInitiatorCerts_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 22, taskInitiatorCerts_.getRaw(i));
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(capsuleManagerEndpoint_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 23, capsuleManagerEndpoint_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(taskInitiatorId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, taskInitiatorId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(scope_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, scope_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(taskBody_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, taskBody_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(signature_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(20, signature_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(signAlgorithm_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(21, signAlgorithm_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < taskInitiatorCerts_.size(); i++) {
          dataSize += computeStringSizeNoTag(taskInitiatorCerts_.getRaw(i));
        }
        size += dataSize;
        size += 2 * getTaskInitiatorCertsList().size();
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(capsuleManagerEndpoint_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(23, capsuleManagerEndpoint_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig)) {
        return super.equals(obj);
      }
      org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig other = (org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig) obj;

      if (!getTaskInitiatorId()
          .equals(other.getTaskInitiatorId())) return false;
      if (!getScope()
          .equals(other.getScope())) return false;
      if (!getTaskBody()
          .equals(other.getTaskBody())) return false;
      if (!getSignature()
          .equals(other.getSignature())) return false;
      if (!getSignAlgorithm()
          .equals(other.getSignAlgorithm())) return false;
      if (!getTaskInitiatorCertsList()
          .equals(other.getTaskInitiatorCertsList())) return false;
      if (!getCapsuleManagerEndpoint()
          .equals(other.getCapsuleManagerEndpoint())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TASK_INITIATOR_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTaskInitiatorId().hashCode();
      hash = (37 * hash) + SCOPE_FIELD_NUMBER;
      hash = (53 * hash) + getScope().hashCode();
      hash = (37 * hash) + TASK_BODY_FIELD_NUMBER;
      hash = (53 * hash) + getTaskBody().hashCode();
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
      hash = (37 * hash) + SIGN_ALGORITHM_FIELD_NUMBER;
      hash = (53 * hash) + getSignAlgorithm().hashCode();
      if (getTaskInitiatorCertsCount() > 0) {
        hash = (37 * hash) + TASK_INITIATOR_CERTS_FIELD_NUMBER;
        hash = (53 * hash) + getTaskInitiatorCertsList().hashCode();
      }
      hash = (37 * hash) + CAPSULE_MANAGER_ENDPOINT_FIELD_NUMBER;
      hash = (53 * hash) + getCapsuleManagerEndpoint().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code secretflow.pipeline.TaskConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:secretflow.pipeline.TaskConfig)
        org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.secretflow.proto.pipeline.TaskConfigOuterClass.internal_static_secretflow_pipeline_TaskConfig_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.secretflow.proto.pipeline.TaskConfigOuterClass.internal_static_secretflow_pipeline_TaskConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig.class, org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig.Builder.class);
      }

      // Construct using org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        taskInitiatorId_ = "";
        scope_ = "";
        taskBody_ = "";
        signature_ = "";
        signAlgorithm_ = "";
        taskInitiatorCerts_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        capsuleManagerEndpoint_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.secretflow.proto.pipeline.TaskConfigOuterClass.internal_static_secretflow_pipeline_TaskConfig_descriptor;
      }

      @java.lang.Override
      public org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig getDefaultInstanceForType() {
        return org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig.getDefaultInstance();
      }

      @java.lang.Override
      public org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig build() {
        org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig buildPartial() {
        org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig result = new org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.taskInitiatorId_ = taskInitiatorId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.scope_ = scope_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.taskBody_ = taskBody_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.signature_ = signature_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.signAlgorithm_ = signAlgorithm_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          taskInitiatorCerts_.makeImmutable();
          result.taskInitiatorCerts_ = taskInitiatorCerts_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.capsuleManagerEndpoint_ = capsuleManagerEndpoint_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig) {
          return mergeFrom((org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig other) {
        if (other == org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig.getDefaultInstance()) return this;
        if (!other.getTaskInitiatorId().isEmpty()) {
          taskInitiatorId_ = other.taskInitiatorId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getScope().isEmpty()) {
          scope_ = other.scope_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getTaskBody().isEmpty()) {
          taskBody_ = other.taskBody_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getSignature().isEmpty()) {
          signature_ = other.signature_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getSignAlgorithm().isEmpty()) {
          signAlgorithm_ = other.signAlgorithm_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.taskInitiatorCerts_.isEmpty()) {
          if (taskInitiatorCerts_.isEmpty()) {
            taskInitiatorCerts_ = other.taskInitiatorCerts_;
            bitField0_ |= 0x00000020;
          } else {
            ensureTaskInitiatorCertsIsMutable();
            taskInitiatorCerts_.addAll(other.taskInitiatorCerts_);
          }
          onChanged();
        }
        if (!other.getCapsuleManagerEndpoint().isEmpty()) {
          capsuleManagerEndpoint_ = other.capsuleManagerEndpoint_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                taskInitiatorId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                scope_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                taskBody_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 162: {
                signature_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 162
              case 170: {
                signAlgorithm_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 170
              case 178: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureTaskInitiatorCertsIsMutable();
                taskInitiatorCerts_.add(s);
                break;
              } // case 178
              case 186: {
                capsuleManagerEndpoint_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 186
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object taskInitiatorId_ = "";
      /**
       * <pre>
       * task_initiator_id
       * </pre>
       *
       * <code>string task_initiator_id = 1;</code>
       * @return The taskInitiatorId.
       */
      public java.lang.String getTaskInitiatorId() {
        java.lang.Object ref = taskInitiatorId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          taskInitiatorId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * task_initiator_id
       * </pre>
       *
       * <code>string task_initiator_id = 1;</code>
       * @return The bytes for taskInitiatorId.
       */
      public com.google.protobuf.ByteString
          getTaskInitiatorIdBytes() {
        java.lang.Object ref = taskInitiatorId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskInitiatorId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * task_initiator_id
       * </pre>
       *
       * <code>string task_initiator_id = 1;</code>
       * @param value The taskInitiatorId to set.
       * @return This builder for chaining.
       */
      public Builder setTaskInitiatorId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        taskInitiatorId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * task_initiator_id
       * </pre>
       *
       * <code>string task_initiator_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTaskInitiatorId() {
        taskInitiatorId_ = getDefaultInstance().getTaskInitiatorId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * task_initiator_id
       * </pre>
       *
       * <code>string task_initiator_id = 1;</code>
       * @param value The bytes for taskInitiatorId to set.
       * @return This builder for chaining.
       */
      public Builder setTaskInitiatorIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        taskInitiatorId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object scope_ = "";
      /**
       * <pre>
       * kuscia： {project_id}
       * local： "default"
       * </pre>
       *
       * <code>string scope = 2;</code>
       * @return The scope.
       */
      public java.lang.String getScope() {
        java.lang.Object ref = scope_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          scope_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * kuscia： {project_id}
       * local： "default"
       * </pre>
       *
       * <code>string scope = 2;</code>
       * @return The bytes for scope.
       */
      public com.google.protobuf.ByteString
          getScopeBytes() {
        java.lang.Object ref = scope_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          scope_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * kuscia： {project_id}
       * local： "default"
       * </pre>
       *
       * <code>string scope = 2;</code>
       * @param value The scope to set.
       * @return This builder for chaining.
       */
      public Builder setScope(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        scope_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * kuscia： {project_id}
       * local： "default"
       * </pre>
       *
       * <code>string scope = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearScope() {
        scope_ = getDefaultInstance().getScope();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * kuscia： {project_id}
       * local： "default"
       * </pre>
       *
       * <code>string scope = 2;</code>
       * @param value The bytes for scope to set.
       * @return This builder for chaining.
       */
      public Builder setScopeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        scope_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object taskBody_ = "";
      /**
       * <pre>
       * base64
       * </pre>
       *
       * <code>string task_body = 3;</code>
       * @return The taskBody.
       */
      public java.lang.String getTaskBody() {
        java.lang.Object ref = taskBody_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          taskBody_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * base64
       * </pre>
       *
       * <code>string task_body = 3;</code>
       * @return The bytes for taskBody.
       */
      public com.google.protobuf.ByteString
          getTaskBodyBytes() {
        java.lang.Object ref = taskBody_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskBody_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * base64
       * </pre>
       *
       * <code>string task_body = 3;</code>
       * @param value The taskBody to set.
       * @return This builder for chaining.
       */
      public Builder setTaskBody(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        taskBody_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * base64
       * </pre>
       *
       * <code>string task_body = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTaskBody() {
        taskBody_ = getDefaultInstance().getTaskBody();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * base64
       * </pre>
       *
       * <code>string task_body = 3;</code>
       * @param value The bytes for taskBody to set.
       * @return This builder for chaining.
       */
      public Builder setTaskBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        taskBody_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object signature_ = "";
      /**
       * <pre>
       *  task_initiator_id || . || scope || . || task_body 的sign
       * </pre>
       *
       * <code>string signature = 20;</code>
       * @return The signature.
       */
      public java.lang.String getSignature() {
        java.lang.Object ref = signature_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          signature_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *  task_initiator_id || . || scope || . || task_body 的sign
       * </pre>
       *
       * <code>string signature = 20;</code>
       * @return The bytes for signature.
       */
      public com.google.protobuf.ByteString
          getSignatureBytes() {
        java.lang.Object ref = signature_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          signature_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *  task_initiator_id || . || scope || . || task_body 的sign
       * </pre>
       *
       * <code>string signature = 20;</code>
       * @param value The signature to set.
       * @return This builder for chaining.
       */
      public Builder setSignature(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        signature_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  task_initiator_id || . || scope || . || task_body 的sign
       * </pre>
       *
       * <code>string signature = 20;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignature() {
        signature_ = getDefaultInstance().getSignature();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  task_initiator_id || . || scope || . || task_body 的sign
       * </pre>
       *
       * <code>string signature = 20;</code>
       * @param value The bytes for signature to set.
       * @return This builder for chaining.
       */
      public Builder setSignatureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        signature_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object signAlgorithm_ = "";
      /**
       * <pre>
       *   * RS256: RSASSA-PKCS1-v1_5 using SHA-256
       *   * ES256: ECDSA using P-256 and SHA-256
       * </pre>
       *
       * <code>string sign_algorithm = 21;</code>
       * @return The signAlgorithm.
       */
      public java.lang.String getSignAlgorithm() {
        java.lang.Object ref = signAlgorithm_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          signAlgorithm_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *   * RS256: RSASSA-PKCS1-v1_5 using SHA-256
       *   * ES256: ECDSA using P-256 and SHA-256
       * </pre>
       *
       * <code>string sign_algorithm = 21;</code>
       * @return The bytes for signAlgorithm.
       */
      public com.google.protobuf.ByteString
          getSignAlgorithmBytes() {
        java.lang.Object ref = signAlgorithm_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          signAlgorithm_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *   * RS256: RSASSA-PKCS1-v1_5 using SHA-256
       *   * ES256: ECDSA using P-256 and SHA-256
       * </pre>
       *
       * <code>string sign_algorithm = 21;</code>
       * @param value The signAlgorithm to set.
       * @return This builder for chaining.
       */
      public Builder setSignAlgorithm(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        signAlgorithm_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *   * RS256: RSASSA-PKCS1-v1_5 using SHA-256
       *   * ES256: ECDSA using P-256 and SHA-256
       * </pre>
       *
       * <code>string sign_algorithm = 21;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignAlgorithm() {
        signAlgorithm_ = getDefaultInstance().getSignAlgorithm();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *   * RS256: RSASSA-PKCS1-v1_5 using SHA-256
       *   * ES256: ECDSA using P-256 and SHA-256
       * </pre>
       *
       * <code>string sign_algorithm = 21;</code>
       * @param value The bytes for signAlgorithm to set.
       * @return This builder for chaining.
       */
      public Builder setSignAlgorithmBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        signAlgorithm_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList taskInitiatorCerts_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureTaskInitiatorCertsIsMutable() {
        if (!taskInitiatorCerts_.isModifiable()) {
          taskInitiatorCerts_ = new com.google.protobuf.LazyStringArrayList(taskInitiatorCerts_);
        }
        bitField0_ |= 0x00000020;
      }
      /**
       * <pre>
       * cert chain
       * </pre>
       *
       * <code>repeated string task_initiator_certs = 22;</code>
       * @return A list containing the taskInitiatorCerts.
       */
      public com.google.protobuf.ProtocolStringList
          getTaskInitiatorCertsList() {
        taskInitiatorCerts_.makeImmutable();
        return taskInitiatorCerts_;
      }
      /**
       * <pre>
       * cert chain
       * </pre>
       *
       * <code>repeated string task_initiator_certs = 22;</code>
       * @return The count of taskInitiatorCerts.
       */
      public int getTaskInitiatorCertsCount() {
        return taskInitiatorCerts_.size();
      }
      /**
       * <pre>
       * cert chain
       * </pre>
       *
       * <code>repeated string task_initiator_certs = 22;</code>
       * @param index The index of the element to return.
       * @return The taskInitiatorCerts at the given index.
       */
      public java.lang.String getTaskInitiatorCerts(int index) {
        return taskInitiatorCerts_.get(index);
      }
      /**
       * <pre>
       * cert chain
       * </pre>
       *
       * <code>repeated string task_initiator_certs = 22;</code>
       * @param index The index of the value to return.
       * @return The bytes of the taskInitiatorCerts at the given index.
       */
      public com.google.protobuf.ByteString
          getTaskInitiatorCertsBytes(int index) {
        return taskInitiatorCerts_.getByteString(index);
      }
      /**
       * <pre>
       * cert chain
       * </pre>
       *
       * <code>repeated string task_initiator_certs = 22;</code>
       * @param index The index to set the value at.
       * @param value The taskInitiatorCerts to set.
       * @return This builder for chaining.
       */
      public Builder setTaskInitiatorCerts(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureTaskInitiatorCertsIsMutable();
        taskInitiatorCerts_.set(index, value);
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * cert chain
       * </pre>
       *
       * <code>repeated string task_initiator_certs = 22;</code>
       * @param value The taskInitiatorCerts to add.
       * @return This builder for chaining.
       */
      public Builder addTaskInitiatorCerts(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureTaskInitiatorCertsIsMutable();
        taskInitiatorCerts_.add(value);
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * cert chain
       * </pre>
       *
       * <code>repeated string task_initiator_certs = 22;</code>
       * @param values The taskInitiatorCerts to add.
       * @return This builder for chaining.
       */
      public Builder addAllTaskInitiatorCerts(
          java.lang.Iterable<java.lang.String> values) {
        ensureTaskInitiatorCertsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, taskInitiatorCerts_);
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * cert chain
       * </pre>
       *
       * <code>repeated string task_initiator_certs = 22;</code>
       * @return This builder for chaining.
       */
      public Builder clearTaskInitiatorCerts() {
        taskInitiatorCerts_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * cert chain
       * </pre>
       *
       * <code>repeated string task_initiator_certs = 22;</code>
       * @param value The bytes of the taskInitiatorCerts to add.
       * @return This builder for chaining.
       */
      public Builder addTaskInitiatorCertsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureTaskInitiatorCertsIsMutable();
        taskInitiatorCerts_.add(value);
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object capsuleManagerEndpoint_ = "";
      /**
       * <pre>
       * capsule manager service
       * </pre>
       *
       * <code>string capsule_manager_endpoint = 23;</code>
       * @return The capsuleManagerEndpoint.
       */
      public java.lang.String getCapsuleManagerEndpoint() {
        java.lang.Object ref = capsuleManagerEndpoint_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          capsuleManagerEndpoint_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * capsule manager service
       * </pre>
       *
       * <code>string capsule_manager_endpoint = 23;</code>
       * @return The bytes for capsuleManagerEndpoint.
       */
      public com.google.protobuf.ByteString
          getCapsuleManagerEndpointBytes() {
        java.lang.Object ref = capsuleManagerEndpoint_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          capsuleManagerEndpoint_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * capsule manager service
       * </pre>
       *
       * <code>string capsule_manager_endpoint = 23;</code>
       * @param value The capsuleManagerEndpoint to set.
       * @return This builder for chaining.
       */
      public Builder setCapsuleManagerEndpoint(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        capsuleManagerEndpoint_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * capsule manager service
       * </pre>
       *
       * <code>string capsule_manager_endpoint = 23;</code>
       * @return This builder for chaining.
       */
      public Builder clearCapsuleManagerEndpoint() {
        capsuleManagerEndpoint_ = getDefaultInstance().getCapsuleManagerEndpoint();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * capsule manager service
       * </pre>
       *
       * <code>string capsule_manager_endpoint = 23;</code>
       * @param value The bytes for capsuleManagerEndpoint to set.
       * @return This builder for chaining.
       */
      public Builder setCapsuleManagerEndpointBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        capsuleManagerEndpoint_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:secretflow.pipeline.TaskConfig)
    }

    // @@protoc_insertion_point(class_scope:secretflow.pipeline.TaskConfig)
    private static final org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig();
    }

    public static org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TaskConfig>
        PARSER = new com.google.protobuf.AbstractParser<TaskConfig>() {
      @java.lang.Override
      public TaskConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TaskConfig> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TaskConfig> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_secretflow_pipeline_TaskConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_secretflow_pipeline_TaskConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,secretflow/protos/pipeline/task_config" +
      ".proto\022\023secretflow.pipeline\"\264\001\n\nTaskConf" +
      "ig\022\031\n\021task_initiator_id\030\001 \001(\t\022\r\n\005scope\030\002" +
      " \001(\t\022\021\n\ttask_body\030\003 \001(\t\022\021\n\tsignature\030\024 \001" +
      "(\t\022\026\n\016sign_algorithm\030\025 \001(\t\022\034\n\024task_initi" +
      "ator_certs\030\026 \003(\t\022 \n\030capsule_manager_endp" +
      "oint\030\027 \001(\tB\037\n\035org.secretflow.proto.pipel" +
      "ineb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_secretflow_pipeline_TaskConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_secretflow_pipeline_TaskConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_secretflow_pipeline_TaskConfig_descriptor,
        new java.lang.String[] { "TaskInitiatorId", "Scope", "TaskBody", "Signature", "SignAlgorithm", "TaskInitiatorCerts", "CapsuleManagerEndpoint", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
