// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: secretflow/protos/kuscia/task_config.proto

package org.secretflow.proto.kuscia;

public final class TaskConfig {
  private TaskConfig() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TaskInputConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:secretflow.kuscia.TaskInputConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, .secretflow.kuscia.DatasourceConfig&gt; sf_datasource_config = 1;</code>
     */
    int getSfDatasourceConfigCount();
    /**
     * <code>map&lt;string, .secretflow.kuscia.DatasourceConfig&gt; sf_datasource_config = 1;</code>
     */
    boolean containsSfDatasourceConfig(
        java.lang.String key);
    /**
     * Use {@link #getSfDatasourceConfigMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig>
    getSfDatasourceConfig();
    /**
     * <code>map&lt;string, .secretflow.kuscia.DatasourceConfig&gt; sf_datasource_config = 1;</code>
     */
    java.util.Map<java.lang.String, org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig>
    getSfDatasourceConfigMap();
    /**
     * <code>map&lt;string, .secretflow.kuscia.DatasourceConfig&gt; sf_datasource_config = 1;</code>
     */
    /* nullable */
org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig getSfDatasourceConfigOrDefault(
        java.lang.String key,
        /* nullable */
org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig defaultValue);
    /**
     * <code>map&lt;string, .secretflow.kuscia.DatasourceConfig&gt; sf_datasource_config = 1;</code>
     */
    org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig getSfDatasourceConfigOrThrow(
        java.lang.String key);

    /**
     * <code>.secretflow.component.SFClusterDesc sf_cluster_desc = 2;</code>
     * @return Whether the sfClusterDesc field is set.
     */
    boolean hasSfClusterDesc();
    /**
     * <code>.secretflow.component.SFClusterDesc sf_cluster_desc = 2;</code>
     * @return The sfClusterDesc.
     */
    org.secretflow.proto.component.Cluster.SFClusterDesc getSfClusterDesc();
    /**
     * <code>.secretflow.component.SFClusterDesc sf_cluster_desc = 2;</code>
     */
    org.secretflow.proto.component.Cluster.SFClusterDescOrBuilder getSfClusterDescOrBuilder();

    /**
     * <code>.secretflow.pipeline.NodeDef sf_node_eval_param = 3;</code>
     * @return Whether the sfNodeEvalParam field is set.
     */
    boolean hasSfNodeEvalParam();
    /**
     * <code>.secretflow.pipeline.NodeDef sf_node_eval_param = 3;</code>
     * @return The sfNodeEvalParam.
     */
    org.secretflow.proto.pipeline.Pipeline.NodeDef getSfNodeEvalParam();
    /**
     * <code>.secretflow.pipeline.NodeDef sf_node_eval_param = 3;</code>
     */
    org.secretflow.proto.pipeline.Pipeline.NodeDefOrBuilder getSfNodeEvalParamOrBuilder();

    /**
     * <code>repeated string sf_output_uris = 4;</code>
     * @return A list containing the sfOutputUris.
     */
    java.util.List<java.lang.String>
        getSfOutputUrisList();
    /**
     * <code>repeated string sf_output_uris = 4;</code>
     * @return The count of sfOutputUris.
     */
    int getSfOutputUrisCount();
    /**
     * <code>repeated string sf_output_uris = 4;</code>
     * @param index The index of the element to return.
     * @return The sfOutputUris at the given index.
     */
    java.lang.String getSfOutputUris(int index);
    /**
     * <code>repeated string sf_output_uris = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the sfOutputUris at the given index.
     */
    com.google.protobuf.ByteString
        getSfOutputUrisBytes(int index);

    /**
     * <code>repeated string sf_input_ids = 5;</code>
     * @return A list containing the sfInputIds.
     */
    java.util.List<java.lang.String>
        getSfInputIdsList();
    /**
     * <code>repeated string sf_input_ids = 5;</code>
     * @return The count of sfInputIds.
     */
    int getSfInputIdsCount();
    /**
     * <code>repeated string sf_input_ids = 5;</code>
     * @param index The index of the element to return.
     * @return The sfInputIds at the given index.
     */
    java.lang.String getSfInputIds(int index);
    /**
     * <code>repeated string sf_input_ids = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the sfInputIds at the given index.
     */
    com.google.protobuf.ByteString
        getSfInputIdsBytes(int index);

    /**
     * <code>repeated string sf_output_ids = 6;</code>
     * @return A list containing the sfOutputIds.
     */
    java.util.List<java.lang.String>
        getSfOutputIdsList();
    /**
     * <code>repeated string sf_output_ids = 6;</code>
     * @return The count of sfOutputIds.
     */
    int getSfOutputIdsCount();
    /**
     * <code>repeated string sf_output_ids = 6;</code>
     * @param index The index of the element to return.
     * @return The sfOutputIds at the given index.
     */
    java.lang.String getSfOutputIds(int index);
    /**
     * <code>repeated string sf_output_ids = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the sfOutputIds at the given index.
     */
    com.google.protobuf.ByteString
        getSfOutputIdsBytes(int index);

    /**
     * <code>.secretflow.pipeline.TaskConfig tee_task_config = 7;</code>
     * @return Whether the teeTaskConfig field is set.
     */
    boolean hasTeeTaskConfig();
    /**
     * <code>.secretflow.pipeline.TaskConfig tee_task_config = 7;</code>
     * @return The teeTaskConfig.
     */
    org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig getTeeTaskConfig();
    /**
     * <code>.secretflow.pipeline.TaskConfig tee_task_config = 7;</code>
     */
    org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfigOrBuilder getTeeTaskConfigOrBuilder();
  }
  /**
   * Protobuf type {@code secretflow.kuscia.TaskInputConfig}
   */
  public static final class TaskInputConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:secretflow.kuscia.TaskInputConfig)
      TaskInputConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TaskInputConfig.newBuilder() to construct.
    private TaskInputConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TaskInputConfig() {
      sfOutputUris_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      sfInputIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      sfOutputIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TaskInputConfig();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.secretflow.proto.kuscia.TaskConfig.internal_static_secretflow_kuscia_TaskInputConfig_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetSfDatasourceConfig();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.secretflow.proto.kuscia.TaskConfig.internal_static_secretflow_kuscia_TaskInputConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig.class, org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig.Builder.class);
    }

    public static final int SF_DATASOURCE_CONFIG_FIELD_NUMBER = 1;
    private static final class SfDatasourceConfigDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig>newDefaultInstance(
                  org.secretflow.proto.kuscia.TaskConfig.internal_static_secretflow_kuscia_TaskInputConfig_SfDatasourceConfigEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig.getDefaultInstance());
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig> sfDatasourceConfig_;
    private com.google.protobuf.MapField<java.lang.String, org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig>
    internalGetSfDatasourceConfig() {
      if (sfDatasourceConfig_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            SfDatasourceConfigDefaultEntryHolder.defaultEntry);
      }
      return sfDatasourceConfig_;
    }
    public int getSfDatasourceConfigCount() {
      return internalGetSfDatasourceConfig().getMap().size();
    }
    /**
     * <code>map&lt;string, .secretflow.kuscia.DatasourceConfig&gt; sf_datasource_config = 1;</code>
     */
    @java.lang.Override
    public boolean containsSfDatasourceConfig(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetSfDatasourceConfig().getMap().containsKey(key);
    }
    /**
     * Use {@link #getSfDatasourceConfigMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig> getSfDatasourceConfig() {
      return getSfDatasourceConfigMap();
    }
    /**
     * <code>map&lt;string, .secretflow.kuscia.DatasourceConfig&gt; sf_datasource_config = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig> getSfDatasourceConfigMap() {
      return internalGetSfDatasourceConfig().getMap();
    }
    /**
     * <code>map&lt;string, .secretflow.kuscia.DatasourceConfig&gt; sf_datasource_config = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig getSfDatasourceConfigOrDefault(
        java.lang.String key,
        /* nullable */
org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig> map =
          internalGetSfDatasourceConfig().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .secretflow.kuscia.DatasourceConfig&gt; sf_datasource_config = 1;</code>
     */
    @java.lang.Override
    public org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig getSfDatasourceConfigOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig> map =
          internalGetSfDatasourceConfig().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int SF_CLUSTER_DESC_FIELD_NUMBER = 2;
    private org.secretflow.proto.component.Cluster.SFClusterDesc sfClusterDesc_;
    /**
     * <code>.secretflow.component.SFClusterDesc sf_cluster_desc = 2;</code>
     * @return Whether the sfClusterDesc field is set.
     */
    @java.lang.Override
    public boolean hasSfClusterDesc() {
      return sfClusterDesc_ != null;
    }
    /**
     * <code>.secretflow.component.SFClusterDesc sf_cluster_desc = 2;</code>
     * @return The sfClusterDesc.
     */
    @java.lang.Override
    public org.secretflow.proto.component.Cluster.SFClusterDesc getSfClusterDesc() {
      return sfClusterDesc_ == null ? org.secretflow.proto.component.Cluster.SFClusterDesc.getDefaultInstance() : sfClusterDesc_;
    }
    /**
     * <code>.secretflow.component.SFClusterDesc sf_cluster_desc = 2;</code>
     */
    @java.lang.Override
    public org.secretflow.proto.component.Cluster.SFClusterDescOrBuilder getSfClusterDescOrBuilder() {
      return sfClusterDesc_ == null ? org.secretflow.proto.component.Cluster.SFClusterDesc.getDefaultInstance() : sfClusterDesc_;
    }

    public static final int SF_NODE_EVAL_PARAM_FIELD_NUMBER = 3;
    private org.secretflow.proto.pipeline.Pipeline.NodeDef sfNodeEvalParam_;
    /**
     * <code>.secretflow.pipeline.NodeDef sf_node_eval_param = 3;</code>
     * @return Whether the sfNodeEvalParam field is set.
     */
    @java.lang.Override
    public boolean hasSfNodeEvalParam() {
      return sfNodeEvalParam_ != null;
    }
    /**
     * <code>.secretflow.pipeline.NodeDef sf_node_eval_param = 3;</code>
     * @return The sfNodeEvalParam.
     */
    @java.lang.Override
    public org.secretflow.proto.pipeline.Pipeline.NodeDef getSfNodeEvalParam() {
      return sfNodeEvalParam_ == null ? org.secretflow.proto.pipeline.Pipeline.NodeDef.getDefaultInstance() : sfNodeEvalParam_;
    }
    /**
     * <code>.secretflow.pipeline.NodeDef sf_node_eval_param = 3;</code>
     */
    @java.lang.Override
    public org.secretflow.proto.pipeline.Pipeline.NodeDefOrBuilder getSfNodeEvalParamOrBuilder() {
      return sfNodeEvalParam_ == null ? org.secretflow.proto.pipeline.Pipeline.NodeDef.getDefaultInstance() : sfNodeEvalParam_;
    }

    public static final int SF_OUTPUT_URIS_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList sfOutputUris_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string sf_output_uris = 4;</code>
     * @return A list containing the sfOutputUris.
     */
    public com.google.protobuf.ProtocolStringList
        getSfOutputUrisList() {
      return sfOutputUris_;
    }
    /**
     * <code>repeated string sf_output_uris = 4;</code>
     * @return The count of sfOutputUris.
     */
    public int getSfOutputUrisCount() {
      return sfOutputUris_.size();
    }
    /**
     * <code>repeated string sf_output_uris = 4;</code>
     * @param index The index of the element to return.
     * @return The sfOutputUris at the given index.
     */
    public java.lang.String getSfOutputUris(int index) {
      return sfOutputUris_.get(index);
    }
    /**
     * <code>repeated string sf_output_uris = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the sfOutputUris at the given index.
     */
    public com.google.protobuf.ByteString
        getSfOutputUrisBytes(int index) {
      return sfOutputUris_.getByteString(index);
    }

    public static final int SF_INPUT_IDS_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList sfInputIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string sf_input_ids = 5;</code>
     * @return A list containing the sfInputIds.
     */
    public com.google.protobuf.ProtocolStringList
        getSfInputIdsList() {
      return sfInputIds_;
    }
    /**
     * <code>repeated string sf_input_ids = 5;</code>
     * @return The count of sfInputIds.
     */
    public int getSfInputIdsCount() {
      return sfInputIds_.size();
    }
    /**
     * <code>repeated string sf_input_ids = 5;</code>
     * @param index The index of the element to return.
     * @return The sfInputIds at the given index.
     */
    public java.lang.String getSfInputIds(int index) {
      return sfInputIds_.get(index);
    }
    /**
     * <code>repeated string sf_input_ids = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the sfInputIds at the given index.
     */
    public com.google.protobuf.ByteString
        getSfInputIdsBytes(int index) {
      return sfInputIds_.getByteString(index);
    }

    public static final int SF_OUTPUT_IDS_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList sfOutputIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string sf_output_ids = 6;</code>
     * @return A list containing the sfOutputIds.
     */
    public com.google.protobuf.ProtocolStringList
        getSfOutputIdsList() {
      return sfOutputIds_;
    }
    /**
     * <code>repeated string sf_output_ids = 6;</code>
     * @return The count of sfOutputIds.
     */
    public int getSfOutputIdsCount() {
      return sfOutputIds_.size();
    }
    /**
     * <code>repeated string sf_output_ids = 6;</code>
     * @param index The index of the element to return.
     * @return The sfOutputIds at the given index.
     */
    public java.lang.String getSfOutputIds(int index) {
      return sfOutputIds_.get(index);
    }
    /**
     * <code>repeated string sf_output_ids = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the sfOutputIds at the given index.
     */
    public com.google.protobuf.ByteString
        getSfOutputIdsBytes(int index) {
      return sfOutputIds_.getByteString(index);
    }

    public static final int TEE_TASK_CONFIG_FIELD_NUMBER = 7;
    private org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig teeTaskConfig_;
    /**
     * <code>.secretflow.pipeline.TaskConfig tee_task_config = 7;</code>
     * @return Whether the teeTaskConfig field is set.
     */
    @java.lang.Override
    public boolean hasTeeTaskConfig() {
      return teeTaskConfig_ != null;
    }
    /**
     * <code>.secretflow.pipeline.TaskConfig tee_task_config = 7;</code>
     * @return The teeTaskConfig.
     */
    @java.lang.Override
    public org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig getTeeTaskConfig() {
      return teeTaskConfig_ == null ? org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig.getDefaultInstance() : teeTaskConfig_;
    }
    /**
     * <code>.secretflow.pipeline.TaskConfig tee_task_config = 7;</code>
     */
    @java.lang.Override
    public org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfigOrBuilder getTeeTaskConfigOrBuilder() {
      return teeTaskConfig_ == null ? org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig.getDefaultInstance() : teeTaskConfig_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetSfDatasourceConfig(),
          SfDatasourceConfigDefaultEntryHolder.defaultEntry,
          1);
      if (sfClusterDesc_ != null) {
        output.writeMessage(2, getSfClusterDesc());
      }
      if (sfNodeEvalParam_ != null) {
        output.writeMessage(3, getSfNodeEvalParam());
      }
      for (int i = 0; i < sfOutputUris_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sfOutputUris_.getRaw(i));
      }
      for (int i = 0; i < sfInputIds_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, sfInputIds_.getRaw(i));
      }
      for (int i = 0; i < sfOutputIds_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, sfOutputIds_.getRaw(i));
      }
      if (teeTaskConfig_ != null) {
        output.writeMessage(7, getTeeTaskConfig());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig> entry
           : internalGetSfDatasourceConfig().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig>
        sfDatasourceConfig__ = SfDatasourceConfigDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, sfDatasourceConfig__);
      }
      if (sfClusterDesc_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getSfClusterDesc());
      }
      if (sfNodeEvalParam_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getSfNodeEvalParam());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < sfOutputUris_.size(); i++) {
          dataSize += computeStringSizeNoTag(sfOutputUris_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSfOutputUrisList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < sfInputIds_.size(); i++) {
          dataSize += computeStringSizeNoTag(sfInputIds_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSfInputIdsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < sfOutputIds_.size(); i++) {
          dataSize += computeStringSizeNoTag(sfOutputIds_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSfOutputIdsList().size();
      }
      if (teeTaskConfig_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getTeeTaskConfig());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig)) {
        return super.equals(obj);
      }
      org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig other = (org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig) obj;

      if (!internalGetSfDatasourceConfig().equals(
          other.internalGetSfDatasourceConfig())) return false;
      if (hasSfClusterDesc() != other.hasSfClusterDesc()) return false;
      if (hasSfClusterDesc()) {
        if (!getSfClusterDesc()
            .equals(other.getSfClusterDesc())) return false;
      }
      if (hasSfNodeEvalParam() != other.hasSfNodeEvalParam()) return false;
      if (hasSfNodeEvalParam()) {
        if (!getSfNodeEvalParam()
            .equals(other.getSfNodeEvalParam())) return false;
      }
      if (!getSfOutputUrisList()
          .equals(other.getSfOutputUrisList())) return false;
      if (!getSfInputIdsList()
          .equals(other.getSfInputIdsList())) return false;
      if (!getSfOutputIdsList()
          .equals(other.getSfOutputIdsList())) return false;
      if (hasTeeTaskConfig() != other.hasTeeTaskConfig()) return false;
      if (hasTeeTaskConfig()) {
        if (!getTeeTaskConfig()
            .equals(other.getTeeTaskConfig())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetSfDatasourceConfig().getMap().isEmpty()) {
        hash = (37 * hash) + SF_DATASOURCE_CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + internalGetSfDatasourceConfig().hashCode();
      }
      if (hasSfClusterDesc()) {
        hash = (37 * hash) + SF_CLUSTER_DESC_FIELD_NUMBER;
        hash = (53 * hash) + getSfClusterDesc().hashCode();
      }
      if (hasSfNodeEvalParam()) {
        hash = (37 * hash) + SF_NODE_EVAL_PARAM_FIELD_NUMBER;
        hash = (53 * hash) + getSfNodeEvalParam().hashCode();
      }
      if (getSfOutputUrisCount() > 0) {
        hash = (37 * hash) + SF_OUTPUT_URIS_FIELD_NUMBER;
        hash = (53 * hash) + getSfOutputUrisList().hashCode();
      }
      if (getSfInputIdsCount() > 0) {
        hash = (37 * hash) + SF_INPUT_IDS_FIELD_NUMBER;
        hash = (53 * hash) + getSfInputIdsList().hashCode();
      }
      if (getSfOutputIdsCount() > 0) {
        hash = (37 * hash) + SF_OUTPUT_IDS_FIELD_NUMBER;
        hash = (53 * hash) + getSfOutputIdsList().hashCode();
      }
      if (hasTeeTaskConfig()) {
        hash = (37 * hash) + TEE_TASK_CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getTeeTaskConfig().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code secretflow.kuscia.TaskInputConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:secretflow.kuscia.TaskInputConfig)
        org.secretflow.proto.kuscia.TaskConfig.TaskInputConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.secretflow.proto.kuscia.TaskConfig.internal_static_secretflow_kuscia_TaskInputConfig_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetSfDatasourceConfig();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableSfDatasourceConfig();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.secretflow.proto.kuscia.TaskConfig.internal_static_secretflow_kuscia_TaskInputConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig.class, org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig.Builder.class);
      }

      // Construct using org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        internalGetMutableSfDatasourceConfig().clear();
        sfClusterDesc_ = null;
        if (sfClusterDescBuilder_ != null) {
          sfClusterDescBuilder_.dispose();
          sfClusterDescBuilder_ = null;
        }
        sfNodeEvalParam_ = null;
        if (sfNodeEvalParamBuilder_ != null) {
          sfNodeEvalParamBuilder_.dispose();
          sfNodeEvalParamBuilder_ = null;
        }
        sfOutputUris_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        sfInputIds_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        sfOutputIds_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        teeTaskConfig_ = null;
        if (teeTaskConfigBuilder_ != null) {
          teeTaskConfigBuilder_.dispose();
          teeTaskConfigBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.secretflow.proto.kuscia.TaskConfig.internal_static_secretflow_kuscia_TaskInputConfig_descriptor;
      }

      @java.lang.Override
      public org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig getDefaultInstanceForType() {
        return org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig.getDefaultInstance();
      }

      @java.lang.Override
      public org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig build() {
        org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig buildPartial() {
        org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig result = new org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.sfDatasourceConfig_ = internalGetSfDatasourceConfig();
          result.sfDatasourceConfig_.makeImmutable();
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.sfClusterDesc_ = sfClusterDescBuilder_ == null
              ? sfClusterDesc_
              : sfClusterDescBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.sfNodeEvalParam_ = sfNodeEvalParamBuilder_ == null
              ? sfNodeEvalParam_
              : sfNodeEvalParamBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          sfOutputUris_.makeImmutable();
          result.sfOutputUris_ = sfOutputUris_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          sfInputIds_.makeImmutable();
          result.sfInputIds_ = sfInputIds_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          sfOutputIds_.makeImmutable();
          result.sfOutputIds_ = sfOutputIds_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.teeTaskConfig_ = teeTaskConfigBuilder_ == null
              ? teeTaskConfig_
              : teeTaskConfigBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig) {
          return mergeFrom((org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig other) {
        if (other == org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig.getDefaultInstance()) return this;
        internalGetMutableSfDatasourceConfig().mergeFrom(
            other.internalGetSfDatasourceConfig());
        bitField0_ |= 0x00000001;
        if (other.hasSfClusterDesc()) {
          mergeSfClusterDesc(other.getSfClusterDesc());
        }
        if (other.hasSfNodeEvalParam()) {
          mergeSfNodeEvalParam(other.getSfNodeEvalParam());
        }
        if (!other.sfOutputUris_.isEmpty()) {
          if (sfOutputUris_.isEmpty()) {
            sfOutputUris_ = other.sfOutputUris_;
            bitField0_ |= 0x00000008;
          } else {
            ensureSfOutputUrisIsMutable();
            sfOutputUris_.addAll(other.sfOutputUris_);
          }
          onChanged();
        }
        if (!other.sfInputIds_.isEmpty()) {
          if (sfInputIds_.isEmpty()) {
            sfInputIds_ = other.sfInputIds_;
            bitField0_ |= 0x00000010;
          } else {
            ensureSfInputIdsIsMutable();
            sfInputIds_.addAll(other.sfInputIds_);
          }
          onChanged();
        }
        if (!other.sfOutputIds_.isEmpty()) {
          if (sfOutputIds_.isEmpty()) {
            sfOutputIds_ = other.sfOutputIds_;
            bitField0_ |= 0x00000020;
          } else {
            ensureSfOutputIdsIsMutable();
            sfOutputIds_.addAll(other.sfOutputIds_);
          }
          onChanged();
        }
        if (other.hasTeeTaskConfig()) {
          mergeTeeTaskConfig(other.getTeeTaskConfig());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.MapEntry<java.lang.String, org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig>
                sfDatasourceConfig__ = input.readMessage(
                    SfDatasourceConfigDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableSfDatasourceConfig().getMutableMap().put(
                    sfDatasourceConfig__.getKey(), sfDatasourceConfig__.getValue());
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getSfClusterDescFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getSfNodeEvalParamFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureSfOutputUrisIsMutable();
                sfOutputUris_.add(s);
                break;
              } // case 34
              case 42: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureSfInputIdsIsMutable();
                sfInputIds_.add(s);
                break;
              } // case 42
              case 50: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureSfOutputIdsIsMutable();
                sfOutputIds_.add(s);
                break;
              } // case 50
              case 58: {
                input.readMessage(
                    getTeeTaskConfigFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig> sfDatasourceConfig_;
      private com.google.protobuf.MapField<java.lang.String, org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig>
          internalGetSfDatasourceConfig() {
        if (sfDatasourceConfig_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              SfDatasourceConfigDefaultEntryHolder.defaultEntry);
        }
        return sfDatasourceConfig_;
      }
      private com.google.protobuf.MapField<java.lang.String, org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig>
          internalGetMutableSfDatasourceConfig() {
        if (sfDatasourceConfig_ == null) {
          sfDatasourceConfig_ = com.google.protobuf.MapField.newMapField(
              SfDatasourceConfigDefaultEntryHolder.defaultEntry);
        }
        if (!sfDatasourceConfig_.isMutable()) {
          sfDatasourceConfig_ = sfDatasourceConfig_.copy();
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return sfDatasourceConfig_;
      }
      public int getSfDatasourceConfigCount() {
        return internalGetSfDatasourceConfig().getMap().size();
      }
      /**
       * <code>map&lt;string, .secretflow.kuscia.DatasourceConfig&gt; sf_datasource_config = 1;</code>
       */
      @java.lang.Override
      public boolean containsSfDatasourceConfig(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetSfDatasourceConfig().getMap().containsKey(key);
      }
      /**
       * Use {@link #getSfDatasourceConfigMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig> getSfDatasourceConfig() {
        return getSfDatasourceConfigMap();
      }
      /**
       * <code>map&lt;string, .secretflow.kuscia.DatasourceConfig&gt; sf_datasource_config = 1;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig> getSfDatasourceConfigMap() {
        return internalGetSfDatasourceConfig().getMap();
      }
      /**
       * <code>map&lt;string, .secretflow.kuscia.DatasourceConfig&gt; sf_datasource_config = 1;</code>
       */
      @java.lang.Override
      public /* nullable */
org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig getSfDatasourceConfigOrDefault(
          java.lang.String key,
          /* nullable */
org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig> map =
            internalGetSfDatasourceConfig().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .secretflow.kuscia.DatasourceConfig&gt; sf_datasource_config = 1;</code>
       */
      @java.lang.Override
      public org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig getSfDatasourceConfigOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig> map =
            internalGetSfDatasourceConfig().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearSfDatasourceConfig() {
        bitField0_ = (bitField0_ & ~0x00000001);
        internalGetMutableSfDatasourceConfig().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .secretflow.kuscia.DatasourceConfig&gt; sf_datasource_config = 1;</code>
       */
      public Builder removeSfDatasourceConfig(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableSfDatasourceConfig().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig>
          getMutableSfDatasourceConfig() {
        bitField0_ |= 0x00000001;
        return internalGetMutableSfDatasourceConfig().getMutableMap();
      }
      /**
       * <code>map&lt;string, .secretflow.kuscia.DatasourceConfig&gt; sf_datasource_config = 1;</code>
       */
      public Builder putSfDatasourceConfig(
          java.lang.String key,
          org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableSfDatasourceConfig().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>map&lt;string, .secretflow.kuscia.DatasourceConfig&gt; sf_datasource_config = 1;</code>
       */
      public Builder putAllSfDatasourceConfig(
          java.util.Map<java.lang.String, org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig> values) {
        internalGetMutableSfDatasourceConfig().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000001;
        return this;
      }

      private org.secretflow.proto.component.Cluster.SFClusterDesc sfClusterDesc_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.secretflow.proto.component.Cluster.SFClusterDesc, org.secretflow.proto.component.Cluster.SFClusterDesc.Builder, org.secretflow.proto.component.Cluster.SFClusterDescOrBuilder> sfClusterDescBuilder_;
      /**
       * <code>.secretflow.component.SFClusterDesc sf_cluster_desc = 2;</code>
       * @return Whether the sfClusterDesc field is set.
       */
      public boolean hasSfClusterDesc() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.secretflow.component.SFClusterDesc sf_cluster_desc = 2;</code>
       * @return The sfClusterDesc.
       */
      public org.secretflow.proto.component.Cluster.SFClusterDesc getSfClusterDesc() {
        if (sfClusterDescBuilder_ == null) {
          return sfClusterDesc_ == null ? org.secretflow.proto.component.Cluster.SFClusterDesc.getDefaultInstance() : sfClusterDesc_;
        } else {
          return sfClusterDescBuilder_.getMessage();
        }
      }
      /**
       * <code>.secretflow.component.SFClusterDesc sf_cluster_desc = 2;</code>
       */
      public Builder setSfClusterDesc(org.secretflow.proto.component.Cluster.SFClusterDesc value) {
        if (sfClusterDescBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sfClusterDesc_ = value;
        } else {
          sfClusterDescBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.component.SFClusterDesc sf_cluster_desc = 2;</code>
       */
      public Builder setSfClusterDesc(
          org.secretflow.proto.component.Cluster.SFClusterDesc.Builder builderForValue) {
        if (sfClusterDescBuilder_ == null) {
          sfClusterDesc_ = builderForValue.build();
        } else {
          sfClusterDescBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.component.SFClusterDesc sf_cluster_desc = 2;</code>
       */
      public Builder mergeSfClusterDesc(org.secretflow.proto.component.Cluster.SFClusterDesc value) {
        if (sfClusterDescBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            sfClusterDesc_ != null &&
            sfClusterDesc_ != org.secretflow.proto.component.Cluster.SFClusterDesc.getDefaultInstance()) {
            getSfClusterDescBuilder().mergeFrom(value);
          } else {
            sfClusterDesc_ = value;
          }
        } else {
          sfClusterDescBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.component.SFClusterDesc sf_cluster_desc = 2;</code>
       */
      public Builder clearSfClusterDesc() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sfClusterDesc_ = null;
        if (sfClusterDescBuilder_ != null) {
          sfClusterDescBuilder_.dispose();
          sfClusterDescBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.component.SFClusterDesc sf_cluster_desc = 2;</code>
       */
      public org.secretflow.proto.component.Cluster.SFClusterDesc.Builder getSfClusterDescBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getSfClusterDescFieldBuilder().getBuilder();
      }
      /**
       * <code>.secretflow.component.SFClusterDesc sf_cluster_desc = 2;</code>
       */
      public org.secretflow.proto.component.Cluster.SFClusterDescOrBuilder getSfClusterDescOrBuilder() {
        if (sfClusterDescBuilder_ != null) {
          return sfClusterDescBuilder_.getMessageOrBuilder();
        } else {
          return sfClusterDesc_ == null ?
              org.secretflow.proto.component.Cluster.SFClusterDesc.getDefaultInstance() : sfClusterDesc_;
        }
      }
      /**
       * <code>.secretflow.component.SFClusterDesc sf_cluster_desc = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.secretflow.proto.component.Cluster.SFClusterDesc, org.secretflow.proto.component.Cluster.SFClusterDesc.Builder, org.secretflow.proto.component.Cluster.SFClusterDescOrBuilder> 
          getSfClusterDescFieldBuilder() {
        if (sfClusterDescBuilder_ == null) {
          sfClusterDescBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.secretflow.proto.component.Cluster.SFClusterDesc, org.secretflow.proto.component.Cluster.SFClusterDesc.Builder, org.secretflow.proto.component.Cluster.SFClusterDescOrBuilder>(
                  getSfClusterDesc(),
                  getParentForChildren(),
                  isClean());
          sfClusterDesc_ = null;
        }
        return sfClusterDescBuilder_;
      }

      private org.secretflow.proto.pipeline.Pipeline.NodeDef sfNodeEvalParam_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.secretflow.proto.pipeline.Pipeline.NodeDef, org.secretflow.proto.pipeline.Pipeline.NodeDef.Builder, org.secretflow.proto.pipeline.Pipeline.NodeDefOrBuilder> sfNodeEvalParamBuilder_;
      /**
       * <code>.secretflow.pipeline.NodeDef sf_node_eval_param = 3;</code>
       * @return Whether the sfNodeEvalParam field is set.
       */
      public boolean hasSfNodeEvalParam() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.secretflow.pipeline.NodeDef sf_node_eval_param = 3;</code>
       * @return The sfNodeEvalParam.
       */
      public org.secretflow.proto.pipeline.Pipeline.NodeDef getSfNodeEvalParam() {
        if (sfNodeEvalParamBuilder_ == null) {
          return sfNodeEvalParam_ == null ? org.secretflow.proto.pipeline.Pipeline.NodeDef.getDefaultInstance() : sfNodeEvalParam_;
        } else {
          return sfNodeEvalParamBuilder_.getMessage();
        }
      }
      /**
       * <code>.secretflow.pipeline.NodeDef sf_node_eval_param = 3;</code>
       */
      public Builder setSfNodeEvalParam(org.secretflow.proto.pipeline.Pipeline.NodeDef value) {
        if (sfNodeEvalParamBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sfNodeEvalParam_ = value;
        } else {
          sfNodeEvalParamBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.pipeline.NodeDef sf_node_eval_param = 3;</code>
       */
      public Builder setSfNodeEvalParam(
          org.secretflow.proto.pipeline.Pipeline.NodeDef.Builder builderForValue) {
        if (sfNodeEvalParamBuilder_ == null) {
          sfNodeEvalParam_ = builderForValue.build();
        } else {
          sfNodeEvalParamBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.pipeline.NodeDef sf_node_eval_param = 3;</code>
       */
      public Builder mergeSfNodeEvalParam(org.secretflow.proto.pipeline.Pipeline.NodeDef value) {
        if (sfNodeEvalParamBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            sfNodeEvalParam_ != null &&
            sfNodeEvalParam_ != org.secretflow.proto.pipeline.Pipeline.NodeDef.getDefaultInstance()) {
            getSfNodeEvalParamBuilder().mergeFrom(value);
          } else {
            sfNodeEvalParam_ = value;
          }
        } else {
          sfNodeEvalParamBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.pipeline.NodeDef sf_node_eval_param = 3;</code>
       */
      public Builder clearSfNodeEvalParam() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sfNodeEvalParam_ = null;
        if (sfNodeEvalParamBuilder_ != null) {
          sfNodeEvalParamBuilder_.dispose();
          sfNodeEvalParamBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.pipeline.NodeDef sf_node_eval_param = 3;</code>
       */
      public org.secretflow.proto.pipeline.Pipeline.NodeDef.Builder getSfNodeEvalParamBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getSfNodeEvalParamFieldBuilder().getBuilder();
      }
      /**
       * <code>.secretflow.pipeline.NodeDef sf_node_eval_param = 3;</code>
       */
      public org.secretflow.proto.pipeline.Pipeline.NodeDefOrBuilder getSfNodeEvalParamOrBuilder() {
        if (sfNodeEvalParamBuilder_ != null) {
          return sfNodeEvalParamBuilder_.getMessageOrBuilder();
        } else {
          return sfNodeEvalParam_ == null ?
              org.secretflow.proto.pipeline.Pipeline.NodeDef.getDefaultInstance() : sfNodeEvalParam_;
        }
      }
      /**
       * <code>.secretflow.pipeline.NodeDef sf_node_eval_param = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.secretflow.proto.pipeline.Pipeline.NodeDef, org.secretflow.proto.pipeline.Pipeline.NodeDef.Builder, org.secretflow.proto.pipeline.Pipeline.NodeDefOrBuilder> 
          getSfNodeEvalParamFieldBuilder() {
        if (sfNodeEvalParamBuilder_ == null) {
          sfNodeEvalParamBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.secretflow.proto.pipeline.Pipeline.NodeDef, org.secretflow.proto.pipeline.Pipeline.NodeDef.Builder, org.secretflow.proto.pipeline.Pipeline.NodeDefOrBuilder>(
                  getSfNodeEvalParam(),
                  getParentForChildren(),
                  isClean());
          sfNodeEvalParam_ = null;
        }
        return sfNodeEvalParamBuilder_;
      }

      private com.google.protobuf.LazyStringArrayList sfOutputUris_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureSfOutputUrisIsMutable() {
        if (!sfOutputUris_.isModifiable()) {
          sfOutputUris_ = new com.google.protobuf.LazyStringArrayList(sfOutputUris_);
        }
        bitField0_ |= 0x00000008;
      }
      /**
       * <code>repeated string sf_output_uris = 4;</code>
       * @return A list containing the sfOutputUris.
       */
      public com.google.protobuf.ProtocolStringList
          getSfOutputUrisList() {
        sfOutputUris_.makeImmutable();
        return sfOutputUris_;
      }
      /**
       * <code>repeated string sf_output_uris = 4;</code>
       * @return The count of sfOutputUris.
       */
      public int getSfOutputUrisCount() {
        return sfOutputUris_.size();
      }
      /**
       * <code>repeated string sf_output_uris = 4;</code>
       * @param index The index of the element to return.
       * @return The sfOutputUris at the given index.
       */
      public java.lang.String getSfOutputUris(int index) {
        return sfOutputUris_.get(index);
      }
      /**
       * <code>repeated string sf_output_uris = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the sfOutputUris at the given index.
       */
      public com.google.protobuf.ByteString
          getSfOutputUrisBytes(int index) {
        return sfOutputUris_.getByteString(index);
      }
      /**
       * <code>repeated string sf_output_uris = 4;</code>
       * @param index The index to set the value at.
       * @param value The sfOutputUris to set.
       * @return This builder for chaining.
       */
      public Builder setSfOutputUris(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureSfOutputUrisIsMutable();
        sfOutputUris_.set(index, value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string sf_output_uris = 4;</code>
       * @param value The sfOutputUris to add.
       * @return This builder for chaining.
       */
      public Builder addSfOutputUris(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureSfOutputUrisIsMutable();
        sfOutputUris_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string sf_output_uris = 4;</code>
       * @param values The sfOutputUris to add.
       * @return This builder for chaining.
       */
      public Builder addAllSfOutputUris(
          java.lang.Iterable<java.lang.String> values) {
        ensureSfOutputUrisIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sfOutputUris_);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string sf_output_uris = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSfOutputUris() {
        sfOutputUris_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string sf_output_uris = 4;</code>
       * @param value The bytes of the sfOutputUris to add.
       * @return This builder for chaining.
       */
      public Builder addSfOutputUrisBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureSfOutputUrisIsMutable();
        sfOutputUris_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList sfInputIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureSfInputIdsIsMutable() {
        if (!sfInputIds_.isModifiable()) {
          sfInputIds_ = new com.google.protobuf.LazyStringArrayList(sfInputIds_);
        }
        bitField0_ |= 0x00000010;
      }
      /**
       * <code>repeated string sf_input_ids = 5;</code>
       * @return A list containing the sfInputIds.
       */
      public com.google.protobuf.ProtocolStringList
          getSfInputIdsList() {
        sfInputIds_.makeImmutable();
        return sfInputIds_;
      }
      /**
       * <code>repeated string sf_input_ids = 5;</code>
       * @return The count of sfInputIds.
       */
      public int getSfInputIdsCount() {
        return sfInputIds_.size();
      }
      /**
       * <code>repeated string sf_input_ids = 5;</code>
       * @param index The index of the element to return.
       * @return The sfInputIds at the given index.
       */
      public java.lang.String getSfInputIds(int index) {
        return sfInputIds_.get(index);
      }
      /**
       * <code>repeated string sf_input_ids = 5;</code>
       * @param index The index of the value to return.
       * @return The bytes of the sfInputIds at the given index.
       */
      public com.google.protobuf.ByteString
          getSfInputIdsBytes(int index) {
        return sfInputIds_.getByteString(index);
      }
      /**
       * <code>repeated string sf_input_ids = 5;</code>
       * @param index The index to set the value at.
       * @param value The sfInputIds to set.
       * @return This builder for chaining.
       */
      public Builder setSfInputIds(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureSfInputIdsIsMutable();
        sfInputIds_.set(index, value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string sf_input_ids = 5;</code>
       * @param value The sfInputIds to add.
       * @return This builder for chaining.
       */
      public Builder addSfInputIds(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureSfInputIdsIsMutable();
        sfInputIds_.add(value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string sf_input_ids = 5;</code>
       * @param values The sfInputIds to add.
       * @return This builder for chaining.
       */
      public Builder addAllSfInputIds(
          java.lang.Iterable<java.lang.String> values) {
        ensureSfInputIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sfInputIds_);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string sf_input_ids = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSfInputIds() {
        sfInputIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string sf_input_ids = 5;</code>
       * @param value The bytes of the sfInputIds to add.
       * @return This builder for chaining.
       */
      public Builder addSfInputIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureSfInputIdsIsMutable();
        sfInputIds_.add(value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList sfOutputIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureSfOutputIdsIsMutable() {
        if (!sfOutputIds_.isModifiable()) {
          sfOutputIds_ = new com.google.protobuf.LazyStringArrayList(sfOutputIds_);
        }
        bitField0_ |= 0x00000020;
      }
      /**
       * <code>repeated string sf_output_ids = 6;</code>
       * @return A list containing the sfOutputIds.
       */
      public com.google.protobuf.ProtocolStringList
          getSfOutputIdsList() {
        sfOutputIds_.makeImmutable();
        return sfOutputIds_;
      }
      /**
       * <code>repeated string sf_output_ids = 6;</code>
       * @return The count of sfOutputIds.
       */
      public int getSfOutputIdsCount() {
        return sfOutputIds_.size();
      }
      /**
       * <code>repeated string sf_output_ids = 6;</code>
       * @param index The index of the element to return.
       * @return The sfOutputIds at the given index.
       */
      public java.lang.String getSfOutputIds(int index) {
        return sfOutputIds_.get(index);
      }
      /**
       * <code>repeated string sf_output_ids = 6;</code>
       * @param index The index of the value to return.
       * @return The bytes of the sfOutputIds at the given index.
       */
      public com.google.protobuf.ByteString
          getSfOutputIdsBytes(int index) {
        return sfOutputIds_.getByteString(index);
      }
      /**
       * <code>repeated string sf_output_ids = 6;</code>
       * @param index The index to set the value at.
       * @param value The sfOutputIds to set.
       * @return This builder for chaining.
       */
      public Builder setSfOutputIds(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureSfOutputIdsIsMutable();
        sfOutputIds_.set(index, value);
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string sf_output_ids = 6;</code>
       * @param value The sfOutputIds to add.
       * @return This builder for chaining.
       */
      public Builder addSfOutputIds(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureSfOutputIdsIsMutable();
        sfOutputIds_.add(value);
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string sf_output_ids = 6;</code>
       * @param values The sfOutputIds to add.
       * @return This builder for chaining.
       */
      public Builder addAllSfOutputIds(
          java.lang.Iterable<java.lang.String> values) {
        ensureSfOutputIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sfOutputIds_);
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string sf_output_ids = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSfOutputIds() {
        sfOutputIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string sf_output_ids = 6;</code>
       * @param value The bytes of the sfOutputIds to add.
       * @return This builder for chaining.
       */
      public Builder addSfOutputIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureSfOutputIdsIsMutable();
        sfOutputIds_.add(value);
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig teeTaskConfig_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig, org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig.Builder, org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfigOrBuilder> teeTaskConfigBuilder_;
      /**
       * <code>.secretflow.pipeline.TaskConfig tee_task_config = 7;</code>
       * @return Whether the teeTaskConfig field is set.
       */
      public boolean hasTeeTaskConfig() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>.secretflow.pipeline.TaskConfig tee_task_config = 7;</code>
       * @return The teeTaskConfig.
       */
      public org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig getTeeTaskConfig() {
        if (teeTaskConfigBuilder_ == null) {
          return teeTaskConfig_ == null ? org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig.getDefaultInstance() : teeTaskConfig_;
        } else {
          return teeTaskConfigBuilder_.getMessage();
        }
      }
      /**
       * <code>.secretflow.pipeline.TaskConfig tee_task_config = 7;</code>
       */
      public Builder setTeeTaskConfig(org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig value) {
        if (teeTaskConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          teeTaskConfig_ = value;
        } else {
          teeTaskConfigBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.pipeline.TaskConfig tee_task_config = 7;</code>
       */
      public Builder setTeeTaskConfig(
          org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig.Builder builderForValue) {
        if (teeTaskConfigBuilder_ == null) {
          teeTaskConfig_ = builderForValue.build();
        } else {
          teeTaskConfigBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.pipeline.TaskConfig tee_task_config = 7;</code>
       */
      public Builder mergeTeeTaskConfig(org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig value) {
        if (teeTaskConfigBuilder_ == null) {
          if (((bitField0_ & 0x00000040) != 0) &&
            teeTaskConfig_ != null &&
            teeTaskConfig_ != org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig.getDefaultInstance()) {
            getTeeTaskConfigBuilder().mergeFrom(value);
          } else {
            teeTaskConfig_ = value;
          }
        } else {
          teeTaskConfigBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.pipeline.TaskConfig tee_task_config = 7;</code>
       */
      public Builder clearTeeTaskConfig() {
        bitField0_ = (bitField0_ & ~0x00000040);
        teeTaskConfig_ = null;
        if (teeTaskConfigBuilder_ != null) {
          teeTaskConfigBuilder_.dispose();
          teeTaskConfigBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.pipeline.TaskConfig tee_task_config = 7;</code>
       */
      public org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig.Builder getTeeTaskConfigBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getTeeTaskConfigFieldBuilder().getBuilder();
      }
      /**
       * <code>.secretflow.pipeline.TaskConfig tee_task_config = 7;</code>
       */
      public org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfigOrBuilder getTeeTaskConfigOrBuilder() {
        if (teeTaskConfigBuilder_ != null) {
          return teeTaskConfigBuilder_.getMessageOrBuilder();
        } else {
          return teeTaskConfig_ == null ?
              org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig.getDefaultInstance() : teeTaskConfig_;
        }
      }
      /**
       * <code>.secretflow.pipeline.TaskConfig tee_task_config = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig, org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig.Builder, org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfigOrBuilder> 
          getTeeTaskConfigFieldBuilder() {
        if (teeTaskConfigBuilder_ == null) {
          teeTaskConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig, org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfig.Builder, org.secretflow.proto.pipeline.TaskConfigOuterClass.TaskConfigOrBuilder>(
                  getTeeTaskConfig(),
                  getParentForChildren(),
                  isClean());
          teeTaskConfig_ = null;
        }
        return teeTaskConfigBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:secretflow.kuscia.TaskInputConfig)
    }

    // @@protoc_insertion_point(class_scope:secretflow.kuscia.TaskInputConfig)
    private static final org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig();
    }

    public static org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TaskInputConfig>
        PARSER = new com.google.protobuf.AbstractParser<TaskInputConfig>() {
      @java.lang.Override
      public TaskInputConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TaskInputConfig> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TaskInputConfig> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.secretflow.proto.kuscia.TaskConfig.TaskInputConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DatasourceConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:secretflow.kuscia.DatasourceConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();
  }
  /**
   * Protobuf type {@code secretflow.kuscia.DatasourceConfig}
   */
  public static final class DatasourceConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:secretflow.kuscia.DatasourceConfig)
      DatasourceConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DatasourceConfig.newBuilder() to construct.
    private DatasourceConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DatasourceConfig() {
      id_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DatasourceConfig();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.secretflow.proto.kuscia.TaskConfig.internal_static_secretflow_kuscia_DatasourceConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.secretflow.proto.kuscia.TaskConfig.internal_static_secretflow_kuscia_DatasourceConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig.class, org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig)) {
        return super.equals(obj);
      }
      org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig other = (org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code secretflow.kuscia.DatasourceConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:secretflow.kuscia.DatasourceConfig)
        org.secretflow.proto.kuscia.TaskConfig.DatasourceConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.secretflow.proto.kuscia.TaskConfig.internal_static_secretflow_kuscia_DatasourceConfig_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.secretflow.proto.kuscia.TaskConfig.internal_static_secretflow_kuscia_DatasourceConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig.class, org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig.Builder.class);
      }

      // Construct using org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.secretflow.proto.kuscia.TaskConfig.internal_static_secretflow_kuscia_DatasourceConfig_descriptor;
      }

      @java.lang.Override
      public org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig getDefaultInstanceForType() {
        return org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig.getDefaultInstance();
      }

      @java.lang.Override
      public org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig build() {
        org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig buildPartial() {
        org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig result = new org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig) {
          return mergeFrom((org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig other) {
        if (other == org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:secretflow.kuscia.DatasourceConfig)
    }

    // @@protoc_insertion_point(class_scope:secretflow.kuscia.DatasourceConfig)
    private static final org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig();
    }

    public static org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DatasourceConfig>
        PARSER = new com.google.protobuf.AbstractParser<DatasourceConfig>() {
      @java.lang.Override
      public DatasourceConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DatasourceConfig> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DatasourceConfig> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.secretflow.proto.kuscia.TaskConfig.DatasourceConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_secretflow_kuscia_TaskInputConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_secretflow_kuscia_TaskInputConfig_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_secretflow_kuscia_TaskInputConfig_SfDatasourceConfigEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_secretflow_kuscia_TaskInputConfig_SfDatasourceConfigEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_secretflow_kuscia_DatasourceConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_secretflow_kuscia_DatasourceConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*secretflow/protos/kuscia/task_config.p" +
      "roto\022\021secretflow.kuscia\032)secretflow/prot" +
      "os/component/cluster.proto\032)secretflow/p" +
      "rotos/pipeline/pipeline.proto\032,secretflo" +
      "w/protos/pipeline/task_config.proto\"\302\003\n\017" +
      "TaskInputConfig\022X\n\024sf_datasource_config\030" +
      "\001 \003(\0132:.secretflow.kuscia.TaskInputConfi" +
      "g.SfDatasourceConfigEntry\022<\n\017sf_cluster_" +
      "desc\030\002 \001(\0132#.secretflow.component.SFClus" +
      "terDesc\0228\n\022sf_node_eval_param\030\003 \001(\0132\034.se" +
      "cretflow.pipeline.NodeDef\022\026\n\016sf_output_u" +
      "ris\030\004 \003(\t\022\024\n\014sf_input_ids\030\005 \003(\t\022\025\n\rsf_ou" +
      "tput_ids\030\006 \003(\t\0228\n\017tee_task_config\030\007 \001(\0132" +
      "\037.secretflow.pipeline.TaskConfig\032^\n\027SfDa" +
      "tasourceConfigEntry\022\013\n\003key\030\001 \001(\t\0222\n\005valu" +
      "e\030\002 \001(\0132#.secretflow.kuscia.DatasourceCo" +
      "nfig:\0028\001\"\036\n\020DatasourceConfig\022\n\n\002id\030\001 \001(\t" +
      "B\035\n\033org.secretflow.proto.kusciab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.secretflow.proto.component.Cluster.getDescriptor(),
          org.secretflow.proto.pipeline.Pipeline.getDescriptor(),
          org.secretflow.proto.pipeline.TaskConfigOuterClass.getDescriptor(),
        });
    internal_static_secretflow_kuscia_TaskInputConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_secretflow_kuscia_TaskInputConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_secretflow_kuscia_TaskInputConfig_descriptor,
        new java.lang.String[] { "SfDatasourceConfig", "SfClusterDesc", "SfNodeEvalParam", "SfOutputUris", "SfInputIds", "SfOutputIds", "TeeTaskConfig", });
    internal_static_secretflow_kuscia_TaskInputConfig_SfDatasourceConfigEntry_descriptor =
      internal_static_secretflow_kuscia_TaskInputConfig_descriptor.getNestedTypes().get(0);
    internal_static_secretflow_kuscia_TaskInputConfig_SfDatasourceConfigEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_secretflow_kuscia_TaskInputConfig_SfDatasourceConfigEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_secretflow_kuscia_DatasourceConfig_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_secretflow_kuscia_DatasourceConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_secretflow_kuscia_DatasourceConfig_descriptor,
        new java.lang.String[] { "Id", });
    org.secretflow.proto.component.Cluster.getDescriptor();
    org.secretflow.proto.pipeline.Pipeline.getDescriptor();
    org.secretflow.proto.pipeline.TaskConfigOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
