// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: secretflow_serving/config/serving_config.proto

package secretflow.serving;

public final class ServingConfigOuterClass {
  private ServingConfigOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ServingConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:secretflow.serving.ServingConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Unique id of the serving service
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <pre>
     * Unique id of the serving service
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>.secretflow.serving.ServerConfig server_conf = 2;</code>
     * @return Whether the serverConf field is set.
     */
    boolean hasServerConf();
    /**
     * <code>.secretflow.serving.ServerConfig server_conf = 2;</code>
     * @return The serverConf.
     */
    secretflow.serving.ServerConfigOuterClass.ServerConfig getServerConf();
    /**
     * <code>.secretflow.serving.ServerConfig server_conf = 2;</code>
     */
    secretflow.serving.ServerConfigOuterClass.ServerConfigOrBuilder getServerConfOrBuilder();

    /**
     * <code>.secretflow.serving.ModelConfig model_conf = 3;</code>
     * @return Whether the modelConf field is set.
     */
    boolean hasModelConf();
    /**
     * <code>.secretflow.serving.ModelConfig model_conf = 3;</code>
     * @return The modelConf.
     */
    secretflow.serving.ModelConfigOuterClass.ModelConfig getModelConf();
    /**
     * <code>.secretflow.serving.ModelConfig model_conf = 3;</code>
     */
    secretflow.serving.ModelConfigOuterClass.ModelConfigOrBuilder getModelConfOrBuilder();

    /**
     * <code>.secretflow.serving.ClusterConfig cluster_conf = 4;</code>
     * @return Whether the clusterConf field is set.
     */
    boolean hasClusterConf();
    /**
     * <code>.secretflow.serving.ClusterConfig cluster_conf = 4;</code>
     * @return The clusterConf.
     */
    secretflow.serving.ClusterConfigOuterClass.ClusterConfig getClusterConf();
    /**
     * <code>.secretflow.serving.ClusterConfig cluster_conf = 4;</code>
     */
    secretflow.serving.ClusterConfigOuterClass.ClusterConfigOrBuilder getClusterConfOrBuilder();

    /**
     * <code>.secretflow.serving.FeatureSourceConfig feature_source_conf = 5;</code>
     * @return Whether the featureSourceConf field is set.
     */
    boolean hasFeatureSourceConf();
    /**
     * <code>.secretflow.serving.FeatureSourceConfig feature_source_conf = 5;</code>
     * @return The featureSourceConf.
     */
    secretflow.serving.FeatureConfig.FeatureSourceConfig getFeatureSourceConf();
    /**
     * <code>.secretflow.serving.FeatureSourceConfig feature_source_conf = 5;</code>
     */
    secretflow.serving.FeatureConfig.FeatureSourceConfigOrBuilder getFeatureSourceConfOrBuilder();
  }
  /**
   * <pre>
   * Related config of serving
   * </pre>
   *
   * Protobuf type {@code secretflow.serving.ServingConfig}
   */
  public static final class ServingConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:secretflow.serving.ServingConfig)
      ServingConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ServingConfig.newBuilder() to construct.
    private ServingConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServingConfig() {
      id_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ServingConfig();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return secretflow.serving.ServingConfigOuterClass.internal_static_secretflow_serving_ServingConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return secretflow.serving.ServingConfigOuterClass.internal_static_secretflow_serving_ServingConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              secretflow.serving.ServingConfigOuterClass.ServingConfig.class, secretflow.serving.ServingConfigOuterClass.ServingConfig.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <pre>
     * Unique id of the serving service
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Unique id of the serving service
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVER_CONF_FIELD_NUMBER = 2;
    private secretflow.serving.ServerConfigOuterClass.ServerConfig serverConf_;
    /**
     * <code>.secretflow.serving.ServerConfig server_conf = 2;</code>
     * @return Whether the serverConf field is set.
     */
    @java.lang.Override
    public boolean hasServerConf() {
      return serverConf_ != null;
    }
    /**
     * <code>.secretflow.serving.ServerConfig server_conf = 2;</code>
     * @return The serverConf.
     */
    @java.lang.Override
    public secretflow.serving.ServerConfigOuterClass.ServerConfig getServerConf() {
      return serverConf_ == null ? secretflow.serving.ServerConfigOuterClass.ServerConfig.getDefaultInstance() : serverConf_;
    }
    /**
     * <code>.secretflow.serving.ServerConfig server_conf = 2;</code>
     */
    @java.lang.Override
    public secretflow.serving.ServerConfigOuterClass.ServerConfigOrBuilder getServerConfOrBuilder() {
      return serverConf_ == null ? secretflow.serving.ServerConfigOuterClass.ServerConfig.getDefaultInstance() : serverConf_;
    }

    public static final int MODEL_CONF_FIELD_NUMBER = 3;
    private secretflow.serving.ModelConfigOuterClass.ModelConfig modelConf_;
    /**
     * <code>.secretflow.serving.ModelConfig model_conf = 3;</code>
     * @return Whether the modelConf field is set.
     */
    @java.lang.Override
    public boolean hasModelConf() {
      return modelConf_ != null;
    }
    /**
     * <code>.secretflow.serving.ModelConfig model_conf = 3;</code>
     * @return The modelConf.
     */
    @java.lang.Override
    public secretflow.serving.ModelConfigOuterClass.ModelConfig getModelConf() {
      return modelConf_ == null ? secretflow.serving.ModelConfigOuterClass.ModelConfig.getDefaultInstance() : modelConf_;
    }
    /**
     * <code>.secretflow.serving.ModelConfig model_conf = 3;</code>
     */
    @java.lang.Override
    public secretflow.serving.ModelConfigOuterClass.ModelConfigOrBuilder getModelConfOrBuilder() {
      return modelConf_ == null ? secretflow.serving.ModelConfigOuterClass.ModelConfig.getDefaultInstance() : modelConf_;
    }

    public static final int CLUSTER_CONF_FIELD_NUMBER = 4;
    private secretflow.serving.ClusterConfigOuterClass.ClusterConfig clusterConf_;
    /**
     * <code>.secretflow.serving.ClusterConfig cluster_conf = 4;</code>
     * @return Whether the clusterConf field is set.
     */
    @java.lang.Override
    public boolean hasClusterConf() {
      return clusterConf_ != null;
    }
    /**
     * <code>.secretflow.serving.ClusterConfig cluster_conf = 4;</code>
     * @return The clusterConf.
     */
    @java.lang.Override
    public secretflow.serving.ClusterConfigOuterClass.ClusterConfig getClusterConf() {
      return clusterConf_ == null ? secretflow.serving.ClusterConfigOuterClass.ClusterConfig.getDefaultInstance() : clusterConf_;
    }
    /**
     * <code>.secretflow.serving.ClusterConfig cluster_conf = 4;</code>
     */
    @java.lang.Override
    public secretflow.serving.ClusterConfigOuterClass.ClusterConfigOrBuilder getClusterConfOrBuilder() {
      return clusterConf_ == null ? secretflow.serving.ClusterConfigOuterClass.ClusterConfig.getDefaultInstance() : clusterConf_;
    }

    public static final int FEATURE_SOURCE_CONF_FIELD_NUMBER = 5;
    private secretflow.serving.FeatureConfig.FeatureSourceConfig featureSourceConf_;
    /**
     * <code>.secretflow.serving.FeatureSourceConfig feature_source_conf = 5;</code>
     * @return Whether the featureSourceConf field is set.
     */
    @java.lang.Override
    public boolean hasFeatureSourceConf() {
      return featureSourceConf_ != null;
    }
    /**
     * <code>.secretflow.serving.FeatureSourceConfig feature_source_conf = 5;</code>
     * @return The featureSourceConf.
     */
    @java.lang.Override
    public secretflow.serving.FeatureConfig.FeatureSourceConfig getFeatureSourceConf() {
      return featureSourceConf_ == null ? secretflow.serving.FeatureConfig.FeatureSourceConfig.getDefaultInstance() : featureSourceConf_;
    }
    /**
     * <code>.secretflow.serving.FeatureSourceConfig feature_source_conf = 5;</code>
     */
    @java.lang.Override
    public secretflow.serving.FeatureConfig.FeatureSourceConfigOrBuilder getFeatureSourceConfOrBuilder() {
      return featureSourceConf_ == null ? secretflow.serving.FeatureConfig.FeatureSourceConfig.getDefaultInstance() : featureSourceConf_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (serverConf_ != null) {
        output.writeMessage(2, getServerConf());
      }
      if (modelConf_ != null) {
        output.writeMessage(3, getModelConf());
      }
      if (clusterConf_ != null) {
        output.writeMessage(4, getClusterConf());
      }
      if (featureSourceConf_ != null) {
        output.writeMessage(5, getFeatureSourceConf());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (serverConf_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getServerConf());
      }
      if (modelConf_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getModelConf());
      }
      if (clusterConf_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getClusterConf());
      }
      if (featureSourceConf_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getFeatureSourceConf());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof secretflow.serving.ServingConfigOuterClass.ServingConfig)) {
        return super.equals(obj);
      }
      secretflow.serving.ServingConfigOuterClass.ServingConfig other = (secretflow.serving.ServingConfigOuterClass.ServingConfig) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (hasServerConf() != other.hasServerConf()) return false;
      if (hasServerConf()) {
        if (!getServerConf()
            .equals(other.getServerConf())) return false;
      }
      if (hasModelConf() != other.hasModelConf()) return false;
      if (hasModelConf()) {
        if (!getModelConf()
            .equals(other.getModelConf())) return false;
      }
      if (hasClusterConf() != other.hasClusterConf()) return false;
      if (hasClusterConf()) {
        if (!getClusterConf()
            .equals(other.getClusterConf())) return false;
      }
      if (hasFeatureSourceConf() != other.hasFeatureSourceConf()) return false;
      if (hasFeatureSourceConf()) {
        if (!getFeatureSourceConf()
            .equals(other.getFeatureSourceConf())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      if (hasServerConf()) {
        hash = (37 * hash) + SERVER_CONF_FIELD_NUMBER;
        hash = (53 * hash) + getServerConf().hashCode();
      }
      if (hasModelConf()) {
        hash = (37 * hash) + MODEL_CONF_FIELD_NUMBER;
        hash = (53 * hash) + getModelConf().hashCode();
      }
      if (hasClusterConf()) {
        hash = (37 * hash) + CLUSTER_CONF_FIELD_NUMBER;
        hash = (53 * hash) + getClusterConf().hashCode();
      }
      if (hasFeatureSourceConf()) {
        hash = (37 * hash) + FEATURE_SOURCE_CONF_FIELD_NUMBER;
        hash = (53 * hash) + getFeatureSourceConf().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static secretflow.serving.ServingConfigOuterClass.ServingConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static secretflow.serving.ServingConfigOuterClass.ServingConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static secretflow.serving.ServingConfigOuterClass.ServingConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static secretflow.serving.ServingConfigOuterClass.ServingConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static secretflow.serving.ServingConfigOuterClass.ServingConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static secretflow.serving.ServingConfigOuterClass.ServingConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static secretflow.serving.ServingConfigOuterClass.ServingConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static secretflow.serving.ServingConfigOuterClass.ServingConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static secretflow.serving.ServingConfigOuterClass.ServingConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static secretflow.serving.ServingConfigOuterClass.ServingConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static secretflow.serving.ServingConfigOuterClass.ServingConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static secretflow.serving.ServingConfigOuterClass.ServingConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(secretflow.serving.ServingConfigOuterClass.ServingConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Related config of serving
     * </pre>
     *
     * Protobuf type {@code secretflow.serving.ServingConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:secretflow.serving.ServingConfig)
        secretflow.serving.ServingConfigOuterClass.ServingConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return secretflow.serving.ServingConfigOuterClass.internal_static_secretflow_serving_ServingConfig_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return secretflow.serving.ServingConfigOuterClass.internal_static_secretflow_serving_ServingConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                secretflow.serving.ServingConfigOuterClass.ServingConfig.class, secretflow.serving.ServingConfigOuterClass.ServingConfig.Builder.class);
      }

      // Construct using secretflow.serving.ServingConfigOuterClass.ServingConfig.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        serverConf_ = null;
        if (serverConfBuilder_ != null) {
          serverConfBuilder_.dispose();
          serverConfBuilder_ = null;
        }
        modelConf_ = null;
        if (modelConfBuilder_ != null) {
          modelConfBuilder_.dispose();
          modelConfBuilder_ = null;
        }
        clusterConf_ = null;
        if (clusterConfBuilder_ != null) {
          clusterConfBuilder_.dispose();
          clusterConfBuilder_ = null;
        }
        featureSourceConf_ = null;
        if (featureSourceConfBuilder_ != null) {
          featureSourceConfBuilder_.dispose();
          featureSourceConfBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return secretflow.serving.ServingConfigOuterClass.internal_static_secretflow_serving_ServingConfig_descriptor;
      }

      @java.lang.Override
      public secretflow.serving.ServingConfigOuterClass.ServingConfig getDefaultInstanceForType() {
        return secretflow.serving.ServingConfigOuterClass.ServingConfig.getDefaultInstance();
      }

      @java.lang.Override
      public secretflow.serving.ServingConfigOuterClass.ServingConfig build() {
        secretflow.serving.ServingConfigOuterClass.ServingConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public secretflow.serving.ServingConfigOuterClass.ServingConfig buildPartial() {
        secretflow.serving.ServingConfigOuterClass.ServingConfig result = new secretflow.serving.ServingConfigOuterClass.ServingConfig(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(secretflow.serving.ServingConfigOuterClass.ServingConfig result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.serverConf_ = serverConfBuilder_ == null
              ? serverConf_
              : serverConfBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.modelConf_ = modelConfBuilder_ == null
              ? modelConf_
              : modelConfBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.clusterConf_ = clusterConfBuilder_ == null
              ? clusterConf_
              : clusterConfBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.featureSourceConf_ = featureSourceConfBuilder_ == null
              ? featureSourceConf_
              : featureSourceConfBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof secretflow.serving.ServingConfigOuterClass.ServingConfig) {
          return mergeFrom((secretflow.serving.ServingConfigOuterClass.ServingConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(secretflow.serving.ServingConfigOuterClass.ServingConfig other) {
        if (other == secretflow.serving.ServingConfigOuterClass.ServingConfig.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasServerConf()) {
          mergeServerConf(other.getServerConf());
        }
        if (other.hasModelConf()) {
          mergeModelConf(other.getModelConf());
        }
        if (other.hasClusterConf()) {
          mergeClusterConf(other.getClusterConf());
        }
        if (other.hasFeatureSourceConf()) {
          mergeFeatureSourceConf(other.getFeatureSourceConf());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getServerConfFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getModelConfFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getClusterConfFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                input.readMessage(
                    getFeatureSourceConfFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <pre>
       * Unique id of the serving service
       * </pre>
       *
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Unique id of the serving service
       * </pre>
       *
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Unique id of the serving service
       * </pre>
       *
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unique id of the serving service
       * </pre>
       *
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unique id of the serving service
       * </pre>
       *
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private secretflow.serving.ServerConfigOuterClass.ServerConfig serverConf_;
      private com.google.protobuf.SingleFieldBuilderV3<
          secretflow.serving.ServerConfigOuterClass.ServerConfig, secretflow.serving.ServerConfigOuterClass.ServerConfig.Builder, secretflow.serving.ServerConfigOuterClass.ServerConfigOrBuilder> serverConfBuilder_;
      /**
       * <code>.secretflow.serving.ServerConfig server_conf = 2;</code>
       * @return Whether the serverConf field is set.
       */
      public boolean hasServerConf() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.secretflow.serving.ServerConfig server_conf = 2;</code>
       * @return The serverConf.
       */
      public secretflow.serving.ServerConfigOuterClass.ServerConfig getServerConf() {
        if (serverConfBuilder_ == null) {
          return serverConf_ == null ? secretflow.serving.ServerConfigOuterClass.ServerConfig.getDefaultInstance() : serverConf_;
        } else {
          return serverConfBuilder_.getMessage();
        }
      }
      /**
       * <code>.secretflow.serving.ServerConfig server_conf = 2;</code>
       */
      public Builder setServerConf(secretflow.serving.ServerConfigOuterClass.ServerConfig value) {
        if (serverConfBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          serverConf_ = value;
        } else {
          serverConfBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.serving.ServerConfig server_conf = 2;</code>
       */
      public Builder setServerConf(
          secretflow.serving.ServerConfigOuterClass.ServerConfig.Builder builderForValue) {
        if (serverConfBuilder_ == null) {
          serverConf_ = builderForValue.build();
        } else {
          serverConfBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.serving.ServerConfig server_conf = 2;</code>
       */
      public Builder mergeServerConf(secretflow.serving.ServerConfigOuterClass.ServerConfig value) {
        if (serverConfBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            serverConf_ != null &&
            serverConf_ != secretflow.serving.ServerConfigOuterClass.ServerConfig.getDefaultInstance()) {
            getServerConfBuilder().mergeFrom(value);
          } else {
            serverConf_ = value;
          }
        } else {
          serverConfBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.serving.ServerConfig server_conf = 2;</code>
       */
      public Builder clearServerConf() {
        bitField0_ = (bitField0_ & ~0x00000002);
        serverConf_ = null;
        if (serverConfBuilder_ != null) {
          serverConfBuilder_.dispose();
          serverConfBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.serving.ServerConfig server_conf = 2;</code>
       */
      public secretflow.serving.ServerConfigOuterClass.ServerConfig.Builder getServerConfBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getServerConfFieldBuilder().getBuilder();
      }
      /**
       * <code>.secretflow.serving.ServerConfig server_conf = 2;</code>
       */
      public secretflow.serving.ServerConfigOuterClass.ServerConfigOrBuilder getServerConfOrBuilder() {
        if (serverConfBuilder_ != null) {
          return serverConfBuilder_.getMessageOrBuilder();
        } else {
          return serverConf_ == null ?
              secretflow.serving.ServerConfigOuterClass.ServerConfig.getDefaultInstance() : serverConf_;
        }
      }
      /**
       * <code>.secretflow.serving.ServerConfig server_conf = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          secretflow.serving.ServerConfigOuterClass.ServerConfig, secretflow.serving.ServerConfigOuterClass.ServerConfig.Builder, secretflow.serving.ServerConfigOuterClass.ServerConfigOrBuilder> 
          getServerConfFieldBuilder() {
        if (serverConfBuilder_ == null) {
          serverConfBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              secretflow.serving.ServerConfigOuterClass.ServerConfig, secretflow.serving.ServerConfigOuterClass.ServerConfig.Builder, secretflow.serving.ServerConfigOuterClass.ServerConfigOrBuilder>(
                  getServerConf(),
                  getParentForChildren(),
                  isClean());
          serverConf_ = null;
        }
        return serverConfBuilder_;
      }

      private secretflow.serving.ModelConfigOuterClass.ModelConfig modelConf_;
      private com.google.protobuf.SingleFieldBuilderV3<
          secretflow.serving.ModelConfigOuterClass.ModelConfig, secretflow.serving.ModelConfigOuterClass.ModelConfig.Builder, secretflow.serving.ModelConfigOuterClass.ModelConfigOrBuilder> modelConfBuilder_;
      /**
       * <code>.secretflow.serving.ModelConfig model_conf = 3;</code>
       * @return Whether the modelConf field is set.
       */
      public boolean hasModelConf() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.secretflow.serving.ModelConfig model_conf = 3;</code>
       * @return The modelConf.
       */
      public secretflow.serving.ModelConfigOuterClass.ModelConfig getModelConf() {
        if (modelConfBuilder_ == null) {
          return modelConf_ == null ? secretflow.serving.ModelConfigOuterClass.ModelConfig.getDefaultInstance() : modelConf_;
        } else {
          return modelConfBuilder_.getMessage();
        }
      }
      /**
       * <code>.secretflow.serving.ModelConfig model_conf = 3;</code>
       */
      public Builder setModelConf(secretflow.serving.ModelConfigOuterClass.ModelConfig value) {
        if (modelConfBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          modelConf_ = value;
        } else {
          modelConfBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.serving.ModelConfig model_conf = 3;</code>
       */
      public Builder setModelConf(
          secretflow.serving.ModelConfigOuterClass.ModelConfig.Builder builderForValue) {
        if (modelConfBuilder_ == null) {
          modelConf_ = builderForValue.build();
        } else {
          modelConfBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.serving.ModelConfig model_conf = 3;</code>
       */
      public Builder mergeModelConf(secretflow.serving.ModelConfigOuterClass.ModelConfig value) {
        if (modelConfBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            modelConf_ != null &&
            modelConf_ != secretflow.serving.ModelConfigOuterClass.ModelConfig.getDefaultInstance()) {
            getModelConfBuilder().mergeFrom(value);
          } else {
            modelConf_ = value;
          }
        } else {
          modelConfBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.serving.ModelConfig model_conf = 3;</code>
       */
      public Builder clearModelConf() {
        bitField0_ = (bitField0_ & ~0x00000004);
        modelConf_ = null;
        if (modelConfBuilder_ != null) {
          modelConfBuilder_.dispose();
          modelConfBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.serving.ModelConfig model_conf = 3;</code>
       */
      public secretflow.serving.ModelConfigOuterClass.ModelConfig.Builder getModelConfBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getModelConfFieldBuilder().getBuilder();
      }
      /**
       * <code>.secretflow.serving.ModelConfig model_conf = 3;</code>
       */
      public secretflow.serving.ModelConfigOuterClass.ModelConfigOrBuilder getModelConfOrBuilder() {
        if (modelConfBuilder_ != null) {
          return modelConfBuilder_.getMessageOrBuilder();
        } else {
          return modelConf_ == null ?
              secretflow.serving.ModelConfigOuterClass.ModelConfig.getDefaultInstance() : modelConf_;
        }
      }
      /**
       * <code>.secretflow.serving.ModelConfig model_conf = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          secretflow.serving.ModelConfigOuterClass.ModelConfig, secretflow.serving.ModelConfigOuterClass.ModelConfig.Builder, secretflow.serving.ModelConfigOuterClass.ModelConfigOrBuilder> 
          getModelConfFieldBuilder() {
        if (modelConfBuilder_ == null) {
          modelConfBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              secretflow.serving.ModelConfigOuterClass.ModelConfig, secretflow.serving.ModelConfigOuterClass.ModelConfig.Builder, secretflow.serving.ModelConfigOuterClass.ModelConfigOrBuilder>(
                  getModelConf(),
                  getParentForChildren(),
                  isClean());
          modelConf_ = null;
        }
        return modelConfBuilder_;
      }

      private secretflow.serving.ClusterConfigOuterClass.ClusterConfig clusterConf_;
      private com.google.protobuf.SingleFieldBuilderV3<
          secretflow.serving.ClusterConfigOuterClass.ClusterConfig, secretflow.serving.ClusterConfigOuterClass.ClusterConfig.Builder, secretflow.serving.ClusterConfigOuterClass.ClusterConfigOrBuilder> clusterConfBuilder_;
      /**
       * <code>.secretflow.serving.ClusterConfig cluster_conf = 4;</code>
       * @return Whether the clusterConf field is set.
       */
      public boolean hasClusterConf() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>.secretflow.serving.ClusterConfig cluster_conf = 4;</code>
       * @return The clusterConf.
       */
      public secretflow.serving.ClusterConfigOuterClass.ClusterConfig getClusterConf() {
        if (clusterConfBuilder_ == null) {
          return clusterConf_ == null ? secretflow.serving.ClusterConfigOuterClass.ClusterConfig.getDefaultInstance() : clusterConf_;
        } else {
          return clusterConfBuilder_.getMessage();
        }
      }
      /**
       * <code>.secretflow.serving.ClusterConfig cluster_conf = 4;</code>
       */
      public Builder setClusterConf(secretflow.serving.ClusterConfigOuterClass.ClusterConfig value) {
        if (clusterConfBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          clusterConf_ = value;
        } else {
          clusterConfBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.serving.ClusterConfig cluster_conf = 4;</code>
       */
      public Builder setClusterConf(
          secretflow.serving.ClusterConfigOuterClass.ClusterConfig.Builder builderForValue) {
        if (clusterConfBuilder_ == null) {
          clusterConf_ = builderForValue.build();
        } else {
          clusterConfBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.serving.ClusterConfig cluster_conf = 4;</code>
       */
      public Builder mergeClusterConf(secretflow.serving.ClusterConfigOuterClass.ClusterConfig value) {
        if (clusterConfBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            clusterConf_ != null &&
            clusterConf_ != secretflow.serving.ClusterConfigOuterClass.ClusterConfig.getDefaultInstance()) {
            getClusterConfBuilder().mergeFrom(value);
          } else {
            clusterConf_ = value;
          }
        } else {
          clusterConfBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.serving.ClusterConfig cluster_conf = 4;</code>
       */
      public Builder clearClusterConf() {
        bitField0_ = (bitField0_ & ~0x00000008);
        clusterConf_ = null;
        if (clusterConfBuilder_ != null) {
          clusterConfBuilder_.dispose();
          clusterConfBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.serving.ClusterConfig cluster_conf = 4;</code>
       */
      public secretflow.serving.ClusterConfigOuterClass.ClusterConfig.Builder getClusterConfBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getClusterConfFieldBuilder().getBuilder();
      }
      /**
       * <code>.secretflow.serving.ClusterConfig cluster_conf = 4;</code>
       */
      public secretflow.serving.ClusterConfigOuterClass.ClusterConfigOrBuilder getClusterConfOrBuilder() {
        if (clusterConfBuilder_ != null) {
          return clusterConfBuilder_.getMessageOrBuilder();
        } else {
          return clusterConf_ == null ?
              secretflow.serving.ClusterConfigOuterClass.ClusterConfig.getDefaultInstance() : clusterConf_;
        }
      }
      /**
       * <code>.secretflow.serving.ClusterConfig cluster_conf = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          secretflow.serving.ClusterConfigOuterClass.ClusterConfig, secretflow.serving.ClusterConfigOuterClass.ClusterConfig.Builder, secretflow.serving.ClusterConfigOuterClass.ClusterConfigOrBuilder> 
          getClusterConfFieldBuilder() {
        if (clusterConfBuilder_ == null) {
          clusterConfBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              secretflow.serving.ClusterConfigOuterClass.ClusterConfig, secretflow.serving.ClusterConfigOuterClass.ClusterConfig.Builder, secretflow.serving.ClusterConfigOuterClass.ClusterConfigOrBuilder>(
                  getClusterConf(),
                  getParentForChildren(),
                  isClean());
          clusterConf_ = null;
        }
        return clusterConfBuilder_;
      }

      private secretflow.serving.FeatureConfig.FeatureSourceConfig featureSourceConf_;
      private com.google.protobuf.SingleFieldBuilderV3<
          secretflow.serving.FeatureConfig.FeatureSourceConfig, secretflow.serving.FeatureConfig.FeatureSourceConfig.Builder, secretflow.serving.FeatureConfig.FeatureSourceConfigOrBuilder> featureSourceConfBuilder_;
      /**
       * <code>.secretflow.serving.FeatureSourceConfig feature_source_conf = 5;</code>
       * @return Whether the featureSourceConf field is set.
       */
      public boolean hasFeatureSourceConf() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>.secretflow.serving.FeatureSourceConfig feature_source_conf = 5;</code>
       * @return The featureSourceConf.
       */
      public secretflow.serving.FeatureConfig.FeatureSourceConfig getFeatureSourceConf() {
        if (featureSourceConfBuilder_ == null) {
          return featureSourceConf_ == null ? secretflow.serving.FeatureConfig.FeatureSourceConfig.getDefaultInstance() : featureSourceConf_;
        } else {
          return featureSourceConfBuilder_.getMessage();
        }
      }
      /**
       * <code>.secretflow.serving.FeatureSourceConfig feature_source_conf = 5;</code>
       */
      public Builder setFeatureSourceConf(secretflow.serving.FeatureConfig.FeatureSourceConfig value) {
        if (featureSourceConfBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          featureSourceConf_ = value;
        } else {
          featureSourceConfBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.serving.FeatureSourceConfig feature_source_conf = 5;</code>
       */
      public Builder setFeatureSourceConf(
          secretflow.serving.FeatureConfig.FeatureSourceConfig.Builder builderForValue) {
        if (featureSourceConfBuilder_ == null) {
          featureSourceConf_ = builderForValue.build();
        } else {
          featureSourceConfBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.serving.FeatureSourceConfig feature_source_conf = 5;</code>
       */
      public Builder mergeFeatureSourceConf(secretflow.serving.FeatureConfig.FeatureSourceConfig value) {
        if (featureSourceConfBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
            featureSourceConf_ != null &&
            featureSourceConf_ != secretflow.serving.FeatureConfig.FeatureSourceConfig.getDefaultInstance()) {
            getFeatureSourceConfBuilder().mergeFrom(value);
          } else {
            featureSourceConf_ = value;
          }
        } else {
          featureSourceConfBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.serving.FeatureSourceConfig feature_source_conf = 5;</code>
       */
      public Builder clearFeatureSourceConf() {
        bitField0_ = (bitField0_ & ~0x00000010);
        featureSourceConf_ = null;
        if (featureSourceConfBuilder_ != null) {
          featureSourceConfBuilder_.dispose();
          featureSourceConfBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.serving.FeatureSourceConfig feature_source_conf = 5;</code>
       */
      public secretflow.serving.FeatureConfig.FeatureSourceConfig.Builder getFeatureSourceConfBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getFeatureSourceConfFieldBuilder().getBuilder();
      }
      /**
       * <code>.secretflow.serving.FeatureSourceConfig feature_source_conf = 5;</code>
       */
      public secretflow.serving.FeatureConfig.FeatureSourceConfigOrBuilder getFeatureSourceConfOrBuilder() {
        if (featureSourceConfBuilder_ != null) {
          return featureSourceConfBuilder_.getMessageOrBuilder();
        } else {
          return featureSourceConf_ == null ?
              secretflow.serving.FeatureConfig.FeatureSourceConfig.getDefaultInstance() : featureSourceConf_;
        }
      }
      /**
       * <code>.secretflow.serving.FeatureSourceConfig feature_source_conf = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          secretflow.serving.FeatureConfig.FeatureSourceConfig, secretflow.serving.FeatureConfig.FeatureSourceConfig.Builder, secretflow.serving.FeatureConfig.FeatureSourceConfigOrBuilder> 
          getFeatureSourceConfFieldBuilder() {
        if (featureSourceConfBuilder_ == null) {
          featureSourceConfBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              secretflow.serving.FeatureConfig.FeatureSourceConfig, secretflow.serving.FeatureConfig.FeatureSourceConfig.Builder, secretflow.serving.FeatureConfig.FeatureSourceConfigOrBuilder>(
                  getFeatureSourceConf(),
                  getParentForChildren(),
                  isClean());
          featureSourceConf_ = null;
        }
        return featureSourceConfBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:secretflow.serving.ServingConfig)
    }

    // @@protoc_insertion_point(class_scope:secretflow.serving.ServingConfig)
    private static final secretflow.serving.ServingConfigOuterClass.ServingConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new secretflow.serving.ServingConfigOuterClass.ServingConfig();
    }

    public static secretflow.serving.ServingConfigOuterClass.ServingConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServingConfig>
        PARSER = new com.google.protobuf.AbstractParser<ServingConfig>() {
      @java.lang.Override
      public ServingConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ServingConfig> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServingConfig> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public secretflow.serving.ServingConfigOuterClass.ServingConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_secretflow_serving_ServingConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_secretflow_serving_ServingConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.secretflow_serving/config/serving_conf" +
      "ig.proto\022\022secretflow.serving\032-secretflow" +
      "_serving/config/server_config.proto\032.sec" +
      "retflow_serving/config/cluster_config.pr" +
      "oto\032,secretflow_serving/config/model_con" +
      "fig.proto\032.secretflow_serving/config/fea" +
      "ture_config.proto\"\206\002\n\rServingConfig\022\n\n\002i" +
      "d\030\001 \001(\t\0225\n\013server_conf\030\002 \001(\0132 .secretflo" +
      "w.serving.ServerConfig\0223\n\nmodel_conf\030\003 \001" +
      "(\0132\037.secretflow.serving.ModelConfig\0227\n\014c" +
      "luster_conf\030\004 \001(\0132!.secretflow.serving.C" +
      "lusterConfig\022D\n\023feature_source_conf\030\005 \001(" +
      "\0132\'.secretflow.serving.FeatureSourceConf" +
      "igb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          secretflow.serving.ServerConfigOuterClass.getDescriptor(),
          secretflow.serving.ClusterConfigOuterClass.getDescriptor(),
          secretflow.serving.ModelConfigOuterClass.getDescriptor(),
          secretflow.serving.FeatureConfig.getDescriptor(),
        });
    internal_static_secretflow_serving_ServingConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_secretflow_serving_ServingConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_secretflow_serving_ServingConfig_descriptor,
        new java.lang.String[] { "Id", "ServerConf", "ModelConf", "ClusterConf", "FeatureSourceConf", });
    secretflow.serving.ServerConfigOuterClass.getDescriptor();
    secretflow.serving.ClusterConfigOuterClass.getDescriptor();
    secretflow.serving.ModelConfigOuterClass.getDescriptor();
    secretflow.serving.FeatureConfig.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
